# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:56f23c3c5922dca60d8da85814d3ea592b236e45ace64bdd6f2a16b59f4f83ff
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.ByteRange do
  @moduledoc "A byte range — start (inclusive) to end (exclusive)."

  @typedoc "A byte range — start (inclusive) to end (exclusive)."
  @type t :: %__MODULE__{
          start: non_neg_integer(),
          end: non_neg_integer()
        }

  defstruct start: 0,
            end: 0
end
