# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:48eaa6aee6a9621260908f86b470f0394ca8594aea6b158a71425b92dd28df38
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.ByteRange do
  @moduledoc "A byte range — start (inclusive) to end (exclusive)."

  @typedoc "A byte range — start (inclusive) to end (exclusive)."
  @type t :: %__MODULE__{
          start: non_neg_integer(),
          end: non_neg_integer()
        }

  defstruct start: 0,
            end: 0
end
