# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:978bc431acc0418fd4fcd597ac48a8d2b6987f96ee4e36c38b8f8ac356fcc3f3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule TreeSitterLanguagePack.CodeChunk do
  @moduledoc "A chunk of source code with rich metadata."

  @typedoc "A chunk of source code with rich metadata."
  @type t :: %__MODULE__{
          content: String.t() | nil,
          start_byte: non_neg_integer(),
          end_byte: non_neg_integer(),
          start_line: non_neg_integer(),
          end_line: non_neg_integer(),
          metadata: map()
        }

  defstruct content: nil,
            start_byte: 0,
            end_byte: 0,
            start_line: 0,
            end_line: 0,
            metadata: nil
end
