# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1e53873ba7c6fb78d43a50a5f9ec4d333cb245894368f553824b3a1c1d128dd6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule TreeSitterLanguagePack.CommentInfo do
  @moduledoc "A comment extracted from source code."

  defstruct text: "",
            kind: :line,
            span: nil,
            associated_node: ""
end
