# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6827e9e46c4825bb50ca9c0cb0367a738622ea498d20c872a682f0f26a16370a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule TreeSitterLanguagePack.CommentKind do
  @moduledoc "The kind of a comment found in source code."

  @type t :: :line | :block | :doc

  @line :line
  @block :block
  @doc_attr :doc

  @spec line() :: t()
  def line, do: @line
  @spec block() :: t()
  def block, do: @block
  @spec doc() :: t()
  def doc, do: @doc_attr
end
