# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:51db1f59c5dc5547edd27bf45dcb4b40b4b2dffbc060de9765bd672d6c7208dd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule TreeSitterLanguagePack.CommentInfo do
  @moduledoc "A comment extracted from source code."

  defstruct text: "",
            kind: :line,
            span: nil,
            associated_node: ""
end
