# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:360e02edf70c86e2e1a835db7f366f6b66fdd0a250df7395639cdaa155a85d21
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.CommentKind do
  @moduledoc """
  The kind of a comment found in source code.

  Distinguishes between single-line comments, block (multi-line) comments,
  and documentation comments.
  """

  @typedoc "The kind of a comment found in source code."
  @type t :: :line | :block | :doc

  @line :line
  @block :block
  @doc_attr :doc

  @doc "A single-line comment (e.g., `// ...` or `# ...`)."
  @spec line() :: t()
  def line, do: @line
  @doc "A block or multi-line comment using slash-star delimiters."
  @spec block() :: t()
  def block, do: @block
  @doc "A documentation comment such as `/// ...` or slash-double-star block."
  @spec doc() :: t()
  def doc, do: @doc_attr
end
