# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:366e4c8ea9d7faf2f7f60323b445cf09d7d68f3d820d87ae297aed3b4a4fc643
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.CommentKind do
  @moduledoc """
  The kind of a comment found in source code.

  Distinguishes between single-line comments, block (multi-line) comments,
  and documentation comments.
  """

  @typedoc "The kind of a comment found in source code."
  @type t :: :line | :block | :doc

  @line :line
  @block :block
  @doc_attr :doc

  @spec line() :: t()
  def line, do: @line
  @spec block() :: t()
  def block, do: @block
  @spec doc() :: t()
  def doc, do: @doc_attr
end
