# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4fd28d28be5d5c08a42b1adaeb8565a890c281118692f20fb4e08cfac6ad7fcf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.CommentInfo do
  @moduledoc "A comment extracted from source code."

  @typedoc "A comment extracted from source code."
  @type t :: %__MODULE__{
          text: String.t() | nil,
          kind: String.t() | nil,
          span: map(),
          associated_node: String.t() | nil
        }

  defstruct text: nil,
            kind: :line,
            span: nil,
            associated_node: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
