# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8bb43fc12f987b2e754f9b1981768a07345d578eb7fe7f956b844c10cb2c2988
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.DataAttribute do
  @moduledoc """
  An XML-style attribute attached to an [`Element`](DataNodeKind::Element) node.

  Populated only for `DataNodeKind::Element`; always empty for `KeyValue` and
  `Sequence` nodes.
  """

  @typedoc "An XML-style attribute attached to an [`Element`](DataNodeKind::Element) node."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          value: String.t() | nil,
          span: map()
        }

  defstruct name: nil,
            value: nil,
            span: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
