# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c002663109334001160146102a13266f3ca774d1b8db4b14bd516ae3fe074f29
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule TreeSitterLanguagePack.Diagnostic do
  @moduledoc "A diagnostic (syntax error, missing node, etc.) from parsing."

  @type t :: %__MODULE__{
          message: String.t() | nil,
          severity: String.t() | nil,
          span: map()
        }

  defstruct message: nil,
            severity: :error,
            span: nil
end
