# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:88a4e3831f755c3d1b90d9dcd6ac92228a8544dcfd080215fd098f599ab15d8d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule TreeSitterLanguagePack.DiagnosticSeverity do
  @moduledoc "Severity level of a diagnostic produced during parsing."

  @type t :: :error | :warning | :info

  @error :error
  @warning :warning
  @info :info

  @spec error() :: t()
  def error, do: @error
  @spec warning() :: t()
  def warning, do: @warning
  @spec info() :: t()
  def info, do: @info
end
