# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c144df140f32d859ddcba2385d5692e139a51d66c3d500a17774045f2732bee5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule TreeSitterLanguagePack.Diagnostic do
  @moduledoc "A diagnostic (syntax error, missing node, etc.) from parsing."

  defstruct message: "",
            severity: :error,
            span: nil
end
