# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:44a0d5babc63706f84f2e19d48cf948b55c87cbbe3e341ee15c08a54f4d42d8f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.DiagnosticSeverity do
  @moduledoc """
  Severity level of a diagnostic produced during parsing.

  Used to classify parse errors, warnings, and informational messages
  found in the syntax tree.
  """

  @typedoc "Severity level of a diagnostic produced during parsing."
  @type t :: :error | :warning | :info

  @error :error
  @warning :warning
  @info :info

  @spec error() :: t()
  def error, do: @error
  @spec warning() :: t()
  def warning, do: @warning
  @spec info() :: t()
  def info, do: @info
end
