# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ba3d64f1bdbc733556a596b2718817609290c351656742357e98689aba93f174
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.Diagnostic do
  @moduledoc "A diagnostic (syntax error, missing node, etc.) from parsing."

  @typedoc "A diagnostic (syntax error, missing node, etc.) from parsing."
  @type t :: %__MODULE__{
          message: String.t() | nil,
          severity: String.t() | nil,
          span: map()
        }

  defstruct message: nil,
            severity: :error,
            span: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
