# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2cf13e2f60e3da15da80d1cbc74475f1620dd146d2dd38c8ece56418c6448772
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule TreeSitterLanguagePack.DocSection do
  @moduledoc "A section within a docstring (e.g., Args, Returns, Raises)."

  defstruct kind: "",
            name: "",
            description: ""
end
