# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7bec16f5c828b57399dc70e8709c84b136820496848b19e2e73499bff909745b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule TreeSitterLanguagePack.DocSection do
  @moduledoc "A section within a docstring (e.g., Args, Returns, Raises)."

  @typedoc "A section within a docstring (e.g., Args, Returns, Raises)."
  @type t :: %__MODULE__{
          kind: String.t() | nil,
          name: String.t() | nil,
          description: String.t() | nil
        }

  defstruct kind: nil,
            name: nil,
            description: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
