# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b84d8e689acc9613a6de6d643c7cfb6d6c4b357a073a66008bb8618a031a5829
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule TreeSitterLanguagePack.DocstringFormat do
  @moduledoc "The format of a docstring extracted from source code."

  @type t :: term()

  @type python_triple_quote :: :python_triple_quote
  @type js_doc :: :js_doc
  @type rustdoc :: :rustdoc
  @type go_doc :: :go_doc
  @type java_doc :: :java_doc
  @type other :: %{type: :other, value_0: term()}
end
