# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:eafdd9d7178a2638060ef75fbdbbd878f44de4d095f40339ca9dc8f615f707ed
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.DocstringInfo do
  @moduledoc "A docstring extracted from source code."

  @typedoc "A docstring extracted from source code."
  @type t :: %__MODULE__{
          text: String.t() | nil,
          format: String.t() | nil,
          span: map(),
          associated_item: String.t() | nil,
          parsed_sections: [map()]
        }

  defstruct text: nil,
            format: :python_triple_quote,
            span: nil,
            associated_item: nil,
            parsed_sections: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
