# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:662dbbf50555ef0b3d0f168ee43cdb4ecd8316e31f16c1cbb2adb942fbf9d618
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule TreeSitterLanguagePack.DocstringFormat do
  @moduledoc """
  The format of a docstring extracted from source code.

  Identifies the docstring convention used, which varies by language
  (e.g., Python triple-quoted strings, JSDoc, Rustdoc `///` comments).
  """

  @typedoc "The format of a docstring extracted from source code."
  @type t :: term()

  @type python_triple_quote :: :python_triple_quote
  @type js_doc :: :js_doc
  @type rustdoc :: :rustdoc
  @type go_doc :: :go_doc
  @type java_doc :: :java_doc
  @type other :: %{type: :other, value: String.t()}
end
