# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f1b49da8b8d934eb13d7453e1cf4e27ae81c6449e165f6addb8ebe5d308bab59
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.DownloadManager do
  @moduledoc "Manages downloading and caching of pre-built parser shared libraries."

  alias TreeSitterLanguagePack.Native
  defstruct [:ref]

  @typedoc "Manages downloading and caching of pre-built parser shared libraries."
  @type t :: %__MODULE__{ref: reference()}

  @doc "Create a new download manager for the given version."
  def new(version) do
    ref = Native.downloadmanager_new(version)
    %__MODULE__{ref: ref}
  end

  @doc "List languages that are already downloaded and cached."
  def installed_languages(obj) do
    Native.downloadmanager_installed_languages(obj.ref)
  end

  @doc "Download the platform bundle and extract every library file it contains."
  def download_all_best_effort(obj) do
    Native.downloadmanager_download_all_best_effort(obj.ref)
  end

  @doc "Remove all cached parser libraries."
  def clean_cache(obj) do
    Native.downloadmanager_clean_cache(obj.ref)
  end
end
