# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3dc68255f40ca241893f3fca14122738a4ea94585b34d1c0a3e2f31afd64ee35
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.ExportKind do
  @moduledoc """
  The kind of an export statement found in source code.

  Covers named exports, default exports, and re-exports from other modules.
  """

  @typedoc "The kind of an export statement found in source code."
  @type t :: :named | :default | :re_export

  @named :named
  @default :default
  @re_export :re_export

  @spec named() :: t()
  def named, do: @named
  @spec default() :: t()
  def default, do: @default
  @spec re_export() :: t()
  def re_export, do: @re_export
end
