# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:44a0d5babc63706f84f2e19d48cf948b55c87cbbe3e341ee15c08a54f4d42d8f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.ExportInfo do
  @moduledoc "An export statement extracted from source code."

  @typedoc "An export statement extracted from source code."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          kind: String.t() | nil,
          span: map()
        }

  defstruct name: nil,
            kind: :named,
            span: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
