# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3ecaa5f0af29375f061d9a41abe233c9a14fcebb22dc4ec835189470fad755b9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.ExportInfo do
  @moduledoc "An export statement extracted from source code."

  @typedoc "An export statement extracted from source code."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          kind: String.t() | nil,
          span: map()
        }

  defstruct name: nil,
            kind: :named,
            span: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
