# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d26334202a156c91e05dfb8839c3fd09447822552054d1364baee8d453570e3b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule TreeSitterLanguagePack.FileMetrics do
  @moduledoc "Aggregate metrics for a source file."

  defstruct total_lines: 0,
            code_lines: 0,
            comment_lines: 0,
            blank_lines: 0,
            total_bytes: 0,
            node_count: 0,
            error_count: 0,
            max_depth: 0
end
