# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:253def366a3f77ef3673ca5129ce8e752546834f68e89a382acbd2a8781a7d1c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.Language do
  @moduledoc false

  defstruct [:ref]

  @type t :: %__MODULE__{ref: reference()}
end
