# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:01bf6aa26f9bca431e424c671c222e81859dd415a27e38197131e42f97ec61e9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule TreeSitterLanguagePack.LanguageInfo do
  @moduledoc false

  defstruct group: "",
            size: 0
end
