# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:662dbbf50555ef0b3d0f168ee43cdb4ecd8316e31f16c1cbb2adb942fbf9d618
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule TreeSitterLanguagePack.Language do
  @moduledoc false

  defstruct [:ref]

  @type t :: %__MODULE__{ref: reference()}
end
