# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:52fb9cedcf32c3a7838ef1c7ff5f663e043f0c76a844f0030d38b3f321ca006f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule TreeSitterLanguagePack.PackConfig do
  @moduledoc "Configuration for the tree-sitter language pack."

  defstruct cache_dir: "",
            languages: [],
            groups: []
end
