# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ba8e9a192f47d20b3f15b79f3ebf45d7f3385af6b0611426539ef7dc098daf2d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule TreeSitterLanguagePack.PackConfig do
  @moduledoc "Configuration for the tree-sitter language pack."

  defstruct cache_dir: "",
            languages: [],
            groups: []
end
