# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8aaf0fc7b8b894087df85c509a255452403f589109687dca9f2d309ce7f26d73
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule TreeSitterLanguagePack.PackConfig do
  @moduledoc "Configuration for the tree-sitter language pack."

  defstruct cache_dir: "",
            languages: [],
            groups: []
end
