# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:73c8a9205734ca144196dab2d166bd5a18c97ba37fc8c654993ef7b2beb04b8a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule TreeSitterLanguagePack.ParserManifest do
  @moduledoc "Manifest describing available parser downloads for a specific version."

  defstruct version: "",
            platforms: %{},
            languages: %{},
            groups: %{}
end
