# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cc54023a622f66efd7b0f3e25962ffc5a04abdd39e32750f87240dd8255b33a8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule TreeSitterLanguagePack.PlatformBundle do
  @moduledoc false

  defstruct url: "",
            sha256: "",
            size: 0
end
