# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a43a7c3dd7356c9e831c86cc5a386de867cd00fec9ff36c1607c0e9a51ea5f4d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.Point do
  @moduledoc "A source position — row + column, zero-indexed."

  @typedoc "A source position — row + column, zero-indexed."
  @type t :: %__MODULE__{
          row: non_neg_integer(),
          column: non_neg_integer()
        }

  defstruct row: 0,
            column: 0
end
