# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d156b3f21d3da47b056bc94d5a2efc5ee0d8c6d26a733a0f453b579ce100d595
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.Point do
  @moduledoc "A source position — row + column, zero-indexed."

  @typedoc "A source position — row + column, zero-indexed."
  @type t :: %__MODULE__{
          row: non_neg_integer(),
          column: non_neg_integer()
        }

  defstruct row: 0,
            column: 0
end
