# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7bec16f5c828b57399dc70e8709c84b136820496848b19e2e73499bff909745b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule TreeSitterLanguagePack.Point do
  @moduledoc "A source position — row + column, zero-indexed."

  @typedoc "A source position — row + column, zero-indexed."
  @type t :: %__MODULE__{
          row: non_neg_integer(),
          column: non_neg_integer()
        }

  defstruct row: 0,
            column: 0
end
