# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:30db5d09cdd3692f8e76340674c39add252d5c94932b2ca72d627a903bf30693
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule TreeSitterLanguagePack.ProcessConfig do
  @moduledoc "Configuration for the `process()` function."

  defstruct language: "",
            structure: true,
            imports: true,
            exports: true,
            comments: false,
            docstrings: false,
            symbols: false,
            diagnostics: false,
            chunk_max_size: nil
end
