# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a43a7c3dd7356c9e831c86cc5a386de867cd00fec9ff36c1607c0e9a51ea5f4d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.StructureKind do
  @moduledoc """
  The kind of structural item found in source code.

  Categorizes top-level and nested declarations such as functions, classes,
  structs, enums, traits, and more. Use [`Other`](StructureKind::Other) for
  language-specific constructs that do not fit a standard category.
  """

  @typedoc "The kind of structural item found in source code."
  @type t :: term()

  @type function_variant :: :function
  @type method :: :method
  @type class :: :class
  @type struct_variant :: :struct
  @type interface :: :interface
  @type enum :: :enum
  @type module_variant :: :module
  @type trait :: :trait
  @type impl :: :impl
  @type namespace :: :namespace
  @type other :: %{type: :other, value: String.t()}
end
