# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:253def366a3f77ef3673ca5129ce8e752546834f68e89a382acbd2a8781a7d1c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.SymbolKind do
  @moduledoc """
  The kind of a symbol definition found in source code.

  Categorizes symbol definitions such as variables, constants, functions,
  classes, types, interfaces, enums, and modules.
  """

  @typedoc "The kind of a symbol definition found in source code."
  @type t :: term()

  @type variable :: :variable
  @type constant :: :constant
  @type function_variant :: :function
  @type class :: :class
  @type type :: :type
  @type interface :: :interface
  @type enum :: :enum
  @type module_variant :: :module
  @type other :: %{type: :other, value: String.t()}
end
