# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3dc68255f40ca241893f3fca14122738a4ea94585b34d1c0a3e2f31afd64ee35
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.SymbolInfo do
  @moduledoc "A symbol (variable, function, type, etc.) extracted from source code."

  @typedoc "A symbol (variable, function, type, etc.) extracted from source code."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          kind: String.t() | nil,
          span: map(),
          type_annotation: String.t() | nil,
          doc: String.t() | nil
        }

  defstruct name: nil,
            kind: :variable,
            span: nil,
            type_annotation: nil,
            doc: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
