# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:75f9fdfbf3b6ada898acef5b8762a3958472df8ac798b8aa1fb5bd2fba2d5f1f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule TreeSitterLanguagePack.Tree do
  @moduledoc "A parsed syntax tree. Cheap to clone (refcount bump)."

  alias TreeSitterLanguagePack.Native

  defstruct [:ref]

  @typedoc "A parsed syntax tree. Cheap to clone (refcount bump)."
  @type t :: %__MODULE__{ref: reference()}

  @doc "Return the root [`Node`] of this tree."
  def root_node(obj) do
    Native.tree_root_node(obj.ref)
  end

  @doc "Return a [`TreeCursor`] positioned at the root."
  def walk(obj) do
    Native.tree_walk(obj.ref)
  end
end
