# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6125571a3e8d71b1bf26c8a105b8f42f97acba36088cabe6d2ac4064fef4370d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.TreeCursor do
  @moduledoc "A cursor for traversing a [`Tree`]."

  alias TreeSitterLanguagePack.Native
  defstruct [:ref]

  @typedoc "A cursor for traversing a [`Tree`]."
  @type t :: %__MODULE__{ref: reference()}

  @doc "Return the [`Node`] at the cursor's current position."
  def node(obj) do
    Native.treecursor_node(obj.ref)
  end

  @doc "Move the cursor to the first child of the current node."
  def goto_first_child(obj) do
    Native.treecursor_goto_first_child(obj.ref)
  end

  @doc "Move the cursor to the parent of the current node."
  def goto_parent(obj) do
    Native.treecursor_goto_parent(obj.ref)
  end

  @doc "Move the cursor to the next sibling of the current node."
  def goto_next_sibling(obj) do
    Native.treecursor_goto_next_sibling(obj.ref)
  end

  @doc "Return the field name for the current node, if any."
  def field_name(obj) do
    Native.treecursor_field_name(obj.ref)
  end
end
