# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:eafdd9d7178a2638060ef75fbdbbd878f44de4d095f40339ca9dc8f615f707ed
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule TreeSitterLanguagePack.Tree do
  @moduledoc "A parsed syntax tree. Cheap to clone (refcount bump)."

  alias TreeSitterLanguagePack.Native

  defstruct [:ref]

  @typedoc "A parsed syntax tree. Cheap to clone (refcount bump)."
  @type t :: %__MODULE__{ref: reference()}

  @doc "Return the root [`Node`] of this tree."
  def root_node(obj) do
    Native.tree_root_node(obj.ref)
  end

  @doc "Return a [`TreeCursor`] positioned at the root."
  def walk(obj) do
    Native.tree_walk(obj.ref)
  end
end
