// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:73d6ebd2ae99bfcd45abf84aa28e1ed6136847bdc9242fcda7f9ab26367c3320
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 30000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
	},
});
