// Generated by alef. Do not edit by hand.
// alef:hash:5c3eac2ef7892df9942263b2ef22bbce08c4729cfb235dcd7f37f968755d1b10

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "tree-sitter-language-pack-android-e2e"
