// Generated by alef. Do not edit by hand.
// alef:hash:a75894bce1172ba6b89bc9875127252be45cd1366073697501a5f134fc884d1a

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "tree-sitter-language-pack-android-e2e"
