// Generated by alef. Do not edit by hand.
// alef:hash:44bf370dc28fc7bcdb3c87c19256c2f869ee3ad3cbf23b099fe87eb219d7b161

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.10.0"
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "tree-sitter-language-pack-android-e2e"
