// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9ec4ae3cc82401fa5c9fe8b284cb90a9e539a42d5bb25c3742f28ff11a90a1a6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.IO;
using System.Runtime.CompilerServices;

namespace Kreuzberg.E2eTests;

internal static class TestSetup
{
    [ModuleInitializer]
    internal static void Init()
    {
        // Walk up from the assembly directory until we find the repo root
        // (the directory containing test_documents/) so that fixture paths
        // like "docx/fake.docx" resolve regardless of where dotnet test
        // launched the runner from.
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir != null)
        {
            var candidate = Path.Combine(dir.FullName, "test_documents");
            if (Directory.Exists(candidate))
            {
                Directory.SetCurrentDirectory(candidate);
                return;
            }
            dir = dir.Parent;
        }
    }
}
