# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: query
defmodule E2e.QueryTest do
  use ExUnit.Case, async: false

  describe "highlights_nonexistent_language" do
    @tag :skip
    test "Get highlights query for nonexistent language returns null/empty" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "highlights_query_rust" do
    @tag :skip
    test "get_highlights_query returns non-empty string for rust" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "highlights_query_unknown_language" do
    @tag :skip
    test "get_highlights_query returns None for unknown language" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "injections_query_rust" do
    @tag :skip
    test "get_injections_query returns non-empty for rust" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "injections_query_unknown_language" do
    @tag :skip
    test "get_injections_query returns empty for unknown language" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "locals_query_cue" do
    @tag :skip
    test "get_locals_query returns non-empty for cue" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "locals_query_unknown_language" do
    @tag :skip
    test "get_locals_query returns empty for unknown language" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end
end
