# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7c2ad6574f6e1041a85475b2fb60302a621b00af3af9ae49ceacb610d7676405
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require 'json'
require 'sorbet-runtime'
require 'ts_pack_core_rb'
