# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:366e4c8ea9d7faf2f7f60323b445cf09d7d68f3d820d87ae297aed3b4a4fc643
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require "json"
require "sorbet-runtime"
require "ts_pack_core_rb"
