# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8e6b60fdb22a27e2f51a6dd18bffcfb22706f9892d9a8d350deea54c0df67828
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require "json"
require "sorbet-runtime"
require "ts_pack_core_rb"
