# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7385ddff499bfd653e3dc1c08b8ada744dc611a13f7086ea02ee1a1dd1416b56
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

module TreeSitterLanguagePack
  ## The version string for this package.
  VERSION = "1.9.0.pre.rc.43"
end
