# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:088535ab50ea9825ca90396ea4a4916ea2ce45a729d1e5c7adba2f527eec1201
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
# frozen_string_literal: true

module TreeSitterLanguagePack
  VERSION = "1.9.0.pre.rc.14"
end
