# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fdaedbc30d45f59f128e477ac54794046794ad0608ac245915e5e9bd7fbac89f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

module TreeSitterLanguagePack
  ## The version string for this package.
  VERSION = "1.9.1"
end
