<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:46daf6e689455d9dd5087f81e0b8e490dfdb3b1b1a4f803121bec388fca89004
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Tree\Sitter\Language\Pack\TreeSitterLanguagePack;

/** E2e tests for category: parsing. */
final class ParsingTest extends TestCase
{
    /** Parse a Go function declaration and assert node type */
    public function test_parsing_go_function(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("package main\nfunc main() {}", ["language" => "go"]);
    }

    /** Parse an HTML element and assert node type */
    public function test_parsing_html_element(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("<div>hello</div>", ["language" => "html"]);
    }

    /** Parse a JavaScript class declaration. */
    public function test_parsing_javascript_class(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("class Foo { bar() {} }", ["language" => "javascript"]);
    }

    /** Parse a JavaScript variable declaration and assert node type */
    public function test_parsing_javascript_variable(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("const x = 1;", ["language" => "javascript"]);
    }

    /** Parse a Python function definition and assert node type */
    public function test_parsing_python_function(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("def hello(): pass", ["language" => "python"]);
    }

    /** Parse a Rust function definition and assert node type */
    public function test_parsing_rust_function(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("fn main() {}", ["language" => "rust"]);
    }

    /** Parse a Rust struct definition. */
    public function test_parsing_rust_struct(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("struct Point { x: f64, y: f64 }", ["language" => "rust"]);
    }
}
