<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d542b0dbe7460c7944b4e03195273c99f81b80d50357b898059868cd681e1c22
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Tree\Sitter\Language\Pack\TreeSitterLanguagePack;

/** E2e tests for category: smoke. */
final class SmokeTest extends TestCase
{
    /** Smoke test: load abl and parse a simple snippet */
    public function test_smoke_abl(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "abl"]);
    }

    /** Smoke test: load actionscript and parse a simple snippet */
    public function test_smoke_actionscript(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("var x:int = 1;", ["language" => "actionscript"]);
    }

    /** Smoke test: load ada and parse a simple snippet */
    public function test_smoke_ada(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("procedure Main is begin null; end Main;", ["language" => "ada"]);
    }

    /** Smoke test: load agda and parse a simple snippet */
    public function test_smoke_agda(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("module Main where", ["language" => "agda"]);
    }

    /** Smoke test: load al and parse a simple snippet */
    public function test_smoke_al(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "al"]);
    }

    /** Smoke test: load angular and parse a simple snippet */
    public function test_smoke_angular(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "angular"]);
    }

    /** Smoke test: load apex and parse a simple snippet */
    public function test_smoke_apex(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("public class Main {}", ["language" => "apex"]);
    }

    /** Smoke test: load arduino and parse a simple snippet */
    public function test_smoke_arduino(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("void setup() {}", ["language" => "arduino"]);
    }

    /** Smoke test: load asciidoc and parse a simple snippet */
    public function test_smoke_asciidoc(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("= Title\n\nParagraph.", ["language" => "asciidoc"]);
    }

    /** Smoke test: load asm and parse a simple snippet */
    public function test_smoke_asm(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("mov eax, 1", ["language" => "asm"]);
    }

    /** Smoke test: load astro and parse a simple snippet */
    public function test_smoke_astro(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("---\n---\n<p>hello</p>", ["language" => "astro"]);
    }

    /** Smoke test: load awk and parse a simple snippet */
    public function test_smoke_awk(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("BEGIN { print \"hello\" }", ["language" => "awk"]);
    }

    /** Smoke test: load bash and parse a simple snippet */
    public function test_smoke_bash(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("echo hello", ["language" => "bash"]);
    }

    /** Smoke test: load bass and parse a simple snippet */
    public function test_smoke_bass(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "bass"]);
    }

    /** Smoke test: load batch and parse a simple snippet */
    public function test_smoke_batch(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("@echo off\necho hello", ["language" => "batch"]);
    }

    /** Smoke test: load beancount and parse a simple snippet */
    public function test_smoke_beancount(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("2024-01-01 open Assets:Bank USD", ["language" => "beancount"]);
    }

    /** Smoke test: load bibtex and parse a simple snippet */
    public function test_smoke_bibtex(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("@article{key, title={A}}", ["language" => "bibtex"]);
    }

    /** Smoke test: load bicep and parse a simple snippet */
    public function test_smoke_bicep(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("param name string", ["language" => "bicep"]);
    }

    /** Smoke test: load bitbake and parse a simple snippet */
    public function test_smoke_bitbake(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("DESCRIPTION = \"hello\"", ["language" => "bitbake"]);
    }

    /** Smoke test: load blade and parse a simple snippet */
    public function test_smoke_blade(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "blade"]);
    }

    /** Smoke test: load brightscript and parse a simple snippet */
    public function test_smoke_brightscript(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "brightscript"]);
    }

    /** Smoke test: load bsl and parse a simple snippet */
    public function test_smoke_bsl(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("Procedure Main() EndProcedure", ["language" => "bsl"]);
    }

    /** Smoke test: load c and parse a simple snippet */
    public function test_smoke_c(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("int main() { return 0; }", ["language" => "c"]);
    }

    /** Smoke test: load c3 and parse a simple snippet */
    public function test_smoke_c3(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "c3"]);
    }

    /** Smoke test: load caddy and parse a simple snippet */
    public function test_smoke_caddy(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process(":8080 {\n\trespond \"Hello\"\n}", ["language" => "caddy"]);
    }

    /** Smoke test: load cairo and parse a simple snippet */
    public function test_smoke_cairo(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("fn main() {}", ["language" => "cairo"]);
    }

    /** Smoke test: load capnp and parse a simple snippet */
    public function test_smoke_capnp(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("@0xabcdef1234567890;", ["language" => "capnp"]);
    }

    /** Smoke test: load cedar and parse a simple snippet */
    public function test_smoke_cedar(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("permit(principal, action, resource);", ["language" => "cedar"]);
    }

    /** Smoke test: load cedarschema and parse a simple snippet */
    public function test_smoke_cedarschema(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("entity User;", ["language" => "cedarschema"]);
    }

    /** Smoke test: load cel and parse a simple snippet */
    public function test_smoke_cel(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "cel"]);
    }

    /** Smoke test: load cfml and parse a simple snippet */
    public function test_smoke_cfml(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "cfml"]);
    }

    /** Smoke test: load chatito and parse a simple snippet */
    public function test_smoke_chatito(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("%[greeting]\n    hello", ["language" => "chatito"]);
    }

    /** Smoke test: load chuck and parse a simple snippet */
    public function test_smoke_chuck(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "chuck"]);
    }

    /** Smoke test: load circom and parse a simple snippet */
    public function test_smoke_circom(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "circom"]);
    }

    /** Smoke test: load clarity and parse a simple snippet */
    public function test_smoke_clarity(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("(define-public (hello) (ok true))", ["language" => "clarity"]);
    }

    /** Smoke test: load clojure and parse a simple snippet */
    public function test_smoke_clojure(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("(def x 1)", ["language" => "clojure"]);
    }

    /** Smoke test: load cmake and parse a simple snippet */
    public function test_smoke_cmake(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("cmake_minimum_required(VERSION 3.0)", ["language" => "cmake"]);
    }

    /** Smoke test: load cobol and parse a simple snippet */
    public function test_smoke_cobol(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("       IDENTIFICATION DIVISION.\n       PROGRAM-ID. HELLO.", ["language" => "cobol"]);
    }

    /** Smoke test: load comment and parse a simple snippet */
    public function test_smoke_comment(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("TODO: fix this", ["language" => "comment"]);
    }

    /** Smoke test: load commonlisp and parse a simple snippet */
    public function test_smoke_commonlisp(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("(defun hello () (print \"hello\"))", ["language" => "commonlisp"]);
    }

    /** Smoke test: load cooklang and parse a simple snippet */
    public function test_smoke_cooklang(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "cooklang"]);
    }

    /** Smoke test: load corn and parse a simple snippet */
    public function test_smoke_corn(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("{ key = \"value\" }", ["language" => "corn"]);
    }

    /** Smoke test: load cpon and parse a simple snippet */
    public function test_smoke_cpon(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("{\"key\": 1}", ["language" => "cpon"]);
    }

    /** Smoke test: load cpp and parse a simple snippet */
    public function test_smoke_cpp(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("int main() { return 0; }", ["language" => "cpp"]);
    }

    /** Smoke test: load crystal and parse a simple snippet */
    public function test_smoke_crystal(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "crystal"]);
    }

    /** Smoke test: load csharp and parse a simple snippet */
    public function test_smoke_csharp(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("class Main {}", ["language" => "csharp"]);
    }

    /** Smoke test: load css and parse a simple snippet */
    public function test_smoke_css(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("body { color: red; }", ["language" => "css"]);
    }

    /** Smoke test: load cst and parse a simple snippet */
    public function test_smoke_cst(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "cst"]);
    }

    /** Smoke test: load csv and parse a simple snippet */
    public function test_smoke_csv(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("a,b,c\n1,2,3", ["language" => "csv"]);
    }

    /** Smoke test: load cuda and parse a simple snippet */
    public function test_smoke_cuda(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("__global__ void kernel() {}", ["language" => "cuda"]);
    }

    /** Smoke test: load cue and parse a simple snippet */
    public function test_smoke_cue(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "cue"]);
    }

    /** Smoke test: load cylc and parse a simple snippet */
    public function test_smoke_cylc(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "cylc"]);
    }

    /** Smoke test: load d and parse a simple snippet */
    public function test_smoke_d(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("void main() {}", ["language" => "d"]);
    }

    /** Smoke test: load dart and parse a simple snippet */
    public function test_smoke_dart(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("void main() {}", ["language" => "dart"]);
    }

    /** Smoke test: load desktop and parse a simple snippet */
    public function test_smoke_desktop(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "desktop"]);
    }

    /** Smoke test: load devicetree and parse a simple snippet */
    public function test_smoke_devicetree(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("/dts-v1/;\n/ { };", ["language" => "devicetree"]);
    }

    /** Smoke test: load dhall and parse a simple snippet */
    public function test_smoke_dhall(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "dhall"]);
    }

    /** Smoke test: load diff and parse a simple snippet */
    public function test_smoke_diff(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("--- a/file\n+++ b/file\n@@ -1 +1 @@\n-old\n+new", ["language" => "diff"]);
    }

    /** Smoke test: load djot and parse a simple snippet */
    public function test_smoke_djot(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "djot"]);
    }

    /** Smoke test: load dockerfile and parse a simple snippet */
    public function test_smoke_dockerfile(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("FROM alpine", ["language" => "dockerfile"]);
    }

    /** Smoke test: load dot and parse a simple snippet */
    public function test_smoke_dot(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("digraph G { A -> B; }", ["language" => "dot"]);
    }

    /** Smoke test: load doxygen and parse a simple snippet */
    public function test_smoke_doxygen(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("/** @brief A function */", ["language" => "doxygen"]);
    }

    /** Smoke test: load dtd and parse a simple snippet */
    public function test_smoke_dtd(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("<!ELEMENT note (body)>", ["language" => "dtd"]);
    }

    /** Smoke test: load earthfile and parse a simple snippet */
    public function test_smoke_earthfile(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "earthfile"]);
    }

    /** Smoke test: load ebnf and parse a simple snippet */
    public function test_smoke_ebnf(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "ebnf"]);
    }

    /** Smoke test: load editorconfig and parse a simple snippet */
    public function test_smoke_editorconfig(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "editorconfig"]);
    }

    /** Smoke test: load eds and parse a simple snippet */
    public function test_smoke_eds(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "eds"]);
    }

    /** Smoke test: load eex and parse a simple snippet */
    public function test_smoke_eex(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "eex"]);
    }

    /** Smoke test: load elisp and parse a simple snippet */
    public function test_smoke_elisp(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("(defun hello () (message \"hello\"))", ["language" => "elisp"]);
    }

    /** Smoke test: load elixir and parse a simple snippet */
    public function test_smoke_elixir(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("IO.puts(\"hello\")", ["language" => "elixir"]);
    }

    /** Smoke test: load elm and parse a simple snippet */
    public function test_smoke_elm(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("module Main exposing (..)", ["language" => "elm"]);
    }

    /** Smoke test: load elsa and parse a simple snippet */
    public function test_smoke_elsa(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "elsa"]);
    }

    /** Smoke test: load elvish and parse a simple snippet */
    public function test_smoke_elvish(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "elvish"]);
    }

    /** Smoke test: load embeddedtemplate and parse a simple snippet */
    public function test_smoke_embeddedtemplate(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("<%= value %>", ["language" => "embeddedtemplate"]);
    }

    /** Smoke test: load enforce and parse a simple snippet */
    public function test_smoke_enforce(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "enforce"]);
    }

    /** Smoke test: load erlang and parse a simple snippet */
    public function test_smoke_erlang(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("main() -> ok.", ["language" => "erlang"]);
    }

    /** Smoke test: load facility and parse a simple snippet */
    public function test_smoke_facility(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "facility"]);
    }

    /** Smoke test: load faust and parse a simple snippet */
    public function test_smoke_faust(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "faust"]);
    }

    /** Smoke test: load fennel and parse a simple snippet */
    public function test_smoke_fennel(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("(fn hello [] (print :hello))", ["language" => "fennel"]);
    }

    /** Smoke test: load fidl and parse a simple snippet */
    public function test_smoke_fidl(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "fidl"]);
    }

    /** Smoke test: load firrtl and parse a simple snippet */
    public function test_smoke_firrtl(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("circuit Main :", ["language" => "firrtl"]);
    }

    /** Smoke test: load fish and parse a simple snippet */
    public function test_smoke_fish(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("echo hello", ["language" => "fish"]);
    }

    /** Smoke test: load foam and parse a simple snippet */
    public function test_smoke_foam(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "foam"]);
    }

    /** Smoke test: load forth and parse a simple snippet */
    public function test_smoke_forth(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "forth"]);
    }

    /** Smoke test: load fortran and parse a simple snippet */
    public function test_smoke_fortran(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("program main\nend program main", ["language" => "fortran"]);
    }

    /** Smoke test: load fsharp and parse a simple snippet */
    public function test_smoke_fsharp(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("let x = 1", ["language" => "fsharp"]);
    }

    /** Smoke test: load fsharp_signature and parse a simple snippet */
    public function test_smoke_fsharp_signature(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("val x: int", ["language" => "fsharp_signature"]);
    }

    /** Smoke test: load func and parse a simple snippet */
    public function test_smoke_func(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("() recv_internal() {}", ["language" => "func"]);
    }

    /** Smoke test: load gap and parse a simple snippet */
    public function test_smoke_gap(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "gap"]);
    }

    /** Smoke test: load gdscript and parse a simple snippet */
    public function test_smoke_gdscript(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("extends Node\nfunc _ready():\n\tpass", ["language" => "gdscript"]);
    }

    /** Smoke test: load gdshader and parse a simple snippet */
    public function test_smoke_gdshader(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "gdshader"]);
    }

    /** Smoke test: load git_config and parse a simple snippet */
    public function test_smoke_git_config(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "git_config"]);
    }

    /** Smoke test: load git_rebase and parse a simple snippet */
    public function test_smoke_git_rebase(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "git_rebase"]);
    }

    /** Smoke test: load gitattributes and parse a simple snippet */
    public function test_smoke_gitattributes(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("*.txt text", ["language" => "gitattributes"]);
    }

    /** Smoke test: load gitcommit and parse a simple snippet */
    public function test_smoke_gitcommit(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("feat: add feature\n\nBody text", ["language" => "gitcommit"]);
    }

    /** Smoke test: load gitignore and parse a simple snippet */
    public function test_smoke_gitignore(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("*.o\n*.log", ["language" => "gitignore"]);
    }

    /** Smoke test: load gleam and parse a simple snippet */
    public function test_smoke_gleam(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("pub fn main() { }", ["language" => "gleam"]);
    }

    /** Smoke test: load glimmer and parse a simple snippet */
    public function test_smoke_glimmer(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "glimmer"]);
    }

    /** Smoke test: load glsl and parse a simple snippet */
    public function test_smoke_glsl(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("void main() { gl_Position = vec4(0.0); }", ["language" => "glsl"]);
    }

    /** Smoke test: load gn and parse a simple snippet */
    public function test_smoke_gn(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("group(\"hello\") {}", ["language" => "gn"]);
    }

    /** Smoke test: load gnuplot and parse a simple snippet */
    public function test_smoke_gnuplot(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "gnuplot"]);
    }

    /** Smoke test: load go and parse a simple snippet */
    public function test_smoke_go(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("package main", ["language" => "go"]);
    }

    /** Smoke test: load godot_resource and parse a simple snippet */
    public function test_smoke_godot_resource(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "godot_resource"]);
    }

    /** Smoke test: load gomod and parse a simple snippet */
    public function test_smoke_gomod(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("module example.com/hello\n\ngo 1.21", ["language" => "gomod"]);
    }

    /** Smoke test: load gosum and parse a simple snippet */
    public function test_smoke_gosum(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("example.com/pkg v1.0.0 h1:abc=", ["language" => "gosum"]);
    }

    /** Smoke test: load gotmpl and parse a simple snippet */
    public function test_smoke_gotmpl(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "gotmpl"]);
    }

    /** Smoke test: load gowork and parse a simple snippet */
    public function test_smoke_gowork(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "gowork"]);
    }

    /** Smoke test: load gpg and parse a simple snippet */
    public function test_smoke_gpg(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "gpg"]);
    }

    /** Smoke test: load graphql and parse a simple snippet */
    public function test_smoke_graphql(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("type Query { hello: String }", ["language" => "graphql"]);
    }

    /** Smoke test: load gren and parse a simple snippet */
    public function test_smoke_gren(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("module Main exposing (..)", ["language" => "gren"]);
    }

    /** Smoke test: load groovy and parse a simple snippet */
    public function test_smoke_groovy(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("def x = 1", ["language" => "groovy"]);
    }

    /** Smoke test: load gstlaunch and parse a simple snippet */
    public function test_smoke_gstlaunch(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("fakesrc ! fakesink", ["language" => "gstlaunch"]);
    }

    /** Smoke test: load hack and parse a simple snippet */
    public function test_smoke_hack(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("<?hh\nfunction main(): void {}", ["language" => "hack"]);
    }

    /** Smoke test: load hare and parse a simple snippet */
    public function test_smoke_hare(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("export fn main() void = void;", ["language" => "hare"]);
    }

    /** Smoke test: load haskell and parse a simple snippet */
    public function test_smoke_haskell(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("main = putStrLn \"hello\"", ["language" => "haskell"]);
    }

    /** Smoke test: load haxe and parse a simple snippet */
    public function test_smoke_haxe(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("class Main { static function main() {} }", ["language" => "haxe"]);
    }

    /** Smoke test: load hcl and parse a simple snippet */
    public function test_smoke_hcl(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("variable \"name\" { type = string }", ["language" => "hcl"]);
    }

    /** Smoke test: load heex and parse a simple snippet */
    public function test_smoke_heex(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("<%= @greeting %>", ["language" => "heex"]);
    }

    /** Smoke test: load hjson and parse a simple snippet */
    public function test_smoke_hjson(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "hjson"]);
    }

    /** Smoke test: load hlsl and parse a simple snippet */
    public function test_smoke_hlsl(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("float4 main() : SV_Target { return 0; }", ["language" => "hlsl"]);
    }

    /** Smoke test: load hocon and parse a simple snippet */
    public function test_smoke_hocon(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "hocon"]);
    }

    /** Smoke test: load hoon and parse a simple snippet */
    public function test_smoke_hoon(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "hoon"]);
    }

    /** Smoke test: load html and parse a simple snippet */
    public function test_smoke_html(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("<p>hello</p>", ["language" => "html"]);
    }

    /** Smoke test: load htmldjango and parse a simple snippet */
    public function test_smoke_htmldjango(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "htmldjango"]);
    }

    /** Smoke test: load http and parse a simple snippet */
    public function test_smoke_http(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "http"]);
    }

    /** Smoke test: load hurl and parse a simple snippet */
    public function test_smoke_hurl(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "hurl"]);
    }

    /** Smoke test: load hyprlang and parse a simple snippet */
    public function test_smoke_hyprlang(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("general { border_size = 1 }", ["language" => "hyprlang"]);
    }

    /** Smoke test: load idris and parse a simple snippet */
    public function test_smoke_idris(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("module Main", ["language" => "idris"]);
    }

    /** Smoke test: load ini and parse a simple snippet */
    public function test_smoke_ini(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("[section]\nkey = value", ["language" => "ini"]);
    }

    /** Smoke test: load ispc and parse a simple snippet */
    public function test_smoke_ispc(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("export void main() {}", ["language" => "ispc"]);
    }

    /** Smoke test: load jai and parse a simple snippet */
    public function test_smoke_jai(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "jai"]);
    }

    /** Smoke test: load janet and parse a simple snippet */
    public function test_smoke_janet(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("(print \"hello\")", ["language" => "janet"]);
    }

    /** Smoke test: load java and parse a simple snippet */
    public function test_smoke_java(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("class Main {}", ["language" => "java"]);
    }

    /** Smoke test: load javadoc and parse a simple snippet */
    public function test_smoke_javadoc(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "javadoc"]);
    }

    /** Smoke test: load javascript and parse a simple snippet */
    public function test_smoke_javascript(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("console.log('hello');", ["language" => "javascript"]);
    }

    /** Smoke test: load jinja2 and parse a simple snippet */
    public function test_smoke_jinja2(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("{{ variable }}", ["language" => "jinja2"]);
    }

    /** Smoke test: load jq and parse a simple snippet */
    public function test_smoke_jq(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process(".[] | select(.key)", ["language" => "jq"]);
    }

    /** Smoke test: load jsdoc and parse a simple snippet */
    public function test_smoke_jsdoc(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("/** @param {string} name */", ["language" => "jsdoc"]);
    }

    /** Smoke test: load json and parse a simple snippet */
    public function test_smoke_json(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("{\"key\": \"value\"}", ["language" => "json"]);
    }

    /** Smoke test: load json5 and parse a simple snippet */
    public function test_smoke_json5(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "json5"]);
    }

    /** Smoke test: load jsonnet and parse a simple snippet */
    public function test_smoke_jsonnet(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("{ key: 'value' }", ["language" => "jsonnet"]);
    }

    /** Smoke test: load julia and parse a simple snippet */
    public function test_smoke_julia(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("function main() end", ["language" => "julia"]);
    }

    /** Smoke test: load just and parse a simple snippet */
    public function test_smoke_just(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "just"]);
    }

    /** Smoke test: load kcl and parse a simple snippet */
    public function test_smoke_kcl(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "kcl"]);
    }

    /** Smoke test: load kconfig and parse a simple snippet */
    public function test_smoke_kconfig(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("config FOO\n\tbool \"Enable foo\"", ["language" => "kconfig"]);
    }

    /** Smoke test: load kdl and parse a simple snippet */
    public function test_smoke_kdl(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("node \"value\"", ["language" => "kdl"]);
    }

    /** Smoke test: load kotlin and parse a simple snippet */
    public function test_smoke_kotlin(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("fun main() {}", ["language" => "kotlin"]);
    }

    /** Smoke test: load latex and parse a simple snippet */
    public function test_smoke_latex(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("\\documentclass{article}\n\\begin{document}\nHello\n\\end{document}", ["language" => "latex"]);
    }

    /** Smoke test: load lean and parse a simple snippet */
    public function test_smoke_lean(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("def main : IO Unit := pure ()", ["language" => "lean"]);
    }

    /** Smoke test: load ledger and parse a simple snippet */
    public function test_smoke_ledger(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "ledger"]);
    }

    /** Smoke test: load less and parse a simple snippet */
    public function test_smoke_less(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "less"]);
    }

    /** Smoke test: load linkerscript and parse a simple snippet */
    public function test_smoke_linkerscript(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("SECTIONS { .text : { *(.text) } }", ["language" => "linkerscript"]);
    }

    /** Smoke test: load liquid and parse a simple snippet */
    public function test_smoke_liquid(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "liquid"]);
    }

    /** Smoke test: load llvm and parse a simple snippet */
    public function test_smoke_llvm(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("define i32 @main() { ret i32 0 }", ["language" => "llvm"]);
    }

    /** Smoke test: load lua and parse a simple snippet */
    public function test_smoke_lua(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("print('hello')", ["language" => "lua"]);
    }

    /** Smoke test: load luadoc and parse a simple snippet */
    public function test_smoke_luadoc(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("---@param name string", ["language" => "luadoc"]);
    }

    /** Smoke test: load luap and parse a simple snippet */
    public function test_smoke_luap(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("[a-z]+", ["language" => "luap"]);
    }

    /** Smoke test: load luau and parse a simple snippet */
    public function test_smoke_luau(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("local x: number = 1", ["language" => "luau"]);
    }

    /** Smoke test: load magik and parse a simple snippet */
    public function test_smoke_magik(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("_method object.hello\n_endmethod", ["language" => "magik"]);
    }

    /** Smoke test: load make and parse a simple snippet */
    public function test_smoke_make(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("all:\n\techo hello", ["language" => "make"]);
    }

    /** Smoke test: load markdown and parse a simple snippet */
    public function test_smoke_markdown(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("# Hello\n\nWorld", ["language" => "markdown"]);
    }

    /** Smoke test: load markdown_inline and parse a simple snippet */
    public function test_smoke_markdown_inline(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("**bold** and *italic*", ["language" => "markdown_inline"]);
    }

    /** Smoke test: load matlab and parse a simple snippet */
    public function test_smoke_matlab(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("function y = hello(x)\ny = x;\nend", ["language" => "matlab"]);
    }

    /** Smoke test: load mermaid and parse a simple snippet */
    public function test_smoke_mermaid(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("graph TD\nA --> B", ["language" => "mermaid"]);
    }

    /** Smoke test: load meson and parse a simple snippet */
    public function test_smoke_meson(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("project('hello', 'c')", ["language" => "meson"]);
    }

    /** Smoke test: load mlir and parse a simple snippet */
    public function test_smoke_mlir(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "mlir"]);
    }

    /** Smoke test: load mojo and parse a simple snippet */
    public function test_smoke_mojo(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "mojo"]);
    }

    /** Smoke test: load move and parse a simple snippet */
    public function test_smoke_move(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "move"]);
    }

    /** Smoke test: load nasm and parse a simple snippet */
    public function test_smoke_nasm(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "nasm"]);
    }

    /** Smoke test: load netlinx and parse a simple snippet */
    public function test_smoke_netlinx(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("PROGRAM_NAME='hello'", ["language" => "netlinx"]);
    }

    /** Smoke test: load nginx and parse a simple snippet */
    public function test_smoke_nginx(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "nginx"]);
    }

    /** Smoke test: load nickel and parse a simple snippet */
    public function test_smoke_nickel(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "nickel"]);
    }

    /** Smoke test: load nim and parse a simple snippet */
    public function test_smoke_nim(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("echo \"hello\"", ["language" => "nim"]);
    }

    /** Smoke test: load ninja and parse a simple snippet */
    public function test_smoke_ninja(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("rule cc\n  command = cc \$in -o \$out", ["language" => "ninja"]);
    }

    /** Smoke test: load nix and parse a simple snippet */
    public function test_smoke_nix(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("{ pkgs ? import <nixpkgs> {} }: pkgs.hello", ["language" => "nix"]);
    }

    /** Smoke test: load norg and parse a simple snippet */
    public function test_smoke_norg(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "norg"]);
    }

    /** Smoke test: load norg_meta and parse a simple snippet */
    public function test_smoke_norg_meta(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "norg_meta"]);
    }

    /** Smoke test: load nqc and parse a simple snippet */
    public function test_smoke_nqc(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("task main() {}", ["language" => "nqc"]);
    }

    /** Smoke test: load nushell and parse a simple snippet */
    public function test_smoke_nushell(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "nushell"]);
    }

    /** Smoke test: load objc and parse a simple snippet */
    public function test_smoke_objc(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("@interface Main @end", ["language" => "objc"]);
    }

    /** Smoke test: load ocaml and parse a simple snippet */
    public function test_smoke_ocaml(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("let () = print_endline \"hello\"", ["language" => "ocaml"]);
    }

    /** Smoke test: load ocaml_interface and parse a simple snippet */
    public function test_smoke_ocaml_interface(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("val x : int", ["language" => "ocaml_interface"]);
    }

    /** Smoke test: load ocamllex and parse a simple snippet */
    public function test_smoke_ocamllex(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "ocamllex"]);
    }

    /** Smoke test: load odin and parse a simple snippet */
    public function test_smoke_odin(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("package main", ["language" => "odin"]);
    }

    /** Smoke test: load openscad and parse a simple snippet */
    public function test_smoke_openscad(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "openscad"]);
    }

    /** Smoke test: load org and parse a simple snippet */
    public function test_smoke_org(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("* Hello\nWorld", ["language" => "org"]);
    }

    /** Smoke test: load pascal and parse a simple snippet */
    public function test_smoke_pascal(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("program Hello; begin end.", ["language" => "pascal"]);
    }

    /** Smoke test: load pem and parse a simple snippet */
    public function test_smoke_pem(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("-----BEGIN CERTIFICATE-----\ndata\n-----END CERTIFICATE-----", ["language" => "pem"]);
    }

    /** Smoke test: load perl and parse a simple snippet */
    public function test_smoke_perl(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("print 'hello';", ["language" => "perl"]);
    }

    /** Smoke test: load pgn and parse a simple snippet */
    public function test_smoke_pgn(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("1. e4 e5 *", ["language" => "pgn"]);
    }

    /** Smoke test: load php and parse a simple snippet */
    public function test_smoke_php(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("<?php echo 'hello'; ?>", ["language" => "php"]);
    }

    /** Smoke test: load phpdoc and parse a simple snippet */
    public function test_smoke_phpdoc(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "phpdoc"]);
    }

    /** Smoke test: load pkl and parse a simple snippet */
    public function test_smoke_pkl(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("name = \"hello\"", ["language" => "pkl"]);
    }

    /** Smoke test: load po and parse a simple snippet */
    public function test_smoke_po(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("msgid \"hello\"\nmsgstr \"world\"", ["language" => "po"]);
    }

    /** Smoke test: load poe_filter and parse a simple snippet */
    public function test_smoke_poe_filter(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "poe_filter"]);
    }

    /** Smoke test: load pony and parse a simple snippet */
    public function test_smoke_pony(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("actor Main\n  new create(env: Env) => None", ["language" => "pony"]);
    }

    /** Smoke test: load postscript and parse a simple snippet */
    public function test_smoke_postscript(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("/hello { (Hello) show } def", ["language" => "postscript"]);
    }

    /** Smoke test: load powershell and parse a simple snippet */
    public function test_smoke_powershell(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("Write-Host 'hello'", ["language" => "powershell"]);
    }

    /** Smoke test: load printf and parse a simple snippet */
    public function test_smoke_printf(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("%d %s", ["language" => "printf"]);
    }

    /** Smoke test: load prisma and parse a simple snippet */
    public function test_smoke_prisma(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("model User { id Int @id }", ["language" => "prisma"]);
    }

    /** Smoke test: load prolog and parse a simple snippet */
    public function test_smoke_prolog(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("hello :- write('hello'), nl.", ["language" => "prolog"]);
    }

    /** Smoke test: load promql and parse a simple snippet */
    public function test_smoke_promql(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "promql"]);
    }

    /** Smoke test: load properties and parse a simple snippet */
    public function test_smoke_properties(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("key=value", ["language" => "properties"]);
    }

    /** Smoke test: load proto and parse a simple snippet */
    public function test_smoke_proto(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("syntax = \"proto3\";", ["language" => "proto"]);
    }

    /** Smoke test: load prql and parse a simple snippet */
    public function test_smoke_prql(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "prql"]);
    }

    /** Smoke test: load psv and parse a simple snippet */
    public function test_smoke_psv(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("a|b|c\n1|2|3", ["language" => "psv"]);
    }

    /** Smoke test: load pug and parse a simple snippet */
    public function test_smoke_pug(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "pug"]);
    }

    /** Smoke test: load puppet and parse a simple snippet */
    public function test_smoke_puppet(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("notify { 'hello': }", ["language" => "puppet"]);
    }

    /** Smoke test: load purescript and parse a simple snippet */
    public function test_smoke_purescript(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("module Main where", ["language" => "purescript"]);
    }

    /** Smoke test: load pymanifest and parse a simple snippet */
    public function test_smoke_pymanifest(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("include *.txt", ["language" => "pymanifest"]);
    }

    /** Smoke test: load python and parse a simple snippet */
    public function test_smoke_python(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("print('hello')", ["language" => "python"]);
    }

    /** Smoke test: load ql and parse a simple snippet */
    public function test_smoke_ql(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "ql"]);
    }

    /** Smoke test: load qmldir and parse a simple snippet */
    public function test_smoke_qmldir(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("module Example", ["language" => "qmldir"]);
    }

    /** Smoke test: load qmljs and parse a simple snippet */
    public function test_smoke_qmljs(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("import QtQuick 2.0\nItem {}", ["language" => "qmljs"]);
    }

    /** Smoke test: load query and parse a simple snippet */
    public function test_smoke_query(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("(identifier) @name", ["language" => "query"]);
    }

    /** Smoke test: load r and parse a simple snippet */
    public function test_smoke_r(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("print('hello')", ["language" => "r"]);
    }

    /** Smoke test: load racket and parse a simple snippet */
    public function test_smoke_racket(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("#lang racket\n(define x 1)", ["language" => "racket"]);
    }

    /** Smoke test: load rasi and parse a simple snippet */
    public function test_smoke_rasi(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "rasi"]);
    }

    /** Smoke test: load razor and parse a simple snippet */
    public function test_smoke_razor(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "razor"]);
    }

    /** Smoke test: load rbs and parse a simple snippet */
    public function test_smoke_rbs(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "rbs"]);
    }

    /** Smoke test: load re2c and parse a simple snippet */
    public function test_smoke_re2c(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("/*!re2c\n  [a-z]+ { return; }\n*/", ["language" => "re2c"]);
    }

    /** Smoke test: load readline and parse a simple snippet */
    public function test_smoke_readline(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("set editing-mode vi", ["language" => "readline"]);
    }

    /** Smoke test: load regex and parse a simple snippet */
    public function test_smoke_regex(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "regex"]);
    }

    /** Smoke test: load rego and parse a simple snippet */
    public function test_smoke_rego(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("package main\ndefault allow = false", ["language" => "rego"]);
    }

    /** Smoke test: load requirements and parse a simple snippet */
    public function test_smoke_requirements(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("flask>=2.0", ["language" => "requirements"]);
    }

    /** Smoke test: load rescript and parse a simple snippet */
    public function test_smoke_rescript(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("let x = 1", ["language" => "rescript"]);
    }

    /** Smoke test: load robot and parse a simple snippet */
    public function test_smoke_robot(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "robot"]);
    }

    /** Smoke test: load roc and parse a simple snippet */
    public function test_smoke_roc(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "roc"]);
    }

    /** Smoke test: load ron and parse a simple snippet */
    public function test_smoke_ron(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("(key: \"value\")", ["language" => "ron"]);
    }

    /** Smoke test: load rst and parse a simple snippet */
    public function test_smoke_rst(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("Hello\n=====\n\nWorld", ["language" => "rst"]);
    }

    /** Smoke test: load rtf and parse a simple snippet */
    public function test_smoke_rtf(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("{\\rtf1 hello}", ["language" => "rtf"]);
    }

    /** Smoke test: load ruby and parse a simple snippet */
    public function test_smoke_ruby(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("puts 'hello'", ["language" => "ruby"]);
    }

    /** Smoke test: load rust and parse a simple snippet */
    public function test_smoke_rust(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("fn main() {}", ["language" => "rust"]);
    }

    /** Smoke test: load scala and parse a simple snippet */
    public function test_smoke_scala(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("object Main", ["language" => "scala"]);
    }

    /** Smoke test: load scheme and parse a simple snippet */
    public function test_smoke_scheme(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("(define x 1)", ["language" => "scheme"]);
    }

    /** Smoke test: load scss and parse a simple snippet */
    public function test_smoke_scss(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("\$color: red;\nbody { color: \$color; }", ["language" => "scss"]);
    }

    /** Smoke test: load slang and parse a simple snippet */
    public function test_smoke_slang(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "slang"]);
    }

    /** Smoke test: load smali and parse a simple snippet */
    public function test_smoke_smali(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process(".class public LMain;\n.super Ljava/lang/Object;", ["language" => "smali"]);
    }

    /** Smoke test: load smalltalk and parse a simple snippet */
    public function test_smoke_smalltalk(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "smalltalk"]);
    }

    /** Smoke test: load smithy and parse a simple snippet */
    public function test_smoke_smithy(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("namespace example\nstring MyString", ["language" => "smithy"]);
    }

    /** Smoke test: load sml and parse a simple snippet */
    public function test_smoke_sml(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "sml"]);
    }

    /** Smoke test: load snakemake and parse a simple snippet */
    public function test_smoke_snakemake(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "snakemake"]);
    }

    /** Smoke test: load solidity and parse a simple snippet */
    public function test_smoke_solidity(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("pragma solidity ^0.8.0;\ncontract Main {}", ["language" => "solidity"]);
    }

    /** Smoke test: load souffle and parse a simple snippet */
    public function test_smoke_souffle(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "souffle"]);
    }

    /** Smoke test: load sourcepawn and parse a simple snippet */
    public function test_smoke_sourcepawn(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "sourcepawn"]);
    }

    /** Smoke test: load sparql and parse a simple snippet */
    public function test_smoke_sparql(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("SELECT ?s WHERE { ?s ?p ?o }", ["language" => "sparql"]);
    }

    /** Smoke test: load sql and parse a simple snippet */
    public function test_smoke_sql(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("SELECT 1;", ["language" => "sql"]);
    }

    /** Smoke test: load sql_bigquery and parse a simple snippet */
    public function test_smoke_sql_bigquery(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "sql_bigquery"]);
    }

    /** Smoke test: load squirrel and parse a simple snippet */
    public function test_smoke_squirrel(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("function main() {}", ["language" => "squirrel"]);
    }

    /** Smoke test: load ssh_config and parse a simple snippet */
    public function test_smoke_ssh_config(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("Host example\n  HostName example.com", ["language" => "ssh_config"]);
    }

    /** Smoke test: load stan and parse a simple snippet */
    public function test_smoke_stan(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "stan"]);
    }

    /** Smoke test: load starlark and parse a simple snippet */
    public function test_smoke_starlark(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("def hello(): pass", ["language" => "starlark"]);
    }

    /** Smoke test: load superhtml and parse a simple snippet */
    public function test_smoke_superhtml(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "superhtml"]);
    }

    /** Smoke test: load svelte and parse a simple snippet */
    public function test_smoke_svelte(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("<script>let x = 1;</script>", ["language" => "svelte"]);
    }

    /** Smoke test: load sway and parse a simple snippet */
    public function test_smoke_sway(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "sway"]);
    }

    /** Smoke test: load swift and parse a simple snippet */
    public function test_smoke_swift(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("print(\"hello\")", ["language" => "swift"]);
    }

    /** Smoke test: load systemverilog and parse a simple snippet */
    public function test_smoke_systemverilog(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "systemverilog"]);
    }

    /** Smoke test: load tablegen and parse a simple snippet */
    public function test_smoke_tablegen(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("def Hello : Base {}", ["language" => "tablegen"]);
    }

    /** Smoke test: load tact and parse a simple snippet */
    public function test_smoke_tact(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "tact"]);
    }

    /** Smoke test: load tcl and parse a simple snippet */
    public function test_smoke_tcl(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("puts hello", ["language" => "tcl"]);
    }

    /** Smoke test: load teal and parse a simple snippet */
    public function test_smoke_teal(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "teal"]);
    }

    /** Smoke test: load templ and parse a simple snippet */
    public function test_smoke_templ(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "templ"]);
    }

    /** Smoke test: load tera and parse a simple snippet */
    public function test_smoke_tera(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "tera"]);
    }

    /** Smoke test: load terraform and parse a simple snippet */
    public function test_smoke_terraform(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("resource \"null_resource\" \"main\" {}", ["language" => "terraform"]);
    }

    /** Smoke test: load test and parse a simple snippet */
    public function test_smoke_test(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("===========\nTest\n===========\n---\n(node)", ["language" => "test"]);
    }

    /** Smoke test: load textproto and parse a simple snippet */
    public function test_smoke_textproto(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("key: \"value\"", ["language" => "textproto"]);
    }

    /** Smoke test: load thrift and parse a simple snippet */
    public function test_smoke_thrift(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("service HelloService {}", ["language" => "thrift"]);
    }

    /** Smoke test: load tlaplus and parse a simple snippet */
    public function test_smoke_tlaplus(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("---- MODULE Main ----\n====", ["language" => "tlaplus"]);
    }

    /** Smoke test: load tmux and parse a simple snippet */
    public function test_smoke_tmux(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "tmux"]);
    }

    /** Smoke test: load todotxt and parse a simple snippet */
    public function test_smoke_todotxt(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "todotxt"]);
    }

    /** Smoke test: load toml and parse a simple snippet */
    public function test_smoke_toml(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("key = \"value\"", ["language" => "toml"]);
    }

    /** Smoke test: load tsv and parse a simple snippet */
    public function test_smoke_tsv(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("a\tb\tc\n1\t2\t3", ["language" => "tsv"]);
    }

    /** Smoke test: load tsx and parse a simple snippet */
    public function test_smoke_tsx(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("const App = () => <div />;", ["language" => "tsx"]);
    }

    /** Smoke test: load turtle and parse a simple snippet */
    public function test_smoke_turtle(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "turtle"]);
    }

    /** Smoke test: load twig and parse a simple snippet */
    public function test_smoke_twig(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("{{ variable }}", ["language" => "twig"]);
    }

    /** Smoke test: load typescript and parse a simple snippet */
    public function test_smoke_typescript(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("const x: number = 42;", ["language" => "typescript"]);
    }

    /** Smoke test: load typespec and parse a simple snippet */
    public function test_smoke_typespec(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "typespec"]);
    }

    /** Smoke test: load typoscript and parse a simple snippet */
    public function test_smoke_typoscript(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "typoscript"]);
    }

    /** Smoke test: load typst and parse a simple snippet */
    public function test_smoke_typst(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("#let x = 1", ["language" => "typst"]);
    }

    /** Smoke test: load udev and parse a simple snippet */
    public function test_smoke_udev(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("ACTION==\"add\", KERNEL==\"sd*\"", ["language" => "udev"]);
    }

    /** Smoke test: load ungrammar and parse a simple snippet */
    public function test_smoke_ungrammar(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("Root = Item*\nItem = 'token'", ["language" => "ungrammar"]);
    }

    /** Smoke test: load uxntal and parse a simple snippet */
    public function test_smoke_uxntal(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("|0100 LIT 01", ["language" => "uxntal"]);
    }

    /** Smoke test: load v and parse a simple snippet */
    public function test_smoke_v(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("fn main() {}", ["language" => "v"]);
    }

    /** Smoke test: load vb and parse a simple snippet */
    public function test_smoke_vb(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("Module Main\nEnd Module", ["language" => "vb"]);
    }

    /** Smoke test: load verilog and parse a simple snippet */
    public function test_smoke_verilog(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("module main; endmodule", ["language" => "verilog"]);
    }

    /** Smoke test: load vhdl and parse a simple snippet */
    public function test_smoke_vhdl(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("entity main is end main;", ["language" => "vhdl"]);
    }

    /** Smoke test: load vhs and parse a simple snippet */
    public function test_smoke_vhs(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "vhs"]);
    }

    /** Smoke test: load vim and parse a simple snippet */
    public function test_smoke_vim(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("echo 'hello'", ["language" => "vim"]);
    }

    /** Smoke test: load vimdoc and parse a simple snippet */
    public function test_smoke_vimdoc(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "vimdoc"]);
    }

    /** Smoke test: load vrl and parse a simple snippet */
    public function test_smoke_vrl(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "vrl"]);
    }

    /** Smoke test: load vue and parse a simple snippet */
    public function test_smoke_vue(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("<template><div>hello</div></template>", ["language" => "vue"]);
    }

    /** Smoke test: load wast and parse a simple snippet */
    public function test_smoke_wast(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("(module)", ["language" => "wast"]);
    }

    /** Smoke test: load wat and parse a simple snippet */
    public function test_smoke_wat(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("(module)", ["language" => "wat"]);
    }

    /** Smoke test: load wgsl and parse a simple snippet */
    public function test_smoke_wgsl(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("@vertex fn main() -> @builtin(position) vec4f { return vec4f(); }", ["language" => "wgsl"]);
    }

    /** Smoke test: load wgsl_bevy and parse a simple snippet */
    public function test_smoke_wgsl_bevy(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "wgsl_bevy"]);
    }

    /** Smoke test: load wit and parse a simple snippet */
    public function test_smoke_wit(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("package example:pkg;", ["language" => "wit"]);
    }

    /** Smoke test: load wolfram and parse a simple snippet */
    public function test_smoke_wolfram(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "wolfram"]);
    }

    /** Smoke test: load x86asm and parse a simple snippet */
    public function test_smoke_x86asm(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "x86asm"]);
    }

    /** Smoke test: load xcompose and parse a simple snippet */
    public function test_smoke_xcompose(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("<Multi_key> <a> : \"a\"", ["language" => "xcompose"]);
    }

    /** Smoke test: load xml and parse a simple snippet */
    public function test_smoke_xml(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("<?xml version=\"1.0\"?>\n<root>hello</root>", ["language" => "xml"]);
    }

    /** Smoke test: load yaml and parse a simple snippet */
    public function test_smoke_yaml(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("key: value", ["language" => "yaml"]);
    }

    /** Smoke test: load yuck and parse a simple snippet */
    public function test_smoke_yuck(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("(defwidget main [] (label :text \"hi\"))", ["language" => "yuck"]);
    }

    /** Smoke test: load zig and parse a simple snippet */
    public function test_smoke_zig(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("pub fn main() void {}", ["language" => "zig"]);
    }

    /** Smoke test: load ziggy and parse a simple snippet */
    public function test_smoke_ziggy(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "ziggy"]);
    }

    /** Smoke test: load ziggy_schema and parse a simple snippet */
    public function test_smoke_ziggy_schema(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("x", ["language" => "ziggy_schema"]);
    }

    /** Smoke test: load zsh and parse a simple snippet */
    public function test_smoke_zsh(): void
    {
        $this->expectNotToPerformAssertions();
        $result = TreeSitterLanguagePack::process("echo hello", ["language" => "zsh"]);
    }
}
