/*
 * This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:599153cd7400a8dded2cec1fd92620f96a34f53cc27330ce810acbd9f30c29a3
 * To regenerate: alef generate
 * To verify freshness: alef verify --exit-code
 * Issues & docs: https://github.com/kreuzberg-dev/alef
 */
/* E2e tests for category: parsing */

#include <assert.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include "tree_sitter_language_pack.h"
#include "test_runner.h"

void test_parsing_go_function(void) {
    /* Parse a Go function declaration and assert node type */
    TS_PACKConversionOptions* options_handle = ts_pack_conversion_options_from_json("{\"language\":\"go\"}");
    TS_PACKProcess* result = process("package main\nfunc main() {}", options_handle);
    assert(result != NULL && "expected call to succeed");
    ts_pack_conversion_options_free(options_handle);
    ts_pack_process_free(result);
}

void test_parsing_html_element(void) {
    /* Parse an HTML element and assert node type */
    TS_PACKConversionOptions* options_handle = ts_pack_conversion_options_from_json("{\"language\":\"html\"}");
    TS_PACKProcess* result = process("<div>hello</div>", options_handle);
    assert(result != NULL && "expected call to succeed");
    ts_pack_conversion_options_free(options_handle);
    ts_pack_process_free(result);
}

void test_parsing_javascript_class(void) {
    /* Parse a JavaScript class declaration. */
    TS_PACKConversionOptions* options_handle = ts_pack_conversion_options_from_json("{\"language\":\"javascript\"}");
    TS_PACKProcess* result = process("class Foo { bar() {} }", options_handle);
    assert(result != NULL && "expected call to succeed");
    ts_pack_conversion_options_free(options_handle);
    ts_pack_process_free(result);
}

void test_parsing_javascript_variable(void) {
    /* Parse a JavaScript variable declaration and assert node type */
    TS_PACKConversionOptions* options_handle = ts_pack_conversion_options_from_json("{\"language\":\"javascript\"}");
    TS_PACKProcess* result = process("const x = 1;", options_handle);
    assert(result != NULL && "expected call to succeed");
    ts_pack_conversion_options_free(options_handle);
    ts_pack_process_free(result);
}

void test_parsing_python_function(void) {
    /* Parse a Python function definition and assert node type */
    TS_PACKConversionOptions* options_handle = ts_pack_conversion_options_from_json("{\"language\":\"python\"}");
    TS_PACKProcess* result = process("def hello(): pass", options_handle);
    assert(result != NULL && "expected call to succeed");
    ts_pack_conversion_options_free(options_handle);
    ts_pack_process_free(result);
}

void test_parsing_rust_function(void) {
    /* Parse a Rust function definition and assert node type */
    TS_PACKConversionOptions* options_handle = ts_pack_conversion_options_from_json("{\"language\":\"rust\"}");
    TS_PACKProcess* result = process("fn main() {}", options_handle);
    assert(result != NULL && "expected call to succeed");
    ts_pack_conversion_options_free(options_handle);
    ts_pack_process_free(result);
}

void test_parsing_rust_struct(void) {
    /* Parse a Rust struct definition. */
    TS_PACKConversionOptions* options_handle = ts_pack_conversion_options_from_json("{\"language\":\"rust\"}");
    TS_PACKProcess* result = process("struct Point { x: f64, y: f64 }", options_handle);
    assert(result != NULL && "expected call to succeed");
    ts_pack_conversion_options_free(options_handle);
    ts_pack_process_free(result);
}
