// DO NOT EDIT - auto-generated by alef
// alef:hash:7a28870ed956f3bc905e5658d6a02739f99c913fd47058d0b86bf0780e634064
package dev.kreuzberg.treesitterlanguagepack;

/**
 * The cross-process download cache lock file could not be acquired or created.
 */
public class CacheLockException extends ErrorException {
  /** Creates a new CacheLockException with the given message. */
  public CacheLockException(final String message) {
    super(message);
  }

  /** Creates a new CacheLockException with the given message and cause. */
  public CacheLockException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
