// DO NOT EDIT - auto-generated by alef
// alef:hash:56f23c3c5922dca60d8da85814d3ea592b236e45ace64bdd6f2a16b59f4f83ff
package dev.kreuzberg.treesitterlanguagepack;

/**
 * The cross-process download cache lock file could not be acquired or created.
 */
public class CacheLockException extends ErrorException {
  /** Creates a new CacheLockException with the given message. */
  public CacheLockException(final String message) {
    super(message);
  }

  /** Creates a new CacheLockException with the given message and cause. */
  public CacheLockException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
