// DO NOT EDIT - auto-generated by alef
// alef:hash:cf84eb383aae226537d4dfbf11634379392a6f7ee6eaead589726b5e5d31f75e
package dev.kreuzberg.treesitterlanguagepack;

/**
 * The cross-process download cache lock file could not be acquired or created.
 */
public class CacheLockException extends ErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new CacheLockException with the given message. */
  public CacheLockException(final String message) {
    super(message);
  }

  /** Creates a new CacheLockException with the given message and cause. */
  public CacheLockException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
