// DO NOT EDIT - auto-generated by alef
// alef:hash:b906bff062ca5b5286fd2f52d467bfed7845bdb2a0022ce89f744f6715668926
package dev.kreuzberg.treesitterlanguagepack;

public class ChecksumMismatchException extends ErrorException {
    /** Creates a new ChecksumMismatchException with the given message. */
    public ChecksumMismatchException(final String message) {
        super(message);
    }

    /** Creates a new ChecksumMismatchException with the given message and cause. */
    public ChecksumMismatchException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
