// DO NOT EDIT - auto-generated by alef
// alef:hash:8e6b60fdb22a27e2f51a6dd18bffcfb22706f9892d9a8d350deea54c0df67828
package dev.kreuzberg.treesitterlanguagepack;

/**
 * The downloaded file's SHA-256 digest did not match the manifest's expected value.
 */
public class ChecksumMismatchException extends ErrorException {
  /** Creates a new ChecksumMismatchException with the given message. */
  public ChecksumMismatchException(final String message) {
    super(message);
  }

  /** Creates a new ChecksumMismatchException with the given message and cause. */
  public ChecksumMismatchException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
