// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7f960fc8544c74f570580d382d6aded8de5314d8618668e20c9dc7c24f87944e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * A chunk of source code with rich metadata.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CodeChunkBuilder.class)
public record CodeChunk(String content, @JsonProperty("start_byte") long startByte,
        @JsonProperty("end_byte") long endByte, @JsonProperty("start_line") long startLine,
        @JsonProperty("end_line") long endLine, ChunkContext metadata) {
    public static CodeChunkBuilder builder() {
        return new CodeChunkBuilder();
    }
}
