// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:45eb0a9e27bd4530f0932097447f0d2d6ddc29bf34ee8e5fc427f431c61c3581
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/** A chunk of source code with rich metadata. */
@JsonPOJOBuilder(withPrefix = "with")
public class CodeChunkBuilder {

  @JsonProperty("content")
  private String content = "";

  @JsonProperty("start_byte")
  private long startByte = 0;

  @JsonProperty("end_byte")
  private long endByte = 0;

  @JsonProperty("start_line")
  private long startLine = 0;

  @JsonProperty("end_line")
  private long endLine = 0;

  @JsonProperty("metadata")
  private ChunkContext metadata = null;

  /** Sets the content field. */
  @JsonProperty("content")
  public CodeChunkBuilder withContent(final String value) {
    this.content = value;
    return this;
  }

  /** Sets the startByte field. */
  @JsonProperty("start_byte")
  public CodeChunkBuilder withStartByte(final long value) {
    this.startByte = value;
    return this;
  }

  /** Sets the endByte field. */
  @JsonProperty("end_byte")
  public CodeChunkBuilder withEndByte(final long value) {
    this.endByte = value;
    return this;
  }

  /** Sets the startLine field. */
  @JsonProperty("start_line")
  public CodeChunkBuilder withStartLine(final long value) {
    this.startLine = value;
    return this;
  }

  /** Sets the endLine field. */
  @JsonProperty("end_line")
  public CodeChunkBuilder withEndLine(final long value) {
    this.endLine = value;
    return this;
  }

  /** Sets the metadata field. */
  @JsonProperty("metadata")
  public CodeChunkBuilder withMetadata(final ChunkContext value) {
    this.metadata = value;
    return this;
  }

  /** Builds the CodeChunk instance. */
  public CodeChunk build() {
    return new CodeChunk(content, startByte, endByte, startLine, endLine, metadata);
  }
}
