// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:366e4c8ea9d7faf2f7f60323b445cf09d7d68f3d820d87ae297aed3b4a4fc643
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.treesitterlanguagepack;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The kind of a comment found in source code.
 *
 * Distinguishes between single-line comments, block (multi-line) comments,
 * and documentation comments.
 */
public enum CommentKind {
    Line("line"),
    Block("block"),
    Doc("doc");

    /** The string value. */
    private final String value;

    CommentKind(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static CommentKind fromValue(final String value) {
        for (CommentKind e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
