// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:abff2a3bf1a5fbcd4e3bea9efb13ca36046e24bdea9f7f54a500a869ae6f684d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * A comment extracted from source code.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CommentInfo.Builder.class)
public record CommentInfo(
    String text,
    CommentKind kind,
    Span span,
    @Nullable @JsonProperty("associated_node") String associatedNode
) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with")
    public static final class Builder {

        private String text = "";
        private CommentKind kind = null;
        private Span span = null;
        @JsonProperty("associated_node")
        private Optional<String> associatedNode = Optional.empty();

        /** Sets the text field. */
        public Builder withText(final String value) {
            this.text = value;
            return this;
        }

        /** Sets the kind field. */
        public Builder withKind(final CommentKind value) {
            this.kind = value;
            return this;
        }

        /** Sets the span field. */
        public Builder withSpan(final Span value) {
            this.span = value;
            return this;
        }

        /** Sets the associatedNode field. */
        @JsonProperty("associated_node")
        public Builder withAssociatedNode(final @Nullable String value) {
            this.associatedNode = Optional.ofNullable(value);
            return this;
        }

        /** Builds the CommentInfo instance. */
        public CommentInfo build() {
            return new CommentInfo(
                text,
                kind,
                span,
                associatedNode.orElse(null)
            );
        }
    }
    // CPD-ON
}
