// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d3675c2cc1b47ecfe4ed51bb5c59a1ac2349d2cddf744adf5ee929a88920c28a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jspecify.annotations.Nullable;

/**
 * A comment extracted from source code.
 */
@SuppressWarnings("checkstyle:LineLength")
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CommentInfoBuilder.class)
public record CommentInfo(String text, CommentKind kind, Span span,
        @Nullable @JsonProperty("associated_node") String associatedNode) {
    public static CommentInfoBuilder builder() {
        return new CommentInfoBuilder();
    }
}
