// DO NOT EDIT - auto-generated by alef
// alef:hash:f1b49da8b8d934eb13d7453e1cf4e27ae81c6449e165f6addb8ebe5d308bab59
package dev.kreuzberg.treesitterlanguagepack;

/**
 * A configuration file or value was invalid or could not be applied.
 */
public class ConfigException extends ErrorException {
  /** Creates a new ConfigException with the given message. */
  public ConfigException(final String message) {
    super(message);
  }

  /** Creates a new ConfigException with the given message and cause. */
  public ConfigException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
