// DO NOT EDIT - auto-generated by alef
// alef:hash:360e02edf70c86e2e1a835db7f366f6b66fdd0a250df7395639cdaa155a85d21
package dev.kreuzberg.treesitterlanguagepack;

/**
 * A configuration file or value was invalid or could not be applied.
 */
public class ConfigException extends ErrorException {
  /** Creates a new ConfigException with the given message. */
  public ConfigException(final String message) {
    super(message);
  }

  /** Creates a new ConfigException with the given message and cause. */
  public ConfigException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
