// DO NOT EDIT - auto-generated by alef
// alef:hash:8b5c2f63b16359cd5303d35101d1bf65aaac2e803ec9acf95020cb2223b35b1c
package dev.kreuzberg.treesitterlanguagepack;

public class ConfigException extends ErrorException {
    /** Creates a new ConfigException with the given message. */
    public ConfigException(final String message) {
        super(message);
    }

    /** Creates a new ConfigException with the given message and cause. */
    public ConfigException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
