// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a21aa2a3f1189c5b552c55448fa68a18ffa0606495ceaabfd947328f099b8706
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * A diagnostic (syntax error, missing node, etc.) from parsing.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record Diagnostic(String message, DiagnosticSeverity severity, Span span) {
    public static DiagnosticBuilder builder() {
        return new DiagnosticBuilder();
    }
}
