// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:89bb7a95df4b87bb8ecef49f69794c82c1c20ad9c2d5b269cf9198b4008b3185
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Severity level of a diagnostic produced during parsing.
 *
 * Used to classify parse errors, warnings, and informational messages found in the syntax tree.
 */
@SuppressWarnings("checkstyle:LineLength")
public enum DiagnosticSeverity {
    Error("error"), Warning("warning"), Info("info");

    /** The string value. */
    private final String value;

    DiagnosticSeverity(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static DiagnosticSeverity fromValue(final String value) {
        for (DiagnosticSeverity e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }
}
