// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:703bf9e3f2d07b4870c409fc81dfac5fc5153c70a703a769f6390451fcadbee9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * A diagnostic (syntax error, missing node, etc.) from parsing.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class DiagnosticBuilder {

    private String message = "";
    private DiagnosticSeverity severity = null;
    private Span span = null;

    /** Sets the message field. */
    public DiagnosticBuilder withMessage(final String value) {
        this.message = value;
        return this;
    }

    /** Sets the severity field. */
    public DiagnosticBuilder withSeverity(final DiagnosticSeverity value) {
        this.severity = value;
        return this;
    }

    /** Sets the span field. */
    public DiagnosticBuilder withSpan(final Span value) {
        this.span = value;
        return this;
    }

    /** Builds the Diagnostic instance. */
    public Diagnostic build() {
        return new Diagnostic(
            message,
            severity,
            span
        );
    }
}
