// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d8f2232976e2562cabb7cbc6b24d1fc65fe795cf5308b6248bfb18c3c1fb7bbd
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * A diagnostic (syntax error, missing node, etc.) from parsing.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = Diagnostic.Builder.class)
public record Diagnostic(String message, DiagnosticSeverity severity, Span span) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with")
    public static final class Builder {

        private String message = "";
        private DiagnosticSeverity severity = null;
        private Span span = null;

        /** Sets the message field. */
        public Builder withMessage(final String value) {
            this.message = value;
            return this;
        }

        /** Sets the severity field. */
        public Builder withSeverity(final DiagnosticSeverity value) {
            this.severity = value;
            return this;
        }

        /** Sets the span field. */
        public Builder withSpan(final Span value) {
            this.span = value;
            return this;
        }

        /** Builds the Diagnostic instance. */
        public Diagnostic build() {
            return new Diagnostic(
                message,
                severity,
                span
            );
        }
    }
    // CPD-ON
}
