// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:877ec3b45631b4d930c4aa7e28e7afb233b4bf66a2c5f32e4aa36ff09230f250
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jspecify.annotations.Nullable;

/**
 * A docstring extracted from source code.
 */
@SuppressWarnings("checkstyle:LineLength")
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DocstringInfoBuilder.class)
public record DocstringInfo(String text, Object format, Span span,
        @Nullable @JsonProperty("associated_item") String associatedItem,
        @JsonInclude(JsonInclude.Include.NON_NULL) @JsonProperty("parsed_sections") List<DocSection> parsedSections) {
    public static DocstringInfoBuilder builder() {
        return new DocstringInfoBuilder();
    }
}
