// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:87e2264ad2b500333f5a6b6e40d79768f748b09e3d8d197a6ef0428b0eac4294
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jspecify.annotations.Nullable;

/**
 * A docstring extracted from source code.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DocstringInfoBuilder.class)
public record DocstringInfo(
    String text,
    DocstringFormat format,
    Span span,
    @Nullable @JsonProperty("associated_item") String associatedItem,
    @JsonInclude(JsonInclude.Include.NON_NULL) @JsonProperty("parsed_sections") List<DocSection> parsedSections
) {
    public static DocstringInfoBuilder builder() {
        return new DocstringInfoBuilder();
    }

    /**
     * Parse a {@code DocstringInfo} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws TreeSitterLanguagePackRsException if the JSON cannot be deserialised.
     */
    public static DocstringInfo fromJson(String json) throws TreeSitterLanguagePackRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, DocstringInfo.class);
        } catch (Exception e) {
            throw new TreeSitterLanguagePackRsException("Failed to parse DocstringInfo from JSON: " + e.getMessage(), e);
        }
    }
}
