// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7070e26a3ca0ea2cdff37aac15dac06cd874815923a32e49e015b8027c95d3d6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The format of a docstring extracted from source code.
 *
 * Identifies the docstring convention used, which varies by language
 * (e.g., Python triple-quoted strings, JSDoc, Rustdoc {@code ///} comments).
 */
public enum DocstringFormat {
    PythonTripleQuote("pythontriplequote"),
    JSDoc("jsdoc"),
    Rustdoc("rustdoc"),
    GoDoc("godoc"),
    JavaDoc("javadoc"),
    Other("other");

    /** The string value. */
    private final String value;

    DocstringFormat(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static DocstringFormat fromValue(final String value) {
        for (DocstringFormat e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }
}
