// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b48f13445b460aa01ad772e5ff17caf1937ac7b59a36097edb275fd7ac8deac6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.treesitterlanguagepack;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * A section within a docstring (e.g., Args, Returns, Raises).
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DocSection.Builder.class)
public record DocSection(
    @JsonProperty("kind") String kind,
    @Nullable @JsonProperty("name") String name,
    @JsonProperty("description") String description
) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

private String kind = "";
private String name = null;
private String description = "";

        /** Sets the kind field. */
        @JsonProperty("kind")
        public Builder withKind(final String value) {
            this.kind = value;
            return this;
        }

        /** Sets the name field. */
        @JsonProperty("name")
        public Builder withName(final @Nullable String value) {
            this.name = value;
            return this;
        }

        /** Sets the description field. */
        @JsonProperty("description")
        public Builder withDescription(final String value) {
            this.description = value;
            return this;
        }

        /** Builds the DocSection instance. */
        public DocSection build() {
            return new DocSection(
                kind,
                name,
                description
            );
        }
    }
    // CPD-ON
}
