// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4697af7626f8bb84399b6e46df5e8184f30100b9b98db924fec1d692f0a5036b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jspecify.annotations.Nullable;

/**
 * A section within a docstring (e.g., Args, Returns, Raises).
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DocSectionBuilder.class)
public record DocSection(String kind, @Nullable String name, String description) {
    public static DocSectionBuilder builder() {
        return new DocSectionBuilder();
    }
}
