// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:74ed423e90aba1062035932102f75b3aa1908ed901b4d68d7015af978b4cfdd1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import java.util.Optional;

/** A section within a docstring (e.g., Args, Returns, Raises). */
@JsonPOJOBuilder(withPrefix = "with")
public class DocSectionBuilder {

  @JsonProperty("kind")
  private String kind = "";

  @JsonProperty("name")
  private Optional<String> name = Optional.empty();

  @JsonProperty("description")
  private String description = "";

  /** Sets the kind field. */
  @JsonProperty("kind")
  public DocSectionBuilder withKind(final String value) {
    this.kind = value;
    return this;
  }

  /** Sets the name field. */
  @JsonProperty("name")
  public DocSectionBuilder withName(final Optional<String> value) {
    this.name = value;
    return this;
  }

  /** Sets the description field. */
  @JsonProperty("description")
  public DocSectionBuilder withDescription(final String value) {
    this.description = value;
    return this;
  }

  /** Builds the DocSection instance. */
  public DocSection build() {
    return new DocSection(kind, name.orElse(null), description);
  }
}
