// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:efb32bf4f7d651920711ce4d35f9ece63e3d9251d93b807f1191634b275bb154
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import java.lang.foreign.MemorySegment;

/**
 * Manages downloading and caching of pre-built parser shared libraries.
 */
@SuppressWarnings("checkstyle:LineLength")
public class DownloadManager implements AutoCloseable {
    private final MemorySegment handle;

    DownloadManager(MemorySegment handle) {
        this.handle = handle;
    }

    MemorySegment handle() {
        return this.handle;
    }

    @Override
    public void close() {
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                NativeLib.TS_PACK_DOWNLOAD_MANAGER_FREE.invoke(handle);
            } catch (Throwable e) {
                throw new RuntimeException("Failed to free DownloadManager: " + e.getMessage(), e);
            }
        }
    }
}
