// DO NOT EDIT - auto-generated by alef
// alef:hash:73d6ebd2ae99bfcd45abf84aa28e1ed6136847bdc9242fcda7f9ab26367c3320
package dev.kreuzberg.treesitterlanguagepack;

/**
 * A parser download from GitHub releases failed.
 */
public class DownloadException extends ErrorException {
  /** Creates a new DownloadException with the given message. */
  public DownloadException(final String message) {
    super(message);
  }

  /** Creates a new DownloadException with the given message and cause. */
  public DownloadException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
