// DO NOT EDIT - auto-generated by alef
// alef:hash:7a28870ed956f3bc905e5658d6a02739f99c913fd47058d0b86bf0780e634064
package dev.kreuzberg.treesitterlanguagepack;

/**
 * A dynamic shared library could not be loaded at runtime.
 */
public class DynamicLoadException extends ErrorException {
  /** Creates a new DynamicLoadException with the given message. */
  public DynamicLoadException(final String message) {
    super(message);
  }

  /** Creates a new DynamicLoadException with the given message and cause. */
  public DynamicLoadException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
