// DO NOT EDIT - auto-generated by alef
// alef:hash:eafdd9d7178a2638060ef75fbdbbd878f44de4d095f40339ca9dc8f615f707ed
package dev.kreuzberg.treesitterlanguagepack;

public class DynamicLoadException extends ErrorException {
    /** Creates a new DynamicLoadException with the given message. */
    public DynamicLoadException(final String message) {
        super(message);
    }

    /** Creates a new DynamicLoadException with the given message and cause. */
    public DynamicLoadException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
