// DO NOT EDIT - auto-generated by alef
// alef:hash:44a0d5babc63706f84f2e19d48cf948b55c87cbbe3e341ee15c08a54f4d42d8f
package dev.kreuzberg.treesitterlanguagepack;

public class DynamicLoadException extends ErrorException {
    /** Creates a new DynamicLoadException with the given message. */
    public DynamicLoadException(final String message) {
        super(message);
    }

    /** Creates a new DynamicLoadException with the given message and cause. */
    public DynamicLoadException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
