// DO NOT EDIT - auto-generated by alef
// alef:hash:48eaa6aee6a9621260908f86b470f0394ca8594aea6b158a71425b92dd28df38
package dev.kreuzberg.treesitterlanguagepack;

/**
 * Errors that can occur when using the tree-sitter language pack.
 *
 * Covers language lookup failures, parse errors, query errors, and I/O issues.
 * Feature-gated variants are included when `config`, `download`, or related
 * features are enabled.
 */
public class ErrorException extends Exception {
  private static final long serialVersionUID = 1L;
  /** Creates a new ErrorException with the given message. */
  public ErrorException(final String message) {
    super(message);
  }

  /** Creates a new ErrorException with the given message and cause. */
  public ErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
