// DO NOT EDIT - auto-generated by alef
// alef:hash:4fd28d28be5d5c08a42b1adaeb8565a890c281118692f20fb4e08cfac6ad7fcf
package dev.kreuzberg.treesitterlanguagepack;

/**
 * Errors that can occur when using the tree-sitter language pack.
 *
 * Covers language lookup failures, parse errors, query errors, and I/O issues.
 * Feature-gated variants are included when `config`, `download`, or related
 * features are enabled.
 */
public class ErrorException extends Exception {
  private static final long serialVersionUID = 1L;
  /** Creates a new ErrorException with the given message. */
  public ErrorException(final String message) {
    super(message);
  }

  /** Creates a new ErrorException with the given message and cause. */
  public ErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
