// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8ae622e2eb8371e5df062fc88c40f38c851b267180cdb0c0ac5db8d512816559
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * An export statement extracted from source code.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record ExportInfo(String name, ExportKind kind, Span span) {
    public static ExportInfoBuilder builder() {
        return new ExportInfoBuilder();
    }
}
