// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5a70fc98d4b17bc729623d3be69bdadeed537fea1a38773d0ac2a3eb4934e76f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

/**
 * An export statement extracted from source code.
 */
public class ExportInfoBuilder {

    private String name = "";
    private ExportKind kind = null;
    private Span span = null;

    /** Sets the name field. */
    public ExportInfoBuilder withName(final String value) {
        this.name = value;
        return this;
    }

    /** Sets the kind field. */
    public ExportInfoBuilder withKind(final ExportKind value) {
        this.kind = value;
        return this;
    }

    /** Sets the span field. */
    public ExportInfoBuilder withSpan(final Span value) {
        this.span = value;
        return this;
    }

    /** Builds the ExportInfo instance. */
    public ExportInfo build() {
        return new ExportInfo(name, kind, span);
    }
}
