// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3dc68255f40ca241893f3fca14122738a4ea94585b34d1c0a3e2f31afd64ee35
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.treesitterlanguagepack;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The kind of an export statement found in source code.
 *
 * Covers named exports, default exports, and re-exports from other modules.
 */
public enum ExportKind {
    Named("named"),
    Default("default"),
    ReExport("reexport");

    /** The string value. */
    private final String value;

    ExportKind(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static ExportKind fromValue(final String value) {
        for (ExportKind e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
