// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b88d2cc3eedfddde64cbc00908e46a0ed4a5b400e9c54227d470a705684b0e98
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * An export statement extracted from source code.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ExportInfo.Builder.class)
public record ExportInfo(String name, ExportKind kind, Span span) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with")
    public static final class Builder {

        private String name = "";
        private ExportKind kind = null;
        private Span span = null;

        /** Sets the name field. */
        public Builder withName(final String value) {
            this.name = value;
            return this;
        }

        /** Sets the kind field. */
        public Builder withKind(final ExportKind value) {
            this.kind = value;
            return this;
        }

        /** Sets the span field. */
        public Builder withSpan(final Span value) {
            this.span = value;
            return this;
        }

        /** Builds the ExportInfo instance. */
        public ExportInfo build() {
            return new ExportInfo(
                name,
                kind,
                span
            );
        }
    }
    // CPD-ON
}
