// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bb4f7b93b97d64c44a784ad899298b669e39b6206b05af6fee6923b09f137f69
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.treesitterlanguagepack;


/**
 * An export statement extracted from source code.
 */
public record ExportInfo(
    String name,
    ExportKind kind,
    Span span) {
  /** Creates a new Builder for constructing instances of this record. */
  public static Builder builder() {
    return new Builder();
  }

  // CPD-OFF
  /** Jackson builder for ExportInfo deserialization. */
  public static final class Builder {

    private String name;
    private ExportKind kind;
    private Span span;

    /** Sets the name field. */
    public Builder withName(final String value) {
      this.name = value;
      return this;
    }

    /** Sets the kind field. */
    public Builder withKind(final ExportKind value) {
      this.kind = value;
      return this;
    }

    /** Sets the span field. */
    public Builder withSpan(final Span value) {
      this.span = value;
      return this;
    }

    /** Constructs a ExportInfo instance from the builder's current state. */
    public ExportInfo build() {
      return new ExportInfo(name, kind, span);
    }
  }
  // CPD-ON
}
