// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bc0477646e1de2f7c74c1edb64f38add2aea7f28c8674483bd108f463f0601a8
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * An import statement extracted from source code.
 */
@SuppressWarnings("checkstyle:LineLength")
@JsonPOJOBuilder(withPrefix = "with")
public class ImportInfoBuilder {

    private String source = "";
    private List<String> items = List.of();
    private Optional<String> alias = Optional.empty();
    private boolean isWildcard = false;
    private Span span = null;

    /** Sets the source field. */
    public ImportInfoBuilder withSource(final String value) {
        this.source = value;
        return this;
    }

    /** Sets the items field. */
    public ImportInfoBuilder withItems(final List<String> value) {
        this.items = value;
        return this;
    }

    /** Sets the alias field. */
    public ImportInfoBuilder withAlias(final Optional<String> value) {
        this.alias = value;
        return this;
    }

    /** Sets the isWildcard field. */
    public ImportInfoBuilder withIsWildcard(final boolean value) {
        this.isWildcard = value;
        return this;
    }

    /** Sets the span field. */
    public ImportInfoBuilder withSpan(final Span value) {
        this.span = value;
        return this;
    }

    /** Builds the ImportInfo instance. */
    public ImportInfo build() {
        return new ImportInfo(source, items, alias.orElse(null), isWildcard, span);
    }
}
