// DO NOT EDIT - auto-generated by alef
// alef:hash:d156b3f21d3da47b056bc94d5a2efc5ee0d8c6d26a733a0f453b579ce100d595
package dev.kreuzberg.treesitterlanguagepack;

/**
 * A byte range was invalid (e.g., end before start, or out of bounds).
 */
public class InvalidRangeException extends ErrorException {
    /** Creates a new InvalidRangeException with the given message. */
    public InvalidRangeException(final String message) {
        super(message);
    }

    /** Creates a new InvalidRangeException with the given message and cause. */
    public InvalidRangeException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
