// DO NOT EDIT - auto-generated by alef
// alef:hash:7bec16f5c828b57399dc70e8709c84b136820496848b19e2e73499bff909745b
package dev.kreuzberg.treesitterlanguagepack;

public class InvalidRangeException extends ErrorException {
    /** Creates a new InvalidRangeException with the given message. */
    public InvalidRangeException(final String message) {
        super(message);
    }

    /** Creates a new InvalidRangeException with the given message and cause. */
    public InvalidRangeException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
