// DO NOT EDIT - auto-generated by alef
// alef:hash:ca0f10e6d251825c38f09febfc70f4fd8d58b076eed7823a4d5ed9ef4bc06370
package dev.kreuzberg.treesitterlanguagepack;

public class InvalidRangeException extends ErrorException {
    /** Creates a new InvalidRangeException with the given message. */
    public InvalidRangeException(final String message) {
        super(message);
    }

    /** Creates a new InvalidRangeException with the given message and cause. */
    public InvalidRangeException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
