// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7bec16f5c828b57399dc70e8709c84b136820496848b19e2e73499bff909745b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

/** Exception thrown when input validation fails. */
@SuppressWarnings("checkstyle:LineLength")
public class InvalidInputException extends TreeSitterLanguagePackRsException {
    /** Creates a new InvalidInputException. */
    public InvalidInputException(final String message) {
        super(1, message);
    }

    /** Creates a new InvalidInputException with a cause. */
    public InvalidInputException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
