// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:eafdd9d7178a2638060ef75fbdbbd878f44de4d095f40339ca9dc8f615f707ed
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.treesitterlanguagepack;

import java.lang.foreign.MemorySegment;

public class Language implements AutoCloseable {
    private final MemorySegment handle;

    Language(MemorySegment handle) {
        this.handle = handle;
    }

    MemorySegment handle() {
        return this.handle;
    }

    @Override
    public void close() {
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                NativeLib.TS_PACK_LANGUAGE_FREE.invoke(handle);
            } catch (Throwable e) {
                throw new RuntimeException("Failed to free Language: " + e.getMessage(), e);
            }
        }
    }
}
