// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e02b60e1678c7f1ae243dd6d6a900f49764b8f18f5b003a6c63483b48fe472e2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import java.lang.foreign.MemorySegment;

/**
 * Thread-safe registry of tree-sitter language parsers.
 *
 * Manages both statically compiled and dynamically loaded language grammars. Use LanguageRegistry::new() for the
 * default registry, or access the global instance via the module-level convenience functions ({@code get_language},
 * {@code available_languages}, etc.).
 */
@SuppressWarnings("checkstyle:LineLength")
public class LanguageRegistry implements AutoCloseable {
    private final MemorySegment handle;

    LanguageRegistry(MemorySegment handle) {
        this.handle = handle;
    }

    MemorySegment handle() {
        return this.handle;
    }

    @Override
    public void close() {
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                NativeLib.TS_PACK_LANGUAGE_REGISTRY_FREE.invoke(handle);
            } catch (Throwable e) {
                throw new RuntimeException("Failed to free LanguageRegistry: " + e.getMessage(), e);
            }
        }
    }
}
