// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4d194fc2fb6db6657c77edf019630ad4209ef925aee190d9e8edab057f2ba2fc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import java.lang.foreign.MemorySegment;

public class Language implements AutoCloseable {
    private final MemorySegment handle;

    Language(MemorySegment handle) {
        this.handle = handle;
    }

    MemorySegment handle() {
        return this.handle;
    }

    @Override
    public void close() {
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                NativeLib.TS_PACK_LANGUAGE_FREE.invoke(handle);
            } catch (Throwable e) {
                throw new RuntimeException("Failed to free Language: " + e.getMessage(), e);
            }
        }
    }
}
