// DO NOT EDIT - auto-generated by alef
// alef:hash:f1b49da8b8d934eb13d7453e1cf4e27ae81c6449e165f6addb8ebe5d308bab59
package dev.kreuzberg.treesitterlanguagepack;

/**
 * The requested language name (or alias) was not found in the registry.
 */
public class LanguageNotFoundException extends ErrorException {
  /** Creates a new LanguageNotFoundException with the given message. */
  public LanguageNotFoundException(final String message) {
    super(message);
  }

  /** Creates a new LanguageNotFoundException with the given message and cause. */
  public LanguageNotFoundException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
