// DO NOT EDIT - auto-generated by alef
// alef:hash:cf84eb383aae226537d4dfbf11634379392a6f7ee6eaead589726b5e5d31f75e
package dev.kreuzberg.treesitterlanguagepack;

/**
 * The requested language name (or alias) was not found in the registry.
 */
public class LanguageNotFoundException extends ErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new LanguageNotFoundException with the given message. */
  public LanguageNotFoundException(final String message) {
    super(message);
  }

  /** Creates a new LanguageNotFoundException with the given message and cause. */
  public LanguageNotFoundException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
