// DO NOT EDIT - auto-generated by alef
// alef:hash:8e6b60fdb22a27e2f51a6dd18bffcfb22706f9892d9a8d350deea54c0df67828
package dev.kreuzberg.treesitterlanguagepack;

/**
 * An internal `RwLock` or `Mutex` was poisoned by a previous panic.
 */
public class LockPoisonedException extends ErrorException {
  /** Creates a new LockPoisonedException with the given message. */
  public LockPoisonedException(final String message) {
    super(message);
  }

  /** Creates a new LockPoisonedException with the given message and cause. */
  public LockPoisonedException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
