// DO NOT EDIT - auto-generated by alef
// alef:hash:93bc2a1c57b034b5427820d307c8d1eab4f8228306c15ee567e6420f464c24ef
package dev.kreuzberg.treesitterlanguagepack;

public class LockPoisonedException extends ErrorException {
    /** Creates a new LockPoisonedException with the given message. */
    public LockPoisonedException(final String message) {
        super(message);
    }

    /** Creates a new LockPoisonedException with the given message and cause. */
    public LockPoisonedException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
