// DO NOT EDIT - auto-generated by alef
// alef:hash:662dbbf50555ef0b3d0f168ee43cdb4ecd8316e31f16c1cbb2adb942fbf9d618
package dev.kreuzberg.treesitterlanguagepack;

public class LockPoisonedException extends ErrorException {
    /** Creates a new LockPoisonedException with the given message. */
    public LockPoisonedException(final String message) {
        super(message);
    }

    /** Creates a new LockPoisonedException with the given message and cause. */
    public LockPoisonedException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
