// DO NOT EDIT - auto-generated by alef
// alef:hash:a43a7c3dd7356c9e831c86cc5a386de867cd00fec9ff36c1607c0e9a51ea5f4d
package dev.kreuzberg.treesitterlanguagepack;

public class NullLanguagePointerException extends ErrorException {
    /** Creates a new NullLanguagePointerException with the given message. */
    public NullLanguagePointerException(final String message) {
        super(message);
    }

    /** Creates a new NullLanguagePointerException with the given message and cause. */
    public NullLanguagePointerException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
