// DO NOT EDIT - auto-generated by alef
// alef:hash:fdaedbc30d45f59f128e477ac54794046794ad0608ac245915e5e9bd7fbac89f
package dev.kreuzberg.treesitterlanguagepack;

/**
 * The tree-sitter language function returned a null pointer for the given language name.
 */
public class NullLanguagePointerException extends ErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new NullLanguagePointerException with the given message. */
  public NullLanguagePointerException(final String message) {
    super(message);
  }

  /** Creates a new NullLanguagePointerException with the given message and cause. */
  public NullLanguagePointerException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
