// DO NOT EDIT - auto-generated by alef
// alef:hash:8e6b60fdb22a27e2f51a6dd18bffcfb22706f9892d9a8d350deea54c0df67828
package dev.kreuzberg.treesitterlanguagepack;

/**
 * The tree-sitter language function returned a null pointer for the given language name.
 */
public class NullLanguagePointerException extends ErrorException {
  /** Creates a new NullLanguagePointerException with the given message. */
  public NullLanguagePointerException(final String message) {
    super(message);
  }

  /** Creates a new NullLanguagePointerException with the given message and cause. */
  public NullLanguagePointerException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
