// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c41e03c6bd669d057dc07825c88db266f848ae4e884d8a9d0684f421278e76fe
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Configuration for the tree-sitter language pack.
 *
 * Controls cache directory and which languages to pre-download. Can be loaded from a TOML file, constructed
 * programmatically, or passed as a dict/object from language bindings.
 *
 * # Example
 *
 * {@code }{@code no_run} use tree_sitter_language_pack::PackConfig;
 *
 * let config = PackConfig { cache_dir: None, languages: Some(vec!["python".to_string(), "rust".to_string()]), groups:
 * None, }; {@code }{@code }
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record PackConfig(
        /** Override default cache directory. */
        @JsonProperty("cache_dir") Optional<java.nio.file.Path> cacheDir,
        /** Languages to pre-download on init. */
        Optional<List<String>> languages,
        /** Language groups to pre-download (e.g. {@code "web"}, {@code "systems"}, {@code "scripting"}). */
        Optional<List<String>> groups) {
    public static PackConfigBuilder builder() {
        return new PackConfigBuilder();
    }
}
