// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:40f36804e9e7b8bbc9167cadfe3d7afa2fc1f17408f2d4917ae1ab4ee3b5a4db
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.List;
import org.jspecify.annotations.Nullable;

/**
 * Configuration for the tree-sitter language pack.
 *
 * <p>Controls cache directory and which languages to pre-download. Can be loaded from a TOML file,
 * constructed programmatically, or passed as a dict/object from language bindings.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PackConfigBuilder.class)
public record PackConfig(
    @JsonProperty("cache_dir") java.nio.file.@Nullable Path cacheDir,
    @Nullable List<String> languages,
    @Nullable List<String> groups) {
  public static PackConfigBuilder builder() {
    return new PackConfigBuilder();
  }

  /**
   * Parse a {@code PackConfig} from a JSON string.
   *
   * @param json JSON serialisation matching the Rust-side field names (snake_case).
   * @throws TreeSitterLanguagePackRsException if the JSON cannot be deserialised.
   */
  public static PackConfig fromJson(String json) throws TreeSitterLanguagePackRsException {
    try {
      return new com.fasterxml.jackson.databind.ObjectMapper()
          .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
          .findAndRegisterModules()
          .setPropertyNamingStrategy(
              com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
          .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
          .configure(
              com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
          .readValue(json, PackConfig.class);
    } catch (Exception e) {
      throw new TreeSitterLanguagePackRsException(
          "Failed to parse PackConfig from JSON: " + e.getMessage(), e);
    }
  }
}
