// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a0a8f44b2d3f6c8794e79ec84bc100ec0203feef459af64963dd75271290a7bf
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * Configuration for the tree-sitter language pack.
 *
 * Controls cache directory and which languages to pre-download.
 * Can be loaded from a TOML file, constructed programmatically,
 * or passed as a dict/object from language bindings.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PackConfig.Builder.class)
public record PackConfig(
    /**
     * Override default cache directory.
     *
     * Default: {@code ~/.cache/tree-sitter-language-pack/v{version}/libs/}
     */
    @JsonProperty("cache_dir") java.nio.file.@Nullable Path cacheDir,
    /**
     * Languages to pre-download on init.
     *
     * Each entry is a language name (e.g. {@code "python"}, {@code "rust"}).
     */
    @Nullable List<String> languages,
    /**
     * Language groups to pre-download (e.g. {@code "web"}, {@code "systems"}, {@code "scripting"}).
     */
    @Nullable List<String> groups
) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with")
    public static final class Builder {

        @JsonProperty("cache_dir")
        private Optional<java.nio.file.Path> cacheDir = Optional.empty();
        @JsonProperty("languages")
        private Optional<List<String>> languages = Optional.empty();
        @JsonProperty("groups")
        private Optional<List<String>> groups = Optional.empty();

        /** Sets the cacheDir field. */
        @JsonProperty("cache_dir")
        public Builder withCacheDir(final java.nio.file.@Nullable Path value) {
            this.cacheDir = Optional.ofNullable(value);
            return this;
        }

        /** Sets the languages field. */
        @JsonProperty("languages")
        public Builder withLanguages(final @Nullable List<String> value) {
            this.languages = Optional.ofNullable(value);
            return this;
        }

        /** Sets the groups field. */
        @JsonProperty("groups")
        public Builder withGroups(final @Nullable List<String> value) {
            this.groups = Optional.ofNullable(value);
            return this;
        }

        /** Builds the PackConfig instance. */
        public PackConfig build() {
            return new PackConfig(
                cacheDir.orElse(null),
                languages.orElse(null),
                groups.orElse(null)
            );
        }
    }
    // CPD-ON
}
