// DO NOT EDIT - auto-generated by alef
// alef:hash:cf84eb383aae226537d4dfbf11634379392a6f7ee6eaead589726b5e5d31f75e
package dev.kreuzberg.treesitterlanguagepack;

/**
 * The language could not be applied to the parser (e.g., ABI version mismatch).
 */
public class ParserSetupException extends ErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ParserSetupException with the given message. */
  public ParserSetupException(final String message) {
    super(message);
  }

  /** Creates a new ParserSetupException with the given message and cause. */
  public ParserSetupException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
