// DO NOT EDIT - auto-generated by alef
// alef:hash:7644bf176b64c3c0cc108f5e064f25e569bf59389216576332b3857ba268dd10
package dev.kreuzberg.treesitterlanguagepack;

public class ParseFailedException extends ErrorException {
    /** Creates a new ParseFailedException with the given message. */
    public ParseFailedException(final String message) {
        super(message);
    }

    /** Creates a new ParseFailedException with the given message and cause. */
    public ParseFailedException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
