// DO NOT EDIT - auto-generated by alef
// alef:hash:8bb43fc12f987b2e754f9b1981768a07345d578eb7fe7f956b844c10cb2c2988
package dev.kreuzberg.treesitterlanguagepack;

/**
 * The tree-sitter parser returned no tree for the given source input.
 */
public class ParseFailedException extends ErrorException {
  /** Creates a new ParseFailedException with the given message. */
  public ParseFailedException(final String message) {
    super(message);
  }

  /** Creates a new ParseFailedException with the given message and cause. */
  public ParseFailedException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
