// DO NOT EDIT - auto-generated by alef
// alef:hash:3dc68255f40ca241893f3fca14122738a4ea94585b34d1c0a3e2f31afd64ee35
package dev.kreuzberg.treesitterlanguagepack;

public class ParserSetupException extends ErrorException {
    /** Creates a new ParserSetupException with the given message. */
    public ParserSetupException(final String message) {
        super(message);
    }

    /** Creates a new ParserSetupException with the given message and cause. */
    public ParserSetupException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
