// DO NOT EDIT - auto-generated by alef
// alef:hash:6978be3cd82e51d58d8a5daec36139555c42ae08b4f4d6caa34c6f28e14b2178
package dev.kreuzberg.treesitterlanguagepack;

public class ParseFailedException extends ErrorException {
    /** Creates a new ParseFailedException with the given message. */
    public ParseFailedException(final String message) {
        super(message);
    }

    /** Creates a new ParseFailedException with the given message and cause. */
    public ParseFailedException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
