// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:324f77fbc3ffa04a1025b4011d25be44a2d243c53b4827cf177528d472c1f2da
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * A source position — row + column, zero-indexed.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = Point.Builder.class)
public record Point(long row, long column) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with")
    public static final class Builder {

        @JsonProperty("row")
        private long row = 0;
        @JsonProperty("column")
        private long column = 0;

        /** Sets the row field. */
        @JsonProperty("row")
        public Builder withRow(final long value) {
            this.row = value;
            return this;
        }

        /** Sets the column field. */
        @JsonProperty("column")
        public Builder withColumn(final long value) {
            this.column = value;
            return this;
        }

        /** Builds the Point instance. */
        public Point build() {
            return new Point(
                row,
                column
            );
        }
    }
    // CPD-ON
}
