// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:253def366a3f77ef3673ca5129ce8e752546834f68e89a382acbd2a8781a7d1c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.treesitterlanguagepack;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * A source position — row + column, zero-indexed.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = Point.Builder.class)
public record Point(@JsonProperty("row") long row, @JsonProperty("column") long column) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

private long row = 0;
private long column = 0;

        /** Sets the row field. */
        @JsonProperty("row")
        public Builder withRow(final long value) {
            this.row = value;
            return this;
        }

        /** Sets the column field. */
        @JsonProperty("column")
        public Builder withColumn(final long value) {
            this.column = value;
            return this;
        }

        /** Builds the Point instance. */
        public Point build() {
            return new Point(
                row,
                column
            );
        }
    }
    // CPD-ON
}
