// DO NOT EDIT - auto-generated by alef
// alef:hash:5f0f99e3dbb3a829af46b241a6dd4f3b8ef00c2ebf4f4ae703962645353d821b
package dev.kreuzberg.treesitterlanguagepack;

public class QueryErrorException extends ErrorException {
    /** Creates a new QueryErrorException with the given message. */
    public QueryErrorException(final String message) {
        super(message);
    }

    /** Creates a new QueryErrorException with the given message and cause. */
    public QueryErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
