// DO NOT EDIT - auto-generated by alef
// alef:hash:ba3d64f1bdbc733556a596b2718817609290c351656742357e98689aba93f174
package dev.kreuzberg.treesitterlanguagepack;

/**
 * A tree-sitter query could not be compiled or executed.
 */
public class QueryErrorException extends ErrorException {
  /** Creates a new QueryErrorException with the given message. */
  public QueryErrorException(final String message) {
    super(message);
  }

  /** Creates a new QueryErrorException with the given message and cause. */
  public QueryErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
