// DO NOT EDIT - auto-generated by alef
// alef:hash:8e6b60fdb22a27e2f51a6dd18bffcfb22706f9892d9a8d350deea54c0df67828
package dev.kreuzberg.treesitterlanguagepack;

/**
 * A tree-sitter query could not be compiled or executed.
 */
public class QueryErrorException extends ErrorException {
  /** Creates a new QueryErrorException with the given message. */
  public QueryErrorException(final String message) {
    super(message);
  }

  /** Creates a new QueryErrorException with the given message and cause. */
  public QueryErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
