// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f7d5ebe44601908cbd194c4a6aa02de26ddff101e7018e0e047a737ec1b573c6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * Byte and line/column range in source code.
 *
 * Represents both byte offsets (for slicing) and human-readable line/column positions (for display and diagnostics).
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SpanBuilder.class)
public record Span(@JsonProperty("start_byte") long startByte, @JsonProperty("end_byte") long endByte,
        @JsonProperty("start_line") long startLine, @JsonProperty("start_column") long startColumn,
        @JsonProperty("end_line") long endLine, @JsonProperty("end_column") long endColumn) {
    public static SpanBuilder builder() {
        return new SpanBuilder();
    }
}
