// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:276a56fc0505db8ffc157fb37ca9e6b27c4c01bf00a9dec034ca7139836c854b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * A structural item (function, class, struct, etc.) in source code.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record StructureItem(Object kind, Optional<String> name, Optional<String> visibility, Span span,
        @JsonInclude(JsonInclude.Include.NON_NULL) List<StructureItem> children,
        @JsonInclude(JsonInclude.Include.NON_NULL) List<String> decorators,
        @JsonProperty("doc_comment") Optional<String> docComment, Optional<String> signature,
        @JsonProperty("body_span") Optional<Span> bodySpan) {
    public static StructureItemBuilder builder() {
        return new StructureItemBuilder();
    }
}
