// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e9abd76b340e5582deb7d54c7f04bb96b21eb5f27e00e50ece43c723749dc7ef
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import java.util.Optional;

/**
 * A symbol (variable, function, type, etc.) extracted from source code.
 */
public class SymbolInfoBuilder {

    private String name = "";
    private SymbolKind kind = null;
    private Span span = null;
    private Optional<String> typeAnnotation = Optional.empty();
    private Optional<String> doc = Optional.empty();

    /** Sets the name field. */
    public SymbolInfoBuilder withName(final String value) {
        this.name = value;
        return this;
    }

    /** Sets the kind field. */
    public SymbolInfoBuilder withKind(final SymbolKind value) {
        this.kind = value;
        return this;
    }

    /** Sets the span field. */
    public SymbolInfoBuilder withSpan(final Span value) {
        this.span = value;
        return this;
    }

    /** Sets the typeAnnotation field. */
    public SymbolInfoBuilder withTypeAnnotation(final Optional<String> value) {
        this.typeAnnotation = value;
        return this;
    }

    /** Sets the doc field. */
    public SymbolInfoBuilder withDoc(final Optional<String> value) {
        this.doc = value;
        return this;
    }

    /** Builds the SymbolInfo instance. */
    public SymbolInfo build() {
        return new SymbolInfo(name, kind, span, typeAnnotation, doc);
    }
}
