// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:538f89bf854b669ecaf490559800036f564e8d36e983162faf0bc63c12b28c43
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jspecify.annotations.Nullable;

/**
 * A symbol (variable, function, type, etc.) extracted from source code.
 */
@SuppressWarnings("checkstyle:LineLength")
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SymbolInfoBuilder.class)
public record SymbolInfo(String name, Object kind, Span span,
        @Nullable @JsonProperty("type_annotation") String typeAnnotation, @Nullable String doc) {
    public static SymbolInfoBuilder builder() {
        return new SymbolInfoBuilder();
    }
}
