// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:16dfd5fd95549888318d80e0851887868550cf52daf40ef15f9cd6f96e05130e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import java.util.List;

public final class TreeSitterLanguagePack {
    private TreeSitterLanguagePack() {
    }

    /**
     * Detect language name from a file extension (without leading dot).
     *
     * Returns `None` for unrecognized extensions. The match is case-insensitive.
     *
     * ``` use tree_sitter_language_pack::detect_language_from_extension;
     * assert_eq!(detect_language_from_extension("py"), Some("python"));
     * assert_eq!(detect_language_from_extension("RS"), Some("rust")); assert_eq!(detect_language_from_extension("xyz"),
     * None); ```
     */
    public static String detectLanguageFromExtension(final String ext) throws TreeSitterLanguagePackRsException {
        java.util.Objects.requireNonNull(ext, "ext must not be null");
        return TreeSitterLanguagePackRs.detectLanguageFromExtension(ext).orElseThrow();
    }

    /**
     * Detect language name from a file path.
     *
     * Extracts the file extension and looks it up. Returns `None` if the path has no extension or the extension is not
     * recognized.
     *
     * ``` use tree_sitter_language_pack::detect_language_from_path;
     * assert_eq!(detect_language_from_path("src/main.rs"), Some("rust"));
     * assert_eq!(detect_language_from_path("README.md"), Some("markdown"));
     * assert_eq!(detect_language_from_path("Makefile"), None); ```
     */
    public static String detectLanguageFromPath(final String path) throws TreeSitterLanguagePackRsException {
        java.util.Objects.requireNonNull(path, "path must not be null");
        return TreeSitterLanguagePackRs.detectLanguageFromPath(path).orElseThrow();
    }

    /**
     * Detect language name from file content using the shebang line (`#!`).
     *
     * Inspects only the first line of `content`. If it begins with `#!`, the interpreter name is extracted and mapped
     * to a language name.
     *
     * Handles common patterns: - `#!/usr/bin/env python3` → `"python"` - `#!/bin/bash` → `"bash"` - `#!/usr/bin/env
     * node` → `"javascript"`
     *
     * The `-S` flag accepted by some `env` implementations is skipped automatically. Version suffixes (e.g.
     * `python3.11`, `ruby3.2`) are stripped before matching.
     *
     * Returns `None` when content does not start with `#!`, the shebang is malformed, or the interpreter is not
     * recognised.
     *
     * ``` use tree_sitter_language_pack::detect_language_from_content;
     * assert_eq!(detect_language_from_content("#!/usr/bin/env python3\npass"), Some("python"));
     * assert_eq!(detect_language_from_content("#!/bin/bash\necho hi"), Some("bash"));
     * assert_eq!(detect_language_from_content("no shebang here"), None); ```
     */
    public static String detectLanguageFromContent(final String content) throws TreeSitterLanguagePackRsException {
        java.util.Objects.requireNonNull(content, "content must not be null");
        return TreeSitterLanguagePackRs.detectLanguageFromContent(content).orElseThrow();
    }

    /**
     * Get the highlights query for a language, if bundled.
     *
     * Returns the contents of `highlights.scm` as a static string, or `None` if no highlights query is bundled for this
     * language.
     *
     * # Example
     *
     * ``` use tree_sitter_language_pack::get_highlights_query;
     *
     * // Returns Some(...) for languages with bundled queries let query = get_highlights_query("python"); // Returns
     * None for languages without bundled highlights queries let missing = get_highlights_query("nonexistent_lang");
     * assert!(missing.is_none()); ```
     */
    public static String getHighlightsQuery(final String language) throws TreeSitterLanguagePackRsException {
        java.util.Objects.requireNonNull(language, "language must not be null");
        return TreeSitterLanguagePackRs.getHighlightsQuery(language).orElseThrow();
    }

    /**
     * Get the injections query for a language, if bundled.
     *
     * Returns the contents of `injections.scm` as a static string, or `None` if no injections query is bundled for this
     * language.
     *
     * # Example
     *
     * ``` use tree_sitter_language_pack::get_injections_query;
     *
     * let query = get_injections_query("markdown"); // Returns None for languages without bundled injections queries
     * let missing = get_injections_query("nonexistent_lang"); assert!(missing.is_none()); ```
     */
    public static String getInjectionsQuery(final String language) throws TreeSitterLanguagePackRsException {
        java.util.Objects.requireNonNull(language, "language must not be null");
        return TreeSitterLanguagePackRs.getInjectionsQuery(language).orElseThrow();
    }

    /**
     * Get the locals query for a language, if bundled.
     *
     * Returns the contents of `locals.scm` as a static string, or `None` if no locals query is bundled for this
     * language.
     *
     * # Example
     *
     * ``` use tree_sitter_language_pack::get_locals_query;
     *
     * let query = get_locals_query("python"); // Returns None for languages without bundled locals queries let missing
     * = get_locals_query("nonexistent_lang"); assert!(missing.is_none()); ```
     */
    public static String getLocalsQuery(final String language) throws TreeSitterLanguagePackRsException {
        java.util.Objects.requireNonNull(language, "language must not be null");
        return TreeSitterLanguagePackRs.getLocalsQuery(language).orElseThrow();
    }

    /**
     * Get a tree-sitter [`Language`] by name using the global registry.
     *
     * Resolves language aliases (e.g., `"shell"` maps to `"bash"`). When the `download` feature is enabled (default),
     * automatically downloads the parser from GitHub releases if not found locally.
     *
     * # Errors
     *
     * Returns [`Error::LanguageNotFound`] if the language is not recognized, or [`Error::Download`] if auto-download
     * fails.
     *
     * # Example
     *
     * ```no_run use tree_sitter_language_pack::get_language;
     *
     * let lang = get_language("python").unwrap(); // Use the Language with a tree-sitter Parser let mut parser =
     * tree_sitter::Parser::new(); parser.set_language(&lang).unwrap(); let tree = parser.parse("x = 1", None).unwrap();
     * assert_eq!(tree.root_node().kind(), "module"); ```
     */
    public static Language getLanguage(final String name) throws TreeSitterLanguagePackRsException {
        java.util.Objects.requireNonNull(name, "name must not be null");
        return TreeSitterLanguagePackRs.getLanguage(name);
    }

    /**
     * Get a tree-sitter [`Parser`] pre-configured for the given language.
     *
     * This is a convenience function that calls [`get_language`] and configures a new parser in one step.
     *
     * # Errors
     *
     * Returns [`Error::LanguageNotFound`] if the language is not recognized, or [`Error::ParserSetup`] if the language
     * cannot be applied to the parser.
     *
     * # Example
     *
     * ```no_run use tree_sitter_language_pack::get_parser;
     *
     * let mut parser = get_parser("rust").unwrap(); let tree = parser.parse("fn main() {}", None).unwrap();
     * assert!(!tree.root_node().has_error()); ```
     */
    public static Parser getParser(final String name) throws TreeSitterLanguagePackRsException {
        java.util.Objects.requireNonNull(name, "name must not be null");
        return TreeSitterLanguagePackRs.getParser(name);
    }

    /**
     * Detect language name from a file path or extension.
     *
     * This compatibility alias matches the pre-Alef Python binding API.
     */
    public static String detectLanguage(final String path) throws TreeSitterLanguagePackRsException {
        java.util.Objects.requireNonNull(path, "path must not be null");
        return TreeSitterLanguagePackRs.detectLanguage(path).orElseThrow();
    }

    /**
     * List all available language names (sorted, deduplicated, includes aliases).
     *
     * Returns names of both statically compiled and dynamically loadable languages, plus any configured aliases.
     *
     * # Example
     *
     * ```no_run use tree_sitter_language_pack::available_languages;
     *
     * let langs = available_languages(); for name in &langs { println!("{}", name); } ```
     */
    public static List<String> availableLanguages() throws TreeSitterLanguagePackRsException {
        return TreeSitterLanguagePackRs.availableLanguages();
    }

    /**
     * Check if a language is available by name or alias.
     *
     * Returns `true` if the language can be loaded (statically compiled, dynamically available, or a known alias for
     * one of these).
     *
     * # Example
     *
     * ```no_run use tree_sitter_language_pack::has_language;
     *
     * assert!(has_language("python")); assert!(has_language("shell")); // alias for "bash"
     * assert!(!has_language("nonexistent_language")); ```
     */
    public static boolean hasLanguage(final String name) throws TreeSitterLanguagePackRsException {
        java.util.Objects.requireNonNull(name, "name must not be null");
        return TreeSitterLanguagePackRs.hasLanguage(name);
    }

    /**
     * Return the number of available languages.
     *
     * Includes statically compiled languages, dynamically loadable languages, and aliases.
     *
     * # Example
     *
     * ```no_run use tree_sitter_language_pack::language_count;
     *
     * let count = language_count(); println!("{} languages available", count); ```
     */
    public static long languageCount() throws TreeSitterLanguagePackRsException {
        return TreeSitterLanguagePackRs.languageCount();
    }

    /**
     * Process source code and extract file intelligence using the global registry.
     *
     * Parses the source with tree-sitter and extracts metrics, structure, imports, exports, comments, docstrings,
     * symbols, diagnostics, and/or chunks based on the flags set in [`ProcessConfig`].
     *
     * # Errors
     *
     * Returns an error if the language is not found or parsing fails.
     *
     * # Example
     *
     * ```no_run use tree_sitter_language_pack::{ProcessConfig, process};
     *
     * let config = ProcessConfig::new("python").all(); let result = process("def hello(): pass", &config).unwrap();
     * println!("Language: {}", result.language); println!("Lines: {}", result.metrics.total_lines);
     * println!("Structures: {}", result.structure.len()); ```
     */
    public static ProcessResult process(final String source, final ProcessConfig config)
            throws TreeSitterLanguagePackRsException {
        java.util.Objects.requireNonNull(source, "source must not be null");
        java.util.Objects.requireNonNull(config, "config must not be null");
        return TreeSitterLanguagePackRs.process(source, config);
    }

    /**
     * Initialize the language pack with the given configuration.
     *
     * Applies any custom cache directory, then downloads all languages and groups specified in the config. This is the
     * recommended entry point when you want to pre-warm the cache before use.
     *
     * # Errors
     *
     * Returns an error if configuration cannot be applied or if downloads fail.
     *
     * # Example
     *
     * ```no_run use tree_sitter_language_pack::{PackConfig, init};
     *
     * let config = PackConfig { cache_dir: None, languages: Some(vec!["python".to_string(), "rust".to_string()]),
     * groups: None, }; init(&config).unwrap(); ```
     */
    public static void init(final PackConfig config) throws TreeSitterLanguagePackRsException {
        java.util.Objects.requireNonNull(config, "config must not be null");
        TreeSitterLanguagePackRs.init(config);
    }

    /**
     * Apply download configuration without downloading anything.
     *
     * Use this to set a custom cache directory before the first call to [`get_language`] or any download function.
     * Changing the cache dir after languages have been registered has no effect on already-loaded languages.
     *
     * # Errors
     *
     * Returns an error if the lock cannot be acquired.
     *
     * # Example
     *
     * ```no_run use std::path::PathBuf; use tree_sitter_language_pack::{PackConfig, configure};
     *
     * let config = PackConfig { cache_dir: Some(PathBuf::from("/tmp/my-parsers")), languages: None, groups: None, };
     * configure(&config).unwrap(); ```
     */
    public static void configure(final PackConfig config) throws TreeSitterLanguagePackRsException {
        java.util.Objects.requireNonNull(config, "config must not be null");
        TreeSitterLanguagePackRs.configure(config);
    }

    /**
     * Download specific languages to the local cache.
     *
     * Returns the number of requested languages available after the call. Already compiled or cached languages are
     * included in the count.
     *
     * # Errors
     *
     * Returns an error if any language is not available in the manifest or if the download fails.
     *
     * # Example
     *
     * ```no_run use tree_sitter_language_pack::download;
     *
     * let count = download(&["python", "rust", "typescript"]).unwrap(); println!("Ensured {} languages", count); ```
     */
    public static long download(final List<String> names) throws TreeSitterLanguagePackRsException {
        java.util.Objects.requireNonNull(names, "names must not be null");
        return TreeSitterLanguagePackRs.download(names);
    }

    /**
     * Download all available languages from the remote manifest.
     *
     * Returns the number of manifest languages available after the call.
     *
     * # Errors
     *
     * Returns an error if the manifest cannot be fetched or a download fails.
     *
     * # Example
     *
     * ```no_run use tree_sitter_language_pack::download_all;
     *
     * let count = download_all().unwrap(); println!("Downloaded {} languages", count); ```
     */
    public static long downloadAll() throws TreeSitterLanguagePackRsException {
        return TreeSitterLanguagePackRs.downloadAll();
    }

    /**
     * Return all language names available in the remote manifest (305).
     *
     * Fetches (and caches) the remote manifest to discover the full list of downloadable languages. Use
     * [`downloaded_languages`] to list what is already cached locally.
     *
     * # Errors
     *
     * Returns an error if the manifest cannot be fetched.
     *
     * # Example
     *
     * ```no_run use tree_sitter_language_pack::manifest_languages;
     *
     * let langs = manifest_languages().unwrap(); println!("{} languages available for download", langs.len()); ```
     */
    public static List<String> manifestLanguages() throws TreeSitterLanguagePackRsException {
        return TreeSitterLanguagePackRs.manifestLanguages();
    }

    /**
     * Return languages that are already downloaded and cached locally.
     *
     * Does not perform any network requests. Returns an empty list if the cache directory does not exist or cannot be
     * read.
     *
     * # Example
     *
     * ```no_run use tree_sitter_language_pack::downloaded_languages;
     *
     * let langs = downloaded_languages(); println!("{} languages already cached", langs.len()); ```
     */
    public static List<String> downloadedLanguages() throws TreeSitterLanguagePackRsException {
        return TreeSitterLanguagePackRs.downloadedLanguages();
    }

    /**
     * Delete all cached parser shared libraries.
     *
     * Resets the cache registration so the next call to [`get_language`] or a download function will re-register the
     * (now empty) cache directory.
     *
     * # Errors
     *
     * Returns an error if the cache directory cannot be removed.
     *
     * # Example
     *
     * ```no_run use tree_sitter_language_pack::clean_cache;
     *
     * clean_cache().unwrap(); println!("Cache cleared"); ```
     */
    public static void cleanCache() throws TreeSitterLanguagePackRsException {
        TreeSitterLanguagePackRs.cleanCache();
    }

    /**
     * Return the effective cache directory path.
     *
     * This is either the custom path set via [`configure`] / [`init`] or the default:
     * `~/.cache/tree-sitter-language-pack/v{version}/libs/`.
     *
     * # Errors
     *
     * Returns an error if the system cache directory cannot be determined.
     *
     * # Example
     *
     * ```no_run use tree_sitter_language_pack::cache_dir;
     *
     * let dir = cache_dir().unwrap(); println!("Cache directory: {}", dir.display()); ```
     */
    public static java.nio.file.Path cacheDir() throws TreeSitterLanguagePackRsException {
        return TreeSitterLanguagePackRs.cacheDir();
    }

}
