// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:eafdd9d7178a2638060ef75fbdbbd878f44de4d095f40339ca9dc8f615f707ed
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.treesitterlanguagepack;

/** Exception thrown by TreeSitterLanguagePackRs. */
@SuppressWarnings("checkstyle:LineLength")
public class TreeSitterLanguagePackRsException extends Exception {
    /** The error code. */
    private final int code;

    /** Creates a new TreeSitterLanguagePackRsException. */
    public TreeSitterLanguagePackRsException(final int code, final String message) {
        super(message);
        this.code = code;
    }

    /** Creates a new TreeSitterLanguagePackRsException with a cause. */
    public TreeSitterLanguagePackRsException(final String message, final Throwable cause) {
        super(message, cause);
        this.code = -1;
    }

    /** Returns the error code. */
    public int getCode() {
        return code;
    }
}
