// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a82135566a214844165e530b714647cb2e03b40fee53cb69e087b9ab3d913e17
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack;

import java.lang.foreign.MemorySegment;

public class Tree implements AutoCloseable {
    private final MemorySegment handle;

    Tree(MemorySegment handle) {
        this.handle = handle;
    }

    MemorySegment handle() {
        return this.handle;
    }

    @Override
    public void close() {
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                NativeLib.TS_PACK_TREE_FREE.invoke(handle);
            } catch (Throwable e) {
                throw new RuntimeException("Failed to free Tree: " + e.getMessage(), e);
            }
        }
    }
}
