// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:44a0d5babc63706f84f2e19d48cf948b55c87cbbe3e341ee15c08a54f4d42d8f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.treesitterlanguagepack;

/** Exception thrown by TreeSitterLanguagePackRs. */
@SuppressWarnings("checkstyle:LineLength")
public class TreeSitterLanguagePackRsException extends Exception {
    /** The error code. */
    private final int code;

    /** Creates a new TreeSitterLanguagePackRsException. */
    public TreeSitterLanguagePackRsException(final int code, final String message) {
        super(message);
        this.code = code;
    }

    /** Creates a new TreeSitterLanguagePackRsException with a cause. */
    public TreeSitterLanguagePackRsException(final String message, final Throwable cause) {
        super(message, cause);
        this.code = -1;
    }

    /** Returns the error code. */
    public int getCode() {
        return code;
    }
}
