// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:73d6ebd2ae99bfcd45abf84aa28e1ed6136847bdc9242fcda7f9ab26367c3320
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.treesitterlanguagepack;

/** Exception thrown by TreeSitterLanguagePackRs. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class TreeSitterLanguagePackRsException extends Exception {
  /** The error code. */
  private final int code;

  /** Creates a new TreeSitterLanguagePackRsException. */
  public TreeSitterLanguagePackRsException(final int code, final String message) {
    super(message);
    this.code = code;
  }

  /** Creates a new TreeSitterLanguagePackRsException with a cause. */
  public TreeSitterLanguagePackRsException(final String message, final Throwable cause) {
    super(message, cause);
    this.code = -1;
  }

  /** Returns the error code. */
  public int getCode() {
    return code;
  }
}
