# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7bec16f5c828b57399dc70e8709c84b136820496848b19e2e73499bff909745b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
"""Exception hierarchy."""


class Error(Exception):
    """Errors that can occur when using the tree-sitter language pack."""


class LanguageNotFoundError(Error):
    """Language not found error."""


class DynamicLoadError(Error):
    """Dynamic load error."""


class NullLanguagePointerError(Error):
    """Null language pointer error."""


class ParserSetupError(Error):
    """Parser setup error."""


class LockPoisonedError(Error):
    """Lock poisoned error."""


class ConfigError(Error):
    """Config error."""


class ParseFailedError(Error):
    """Parse failed error."""


class QueryError(Error):
    """Query error."""


class InvalidRangeError(Error):
    """Invalid range error."""


class IoError(Error):
    """Io error."""


class DownloadError(Error):
    """Download error."""


class ChecksumMismatchError(Error):
    """Checksum mismatch error."""


class CacheLockError(Error):
    """Cache lock error."""
