# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ce4d60d13e87a19e6d25e5d034592431a73190f38f3cc8d3838b813ec738bca7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""Exception hierarchy."""


class Error(Exception):
    """Errors that can occur when using the tree-sitter language pack."""


class LanguageNotFoundError(Error):
    """Language not found error."""


class DynamicLoadError(Error):
    """Dynamic load error."""


class NullLanguagePointerError(Error):
    """Null language pointer error."""


class ParserSetupError(Error):
    """Parser setup error."""


class LockPoisonedError(Error):
    """Lock poisoned error."""


class ConfigError(Error):
    """Config error."""


class ParseFailedError(Error):
    """Parse failed error."""


class QueryError(Error):
    """Query error."""


class InvalidRangeError(Error):
    """Invalid range error."""


class IoError(Error):
    """Io error."""
