<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0a134ecf571c508ef5b18caab832cb9ed3c99e9b5f1bd7442d4c7d533f4eda2d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Tree\Sitter\Language\Pack\TreeSitterLanguagePack;

/** E2e tests for category: query. */
final class QueryTest extends TestCase
{
    /** Get highlights query for nonexistent language returns null/empty */
    public function test_highlights_nonexistent_language(): void
    {
        $result = TreeSitterLanguagePack::get_highlights_query("zzz_nonexistent_lang");
        $this->assertEmpty($result);
    }

    /** get_highlights_query returns non-empty string for rust */
    public function test_highlights_query_rust(): void
    {
        $result = TreeSitterLanguagePack::get_highlights_query("rust");
        $this->assertNotEmpty($result);
    }

    /** get_highlights_query returns None for unknown language */
    public function test_highlights_query_unknown_language(): void
    {
        $result = TreeSitterLanguagePack::get_highlights_query("nonexistent_language_xyz");
        $this->assertEmpty($result);
    }

    /** get_injections_query returns non-empty for rust */
    public function test_injections_query_rust(): void
    {
        $result = TreeSitterLanguagePack::get_injections_query("rust");
        $this->assertNotEmpty($result);
    }

    /** get_injections_query returns empty for unknown language */
    public function test_injections_query_unknown_language(): void
    {
        $result = TreeSitterLanguagePack::get_injections_query("nonexistent_xyz");
        $this->assertEmpty($result);
    }

    /** get_locals_query returns non-empty for cue */
    public function test_locals_query_cue(): void
    {
        $result = TreeSitterLanguagePack::get_locals_query("cue");
        $this->assertNotEmpty($result);
    }

    /** get_locals_query returns empty for unknown language */
    public function test_locals_query_unknown_language(): void
    {
        $result = TreeSitterLanguagePack::get_locals_query("nonexistent_xyz");
        $this->assertEmpty($result);
    }
}
