// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8e6b60fdb22a27e2f51a6dd18bffcfb22706f9892d9a8d350deea54c0df67828
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 30000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
	},
});
