# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9b05b8528d7b0e735631899341f0a83000e10962ff05ab310c5c396058c2e79c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

module Tree_sitter_language_pack
  VERSION = '1.8.0.pre.rc.41'
end
