# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8f204f632b6b6c86df0b776b3d83ace89acb10fee632ffe9c91e5162c27a8dc2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

module Tree_sitter_language_pack
  VERSION = "1.8.0.pre.rc.26"
end
