# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:208fec95d1edffe207b8be8a4b7382f16c3c9578bd1db6a8af3b334daa9cb5c0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

module Tree_sitter_language_pack
  VERSION = '1.8.0.pre.rc.37'
end
