// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:de3a445dcb22e47815960533bc602f67d05a8b03f833c4ac0ab7f33fd34066b1
fn main() {
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    cbindgen::generate(crate_dir)
        .expect("Unable to generate C bindings")
        .write_to_file("include/ts_pack.h");
}
