// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:44a0d5babc63706f84f2e19d48cf948b55c87cbbe3e341ee15c08a54f4d42d8f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
const std = @import("std");
const testing = std.testing;
const tree_sitter_language_pack = @import("tree_sitter_language_pack");

// Suppress C++ global destructor aborts that break zig's --listen=- IPC
extern "c" fn signal(sig: i32, handler: usize) usize;
var _abort_handler_installed: bool = false;
fn suppress_abort() void {
    if (!_abort_handler_installed) {
        // SIGABRT = 6 on POSIX; SIG_IGN = 1
        _ = signal(6, 1);
        _abort_handler_installed = true;
    }
}

// E2e tests for category: query

test "highlights_query_rust" {
    // get_highlights_query returns non-empty string for rust
    suppress_abort();
    const result = try tree_sitter_language_pack.get_highlights_query("rust");
    try testing.expect(result != null);
}

test "injections_query_rust" {
    // get_injections_query returns non-empty for rust
    suppress_abort();
    const result = try tree_sitter_language_pack.get_injections_query("rust");
    try testing.expect(result != null);
}
