<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4fd28d28be5d5c08a42b1adaeb8565a890c281118692f20fb4e08cfac6ad7fcf
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
declare(strict_types=1);

namespace Tree\Sitter\Language\Pack;

/**
 * Manages downloading and caching of pre-built parser shared libraries.
 */
final class DownloadManager
{
    /**
     * List languages that are already downloaded and cached.
     * @return array<string>
     */
    public function installedLanguages(): array
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
    /**
     * Download the platform bundle and extract every library file it contains.
     */
    public function downloadAllBestEffort(): int
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
    /**
     * Remove all cached parser libraries.
     */
    public function cleanCache(): void
    {
    }
    /**
     * Create a new download manager for the given version.
     */
    public static function new(string $version): DownloadManager
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
}
