<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:75f9fdfbf3b6ada898acef5b8762a3958472df8ac798b8aa1fb5bd2fba2d5f1f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef
declare(strict_types=1);

namespace Tree\Sitter\Language\Pack;

/**
 * Manages downloading and caching of pre-built parser shared libraries.
 */
final class DownloadManager
{
    /**
     * List languages that are already downloaded and cached.
     * @return array<string>
     */
    public function installedLanguages(): array
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
    /**
     * Download the platform bundle and extract every library file it contains.
     */
    public function downloadAllBestEffort(): int
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
    /**
     * Remove all cached parser libraries.
     */
    public function cleanCache(): void
    {
    }
    /**
     * Create a new download manager for the given version.
     */
    public static function new(string $version): DownloadManager
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
    /**
     * Create a download manager with a custom cache directory.
     */
    public static function withCacheDir(string $version, string $cache_dir): DownloadManager
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
}
