<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f1b49da8b8d934eb13d7453e1cf4e27ae81c6449e165f6addb8ebe5d308bab59
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
declare(strict_types=1);

namespace Tree\Sitter\Language\Pack;

final class Language
{
}
