<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:75f9fdfbf3b6ada898acef5b8762a3958472df8ac798b8aa1fb5bd2fba2d5f1f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef
declare(strict_types=1);

namespace Tree\Sitter\Language\Pack;

/**
 * A tree-sitter parser configured for one language at a time.
 *
 * # Example
 */
final class Parser
{
    /**
     * Configure the parser to use the language identified by name (e.g. `"python"`).
     */
    public function setLanguage(string $name): void
    {
    }
    /**
     * Parse a UTF-8 source string. Returns `None` if parsing was cancelled
     */
    public function parse(string $source): ?Tree
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
    /**
     * Parse a raw byte slice. Returns `None` if parsing was cancelled or
     */
    public function parseBytes(string $source): ?Tree
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
    /**
     * Reset internal state. The next call to `parse`(Self.parse) will
     */
    public function reset(): void
    {
    }
    public static function default(): Parser
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
}
