// Generated by alef. Imports the full tree_sitter_language_pack API.
// alef:hash:4fd28d28be5d5c08a42b1adaeb8565a890c281118692f20fb4e08cfac6ad7fcf
pub const api = @import("tree_sitter_language_pack.zig");
