// Generated by alef. Imports the full tree_sitter_language_pack API.
// alef:hash:ba3d64f1bdbc733556a596b2718817609290c351656742357e98689aba93f174
pub const api = @import("tree_sitter_language_pack.zig");
