// Generated by alef. Imports the full tree_sitter_language_pack API.
// alef:hash:6125571a3e8d71b1bf26c8a105b8f42f97acba36088cabe6d2ac4064fef4370d
pub const api = @import("tree_sitter_language_pack.zig");
