# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7385ddff499bfd653e3dc1c08b8ada744dc611a13f7086ea02ee1a1dd1416b56
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
"""Pytest configuration for e2e tests."""
# Ensure the package is importable.
# The tree_sitter_language_pack package is expected to be installed in the current environment.
