# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:eafdd9d7178a2638060ef75fbdbbd878f44de4d095f40339ca9dc8f615f707ed
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
"""Pytest configuration for e2e tests."""
# Ensure the package is importable.
# The tree_sitter_language_pack package is expected to be installed in the current environment.
