# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6125571a3e8d71b1bf26c8a105b8f42f97acba36088cabe6d2ac4064fef4370d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require_relative "tree_sitter_language_pack/version"
require_relative "tree_sitter_language_pack/native"

# Top-level namespace for the TreeSitterLanguagePack Ruby binding.
#
# All type and function symbols are re-exported from the native extension
# loaded via `require_relative "tree_sitter_language_pack/native"`. See
# {file:README.md} for usage examples and the upstream documentation
# for the full API reference.
module TreeSitterLanguagePack
  # Re-export all types and functions from native extension
end
