# Generated by alef. Do not edit by hand.
# alef:hash:cf84eb383aae226537d4dfbf11634379392a6f7ee6eaead589726b5e5d31f75e
# Keep generated public API for consumers using R8/ProGuard.
-keep class dev.kreuzberg.tslp.android.** { *; }
