# Generated by alef. Do not edit by hand.
# alef:hash:7385ddff499bfd653e3dc1c08b8ada744dc611a13f7086ea02ee1a1dd1416b56
# Keep generated public API for consumers using R8/ProGuard.
-keep class dev.kreuzberg.tslp.android.** { *; }
