// Generated by alef. Do not edit by hand.
// alef:hash:8e6b60fdb22a27e2f51a6dd18bffcfb22706f9892d9a8d350deea54c0df67828

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.7.0"
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "tree-sitter-language-pack-android"
