// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0a50ad54a699f207891f94d4615ab8767e07ce826b42a612b02acff54e902c48
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 30000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
	},
});
