// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b48f13445b460aa01ad772e5ff17caf1937ac7b59a36097edb275fd7ac8deac6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 30000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
	},
});
