// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:44bf370dc28fc7bcdb3c87c19256c2f869ee3ad3cbf23b099fe87eb219d7b161
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 30000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
	},
});
