// Generated by alef. Do not edit by hand.

package dev.kreuzberg.tslp.android

/**
 * A byte range — start (inclusive) to end (exclusive).
 */
data class ByteRange(
    /**
     * Inclusive start byte offset.
     */
    val start: Long,
    /**
     * Exclusive end byte offset.
     */
    val end: Long,
)
