// Generated by alef. Do not edit by hand.
// alef:hash:48eaa6aee6a9621260908f86b470f0394ca8594aea6b158a71425b92dd28df38
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
)

package dev.kreuzberg.tslp.android

/** A section within a docstring (e.g., Args, Returns, Raises). */
data class DocSection(
    /** Section kind (e.g., `"args"`, `"returns"`, `"raises"`). */
    val kind: String = "",
    /** Parameter or return value name, if applicable. */
    val name: String? = null,
    /** Description text for this section. */
    val description: String = "",
)
