// Generated by alef. Do not edit by hand.

package dev.kreuzberg.tslp.android

/** JNI-backed wrapper holding a native `Language` handle. */
class Language internal constructor(internal val handle: Long) : AutoCloseable {
    override fun close() {
        TreeSitterLanguagePackBridge.nativeFreeLanguage(handle)
    }
}
