// Generated by alef. Do not edit by hand.
// alef:hash:360e02edf70c86e2e1a835db7f366f6b66fdd0a250df7395639cdaa155a85d21

package dev.kreuzberg.tslp.android

class TreeSitterLanguagePackBridgeException(message: String?, cause: Throwable?) :
    RuntimeException(message, cause) {
    constructor(message: String?) : this(message, null)
}
