// Generated by alef. Do not edit by hand.
// alef:hash:73d6ebd2ae99bfcd45abf84aa28e1ed6136847bdc9242fcda7f9ab26367c3320

package dev.kreuzberg.tslp.android

class TreeSitterLanguagePackBridgeException(message: String?, cause: Throwable?) :
    RuntimeException(message, cause) {
    constructor(message: String?) : this(message, null)
}
