// Generated by alef. Do not edit by hand.
// alef:hash:fdaedbc30d45f59f128e477ac54794046794ad0608ac245915e5e9bd7fbac89f

// Traits module (empty in Dart as Dart does not have trait systems like Rust).
// This file is kept for API surface consistency across language bindings.
