// Generated by alef. Do not edit by hand.
// alef:hash:8e6b60fdb22a27e2f51a6dd18bffcfb22706f9892d9a8d350deea54c0df67828

// Traits module (empty in Dart as Dart does not have trait systems like Rust).
// This file is kept for API surface consistency across language bindings.
