// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5ee4d98439c51ef19a5100f330fbba555bc0a4b5e12af2ebb695d74df17dd0ab
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.treesitterlanguagepack.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.treesitterlanguagepack.TreeSitterLanguagePack;
import dev.kreuzberg.treesitterlanguagepack.PackConfig;
import dev.kreuzberg.treesitterlanguagepack.ProcessConfig;
import java.util.Optional;

/** E2e tests for category: download. */
class DownloadTest {
    @Test
    void testDownloadCacheDir() throws Exception {
        // Get the cache directory path and verify it is non-empty
        var result = TreeSitterLanguagePack.cacheDir();
        assertFalse(result == null || result.isEmpty(), "expected non-empty value");
    }

    @Test
    void testDownloadCleanCache() throws Exception {
        // Clean the parser cache directory
        TreeSitterLanguagePack.cleanCache();
    }

    @Test
    void testDownloadDownloadedEmpty() throws Exception {
        // List downloaded languages (may be empty before any downloads)
        var result = TreeSitterLanguagePack.downloadedLanguages();
    }

    @Test
    void testDownloadInitDefault() throws Exception {
        // Initialize language pack with default config
        var config = PackConfig.builder().build();
        TreeSitterLanguagePack.init(config);
    }

    @Test
    void testDownloadManifestLanguages() throws Exception {
        // List manifest languages and verify the full downloadable catalog
        var result = TreeSitterLanguagePack.manifestLanguages();
        assertFalse(result == null || result.isEmpty(), "expected non-empty value");
        assertTrue(result.size() >= 300, "expected at least 300 elements");
        assertTrue(result.contains("python"), "expected to contain: " + "python");
    }

    @Test
    void testDownloadSingleLanguage() throws Exception {
        // Download a single language parser and verify count
        var result = TreeSitterLanguagePack.download(java.util.List.of("python"));
        assertTrue(result >= 1, "expected >= 1");
    }

}
