// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:48eaa6aee6a9621260908f86b470f0394ca8594aea6b158a71425b92dd28df38
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TreeSitterLanguagePack;

/// <summary>
/// A byte range — start (inclusive) to end (exclusive).
/// </summary>
public sealed record ByteRange
{
    /// <summary>
    /// Inclusive start byte offset.
    /// </summary>
    [JsonPropertyName("start")]
    public ulong Start { get; init; } = 0;

    /// <summary>
    /// Exclusive end byte offset.
    /// </summary>
    [JsonPropertyName("end")]
    public ulong End { get; init; } = 0;


    /// <summary>
    /// Parse a <see cref="ByteRange"/> from a JSON string.
    /// </summary>
    /// <exception cref="TreeSitterLanguagePackException">When the JSON cannot be deserialised.</exception>
    public static ByteRange FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<ByteRange>(json, JsonOptions)
                ?? throw new TreeSitterLanguagePackException($"Failed to parse ByteRange from JSON: deserializer returned null");
        }
        catch (TreeSitterLanguagePackException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new TreeSitterLanguagePackException($"Failed to parse ByteRange from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
