// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:fdaedbc30d45f59f128e477ac54794046794ad0608ac245915e5e9bd7fbac89f
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// The cross-process download cache lock file could not be acquired or created.
/// </summary>
public class CacheLockException : ErrorException
{
    public CacheLockException(string message) : base(message) { }

    public CacheLockException(string message, Exception innerException) : base(message, innerException) { }
}
