// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:48eaa6aee6a9621260908f86b470f0394ca8594aea6b158a71425b92dd28df38
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// The downloaded file's SHA-256 digest did not match the manifest's expected value.
/// </summary>
public class ChecksumMismatchException : ErrorException
{
    public ChecksumMismatchException(string message) : base(message) { }

    public ChecksumMismatchException(string message, Exception innerException) : base(message, innerException) { }
}
