// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ba3d64f1bdbc733556a596b2718817609290c351656742357e98689aba93f174
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// The downloaded file's SHA-256 digest did not match the manifest's expected value.
/// </summary>
public class ChecksumMismatchException : ErrorException
{
    public ChecksumMismatchException(string message) : base(message) { }

    public ChecksumMismatchException(string message, Exception innerException) : base(message, innerException) { }
}
