// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:333f88b4b61a5b1425a00e611d05fbc259017f78f48e360642d3ed2f46d378bb
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TreeSitterLanguagePack;
/// <summary>/// The kind of a comment found in source code./// /// Distinguishes between single-line comments, block (multi-line) comments,/// and documentation comments./// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum CommentKind
{
    [JsonPropertyName("line")]
    Line, [JsonPropertyName("block")]
    Block, [JsonPropertyName("doc")]
    Doc,
}
