// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8936e25a01088cfabea396404d811986086c5bd4f79fc9734d28d6157271e356
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TreeSitterLanguagePack;
/// <summary>
/// The kind of a comment found in source code.
///
/// Distinguishes between single-line comments, block (multi-line) comments,
/// and documentation comments.
/// </summary>
[JsonConverter(typeof(CommentKindJsonConverter))]
public enum CommentKind
{
    [JsonPropertyName("line")]
    Line, [JsonPropertyName("block")]
    Block, [JsonPropertyName("doc")]
    Doc,
}


/// <summary>Custom JSON converter for <see cref="CommentKind"/> that respects explicit variant names.</summary>
internal sealed class CommentKindJsonConverter : JsonConverter<CommentKind>
{
    public override CommentKind Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return value switch
        {
            "line" => CommentKind.Line,
            "block" => CommentKind.Block,
            "doc" => CommentKind.Doc,
            _ => throw new JsonException($"Unknown CommentKind value: {value}")
        };
    }

    public override void Write(Utf8JsonWriter writer, CommentKind value, JsonSerializerOptions options)
    {
        var str = value switch
        {
            CommentKind.Line => "line",
            CommentKind.Block => "block",
            CommentKind.Doc => "doc",
            _ => throw new JsonException($"Unknown CommentKind value: {value}")
        };
        writer.WriteStringValue(str);
    }
}
