// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d74eea0398c6d44e34b17f930d85eb2eab2767fab08cfc3da5ca0d29cea902dd
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TreeSitterLanguagePack;

/// <summary>
/// A comment extracted from source code.
/// </summary>
public sealed class CommentInfo
{
    [JsonPropertyName("text")]
    public string Text { get; set; } = "";

    [JsonPropertyName("kind")]
    public CommentKind? Kind { get; set; } = null;

    [JsonPropertyName("span")]
    public Span Span { get; set; } = default!;

    [JsonPropertyName("associated_node")]
    public string? AssociatedNode { get; set; } = null;

}
