// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:954201776048759980ae98835633f18bae90819ab92ca042b787bdb1ed512fb5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace TreeSitterLanguagePack;

/// <summary>
/// The kind of a comment found in source code.
///
/// Distinguishes between single-line comments, block (multi-line) comments,
/// and documentation comments.
/// </summary>
public enum CommentKind
{
    [JsonPropertyName("line")]
    Line,
    [JsonPropertyName("block")]
    Block,
    [JsonPropertyName("doc")]
    Doc,
}
