// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:cf84eb383aae226537d4dfbf11634379392a6f7ee6eaead589726b5e5d31f75e
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// A configuration file or value was invalid or could not be applied.
/// </summary>
public class ConfigException : ErrorException
{
    public ConfigException(string message) : base(message) { }

    public ConfigException(string message, Exception innerException) : base(message, innerException) { }
}
