// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7bec16f5c828b57399dc70e8709c84b136820496848b19e2e73499bff909745b
#nullable enable

using System;

namespace TreeSitterLanguagePack;

public class ConfigException : ErrorException
{
    public ConfigException(string message) : base(message) { }

    public ConfigException(string message, Exception innerException) : base(message, innerException) { }
}
