// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:366e4c8ea9d7faf2f7f60323b445cf09d7d68f3d820d87ae297aed3b4a4fc643
#nullable enable

using System;

namespace TreeSitterLanguagePack;

public class ConfigException : ErrorException
{
    public ConfigException(string message) : base(message) { }

    public ConfigException(string message, Exception innerException) : base(message, innerException) { }
}
