// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:f076b060d538c79c54d8ca3918737f6a89b0edf533260d360d3325935d0f745d
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TreeSitterLanguagePack;
/// <summary>/// Severity level of a diagnostic produced during parsing./// /// Used to classify parse errors, warnings, and informational messages/// found in the syntax tree./// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum DiagnosticSeverity
{
    [JsonPropertyName("error")]
    Error, [JsonPropertyName("warning")]
    Warning, [JsonPropertyName("info")]
    Info,
}
