// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ef2582b1c5efe9198d52af5272964a35fa5d75167fb60e65be4d464630ee52a3
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TreeSitterLanguagePack;
/// <summary>/// Severity level of a diagnostic produced during parsing./// /// Used to classify parse errors, warnings, and informational messages/// found in the syntax tree./// </summary>
public enum DiagnosticSeverity
{[JsonPropertyName("error")]
    Error,[JsonPropertyName("warning")]
    Warning,[JsonPropertyName("info")]
    Info,}
