// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d412f5bc84dd26c08e61b3cf2553d76e194f2e887eadc1677d5d520a680a4b76
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TreeSitterLanguagePack;

/// <summary>
/// A section within a docstring (e.g., Args, Returns, Raises).
/// </summary>
public sealed class DocSection
{
    [JsonPropertyName("kind")]
    public string Kind { get; set; } = "";

    [JsonPropertyName("name")]
    public string? Name { get; set; } = null;

    [JsonPropertyName("description")]
    public string Description { get; set; } = "";

}
