// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:44a0d5babc63706f84f2e19d48cf948b55c87cbbe3e341ee15c08a54f4d42d8f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TreeSitterLanguagePack;

/// <summary>
/// A docstring extracted from source code.
/// </summary>
public sealed record DocstringInfo
{
    [JsonPropertyName("text")]
    public string Text { get; init; } = "";

    [JsonPropertyName("format")]
    public DocstringFormat? Format { get; init; } = null;

    [JsonPropertyName("span")]
    public Span Span { get; init; } = default!;

    [JsonPropertyName("associated_item")]
    public string? AssociatedItem { get; init; } = null;

    [JsonPropertyName("parsed_sections")]
    public List<DocSection> ParsedSections { get; init; } = [];


    /// <summary>
    /// Parse a <see cref="DocstringInfo"/> from a JSON string.
    /// </summary>
    /// <exception cref="TreeSitterLanguagePackException">When the JSON cannot be deserialised.</exception>
    public static DocstringInfo FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<DocstringInfo>(json, JsonOptions)
                ?? throw new TreeSitterLanguagePackException($"Failed to parse DocstringInfo from JSON: deserializer returned null");
        }
        catch (TreeSitterLanguagePackException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new TreeSitterLanguagePackException($"Failed to parse DocstringInfo from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };

    /// <summary>Options for serializing config/input objects to FFI. Strips nulls
    /// (nullable C# fields default to null and would override required Rust fields with
    /// non-deserialisable nulls) but preserves explicit false/0 so caller intent is kept.</summary>
    private static readonly JsonSerializerOptions JsonSerializationOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
