// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:257245a362608de2b2c9a9d0c3ee6771ffc4ac3f0ba4ea0d298281203313eace
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TreeSitterLanguagePack;
/// <summary>/// The format of a docstring extracted from source code./// /// Identifies the docstring convention used, which varies by language/// (e.g., Python triple-quoted strings, JSDoc, Rustdoc `///` comments)./// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum DocstringFormat
{
    [JsonPropertyName("pythontriplequote")]
    PythonTripleQuote, [JsonPropertyName("jsdoc")]
    JsDoc, [JsonPropertyName("rustdoc")]
    Rustdoc, [JsonPropertyName("godoc")]
    GoDoc, [JsonPropertyName("javadoc")]
    JavaDoc, [JsonPropertyName("other")]
    Other,
}
