// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:f1b49da8b8d934eb13d7453e1cf4e27ae81c6449e165f6addb8ebe5d308bab59
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// A dynamic shared library could not be loaded at runtime.
/// </summary>
public class DynamicLoadException : ErrorException
{
    public DynamicLoadException(string message) : base(message) { }

    public DynamicLoadException(string message, Exception innerException) : base(message, innerException) { }
}
