// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:2deeb1888cafa0076df8a141a89dacafbfb77ac46c3100ef4cefed7a325b2a9f
#nullable enable

using System;

namespace TreeSitterLanguagePack;

public class DynamicLoadException : ErrorException
{
    public DynamicLoadException(string message) : base(message) { }

    public DynamicLoadException(string message, Exception innerException) : base(message, innerException) { }
}
