// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:360e02edf70c86e2e1a835db7f366f6b66fdd0a250df7395639cdaa155a85d21
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// A dynamic shared library could not be loaded at runtime.
/// </summary>
public class DynamicLoadException : ErrorException
{
    public DynamicLoadException(string message) : base(message) { }

    public DynamicLoadException(string message, Exception innerException) : base(message, innerException) { }
}
