// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7bec16f5c828b57399dc70e8709c84b136820496848b19e2e73499bff909745b
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// Errors that can occur when using the tree-sitter language pack.
///
/// Covers language lookup failures, parse errors, query errors, and I/O issues.
/// Feature-gated variants are included when `config`, `download`, or related
/// features are enabled.
/// </summary>
public class ErrorException : TreeSitterLanguagePackException
{
    public ErrorException(string message) : base(message) { }

    public ErrorException(string message, Exception innerException) : base(message, innerException) { }
}
