// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:6125571a3e8d71b1bf26c8a105b8f42f97acba36088cabe6d2ac4064fef4370d
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// Errors that can occur when using the tree-sitter language pack.
///
/// Covers language lookup failures, parse errors, query errors, and I/O issues.
/// Feature-gated variants are included when `config`, `download`, or related
/// features are enabled.
/// </summary>
public class ErrorException : TreeSitterLanguagePackException
{
    public ErrorException(string message) : base(message) { }

    public ErrorException(string message, Exception innerException) : base(message, innerException) { }
}
