// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:366e4c8ea9d7faf2f7f60323b445cf09d7d68f3d820d87ae297aed3b4a4fc643
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TreeSitterLanguagePack;
/// <summary>
/// The kind of an export statement found in source code.
///
/// Covers named exports, default exports, and re-exports from other modules.
/// </summary>
[JsonConverter(typeof(ExportKindJsonConverter))]
public enum ExportKind
{
    [JsonPropertyName("Named")]
    Named,
    [JsonPropertyName("Default")]
    Default,
    [JsonPropertyName("ReExport")]
    ReExport,
}


/// <summary>
/// Custom JSON converter for <see cref="ExportKind"/> that respects explicit variant names.
/// </summary>
internal sealed class ExportKindJsonConverter : JsonConverter<ExportKind>
{
    public override ExportKind Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return value switch
        {
            "Named" => ExportKind.Named,
            "Default" => ExportKind.Default,
            "ReExport" => ExportKind.ReExport,
            _ => throw new JsonException($"Unknown ExportKind value: {value}")
        };
    }

    public override void Write(Utf8JsonWriter writer, ExportKind value, JsonSerializerOptions options)
    {
        var str = value switch
        {
            ExportKind.Named => "Named",
            ExportKind.Default => "Default",
            ExportKind.ReExport => "ReExport",
            _ => throw new JsonException($"Unknown ExportKind value: {value}")
        };
        writer.WriteStringValue(str);
    }
}
