// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ac9e822e37d13407ab5e2c565029091497db93eb9130f5af31c88c2142150fe7
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TreeSitterLanguagePack;
/// <summary>/// The kind of an export statement found in source code./// /// Covers named exports, default exports, and re-exports from other modules./// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ExportKind
{
    [JsonPropertyName("named")]
    Named, [JsonPropertyName("default")]
    Default, [JsonPropertyName("reexport")]
    ReExport,
}
