// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:9af2b8e19e1437af99a4f56df1a00bf23dd14119648e28fd32441421866a39fa
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TreeSitterLanguagePack;
/// <summary>/// The kind of an export statement found in source code./// /// Covers named exports, default exports, and re-exports from other modules./// </summary>
public enum ExportKind
{[JsonPropertyName("named")]
    Named,[JsonPropertyName("default")]
    Default,[JsonPropertyName("reexport")]
    ReExport,}
