// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:27a5a3bc0acb807e285c900cca18ee29f2b6f1520f956cc404ca564b7bdd96eb
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TreeSitterLanguagePack;

/// <summary>
/// An export statement extracted from source code.
/// </summary>
public sealed class ExportInfo
{
    [JsonPropertyName("name")]
    public string Name { get; set; } = "";

    [JsonPropertyName("kind")]
    public ExportKind? Kind { get; set; } = null;

    [JsonPropertyName("span")]
    public Span Span { get; set; } = default!;

}
