// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:eadcc1dc787c86b7a0687d16c6060e61dd2947f5ff657bf21ab85e0f089b3569
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TreeSitterLanguagePack;

/// <summary>
/// An export statement extracted from source code.
/// </summary>
public sealed class ExportInfo
{
    [JsonPropertyName("name")]
    public string Name { get; set; } = "";

    [JsonPropertyName("kind")]
    public ExportKind? Kind { get; set; } = null;

    [JsonPropertyName("span")]
    public Span Span { get; set; } = default!;


    /// <summary>
    /// Parse a <see cref="ExportInfo"/> from a JSON string.
    /// </summary>
    /// <exception cref="TreeSitterLanguagePackException">When the JSON cannot be deserialised.</exception>
    public static ExportInfo FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<ExportInfo>(json, JsonOptions)
                ?? throw new TreeSitterLanguagePackException($"Failed to parse ExportInfo from JSON: deserializer returned null");
        }
        catch (TreeSitterLanguagePackException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new TreeSitterLanguagePackException($"Failed to parse ExportInfo from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
