// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e8423cea08a631e7574a63b4bf7963eb66a76464826490068497f45e97d1bbb1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TreeSitterLanguagePack;

/// <summary>
/// An import statement extracted from source code.
/// </summary>
public sealed class ImportInfo
{
    [JsonPropertyName("source")]
    public string Source { get; set; } = "";

    [JsonPropertyName("items")]
    public List<string> Items { get; set; } = [];

    [JsonPropertyName("alias")]
    public string? Alias { get; set; } = null;

    [JsonPropertyName("is_wildcard")]
    public bool IsWildcard { get; set; } = false;

    [JsonPropertyName("span")]
    public Span Span { get; set; } = default!;

}
