// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:cf84eb383aae226537d4dfbf11634379392a6f7ee6eaead589726b5e5d31f75e
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// A byte range was invalid (e.g., end before start, or out of bounds).
/// </summary>
public class InvalidRangeException : ErrorException
{
    public InvalidRangeException(string message) : base(message) { }

    public InvalidRangeException(string message, Exception innerException) : base(message, innerException) { }
}
