// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:56f23c3c5922dca60d8da85814d3ea592b236e45ace64bdd6f2a16b59f4f83ff
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// A byte range was invalid (e.g., end before start, or out of bounds).
/// </summary>
public class InvalidRangeException : ErrorException
{
    public InvalidRangeException(string message) : base(message) { }

    public InvalidRangeException(string message, Exception innerException) : base(message, innerException) { }
}
