// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b48f13445b460aa01ad772e5ff17caf1937ac7b59a36097edb275fd7ac8deac6
#nullable enable

using System;

namespace TreeSitterLanguagePack;

public class InvalidRangeException : ErrorException
{
    public InvalidRangeException(string message) : base(message) { }

    public InvalidRangeException(string message, Exception innerException) : base(message, innerException) { }
}
