// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:48eaa6aee6a9621260908f86b470f0394ca8594aea6b158a71425b92dd28df38
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// The requested language name (or alias) was not found in the registry.
/// </summary>
public class LanguageNotFoundException : ErrorException
{
    public LanguageNotFoundException(string message) : base(message) { }

    public LanguageNotFoundException(string message, Exception innerException) : base(message, innerException) { }
}
