// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:315fdd75adc264b2de9a616676db17facfdb001406dcb313ed620cef495b2bd2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TreeSitterLanguagePack;

public sealed class LanguageInfo
{
    [JsonPropertyName("group")]
    public string Group { get; set; } = "";

    [JsonPropertyName("size")]
    public ulong Size { get; set; } = 0;


    /// <summary>
    /// Parse a <see cref="LanguageInfo"/> from a JSON string.
    /// </summary>
    /// <exception cref="TreeSitterLanguagePackException">When the JSON cannot be deserialised.</exception>
    public static LanguageInfo FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<LanguageInfo>(json, JsonOptions)
                ?? throw new TreeSitterLanguagePackException($"Failed to parse LanguageInfo from JSON: deserializer returned null");
        }
        catch (TreeSitterLanguagePackException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new TreeSitterLanguagePackException($"Failed to parse LanguageInfo from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
