// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:366e4c8ea9d7faf2f7f60323b445cf09d7d68f3d820d87ae297aed3b4a4fc643
#nullable enable

using System;
using Microsoft.Win32.SafeHandles;
using System.Runtime.InteropServices;

namespace TreeSitterLanguagePack;

internal sealed class LanguageSafeHandle : SafeHandle
{
    internal LanguageSafeHandle(IntPtr handle) : base(IntPtr.Zero, true)
    {
        SetHandle(handle);
    }

    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        NativeMethods.LanguageFree(handle);
        return true;
    }
}

public sealed class Language : IDisposable
{
    private readonly LanguageSafeHandle _safeHandle;

    internal Language(IntPtr handle)
    {
        _safeHandle = new LanguageSafeHandle(handle);
    }

    internal IntPtr Handle => _safeHandle.DangerousGetHandle();

    public void Dispose() => _safeHandle.Dispose();

}
