// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:fd7b1e473fa0d8e7e4206ee0cd5f300888c629c053f5f94ebf472d87c1b3f26c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;

namespace TreeSitterLanguagePack;

public sealed class Language : IDisposable
{
    internal IntPtr Handle { get; }

    internal Language(IntPtr handle)
    {
        Handle = handle;
    }

    public void Dispose()
    {
        // Native free will be called by the runtime
    }
}
