// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:954e8c969c2688124c036fab998347d1bb269e112b398e2d92ffbd2b67f24a45
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TreeSitterLanguagePack;

public sealed class LanguageInfo
{
    [JsonPropertyName("group")]
    public string Group { get; set; } = "";

    [JsonPropertyName("size")]
    public ulong Size { get; set; } = 0;

}
