// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7a28870ed956f3bc905e5658d6a02739f99c913fd47058d0b86bf0780e634064
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// The requested language name (or alias) was not found in the registry.
/// </summary>
public class LanguageNotFoundException : ErrorException
{
    public LanguageNotFoundException(string message) : base(message) { }

    public LanguageNotFoundException(string message, Exception innerException) : base(message, innerException) { }
}
