// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:360e02edf70c86e2e1a835db7f366f6b66fdd0a250df7395639cdaa155a85d21
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// An internal `RwLock` or `Mutex` was poisoned by a previous panic.
/// </summary>
public class LockPoisonedException : ErrorException
{
    public LockPoisonedException(string message) : base(message) { }

    public LockPoisonedException(string message, Exception innerException) : base(message, innerException) { }
}
