// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:44a0d5babc63706f84f2e19d48cf948b55c87cbbe3e341ee15c08a54f4d42d8f
#nullable enable

using System;

namespace TreeSitterLanguagePack;

public class LockPoisonedException : ErrorException
{
    public LockPoisonedException(string message) : base(message) { }

    public LockPoisonedException(string message, Exception innerException) : base(message, innerException) { }
}
