// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:5c3eac2ef7892df9942263b2ef22bbce08c4729cfb235dcd7f37f968755d1b10
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// The tree-sitter language function returned a null pointer for the given language name.
/// </summary>
public class NullLanguagePointerException : ErrorException
{
    public NullLanguagePointerException(string message) : base(message) { }

    public NullLanguagePointerException(string message, Exception innerException) : base(message, innerException) { }
}
