// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8e6b60fdb22a27e2f51a6dd18bffcfb22706f9892d9a8d350deea54c0df67828
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// The language could not be applied to the parser (e.g., ABI version mismatch).
/// </summary>
public class ParserSetupException : ErrorException
{
    public ParserSetupException(string message) : base(message) { }

    public ParserSetupException(string message, Exception innerException) : base(message, innerException) { }
}
