// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:360e02edf70c86e2e1a835db7f366f6b66fdd0a250df7395639cdaa155a85d21
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// The language could not be applied to the parser (e.g., ABI version mismatch).
/// </summary>
public class ParserSetupException : ErrorException
{
    public ParserSetupException(string message) : base(message) { }

    public ParserSetupException(string message, Exception innerException) : base(message, innerException) { }
}
