// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8e6b60fdb22a27e2f51a6dd18bffcfb22706f9892d9a8d350deea54c0df67828
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// The tree-sitter parser returned no tree for the given source input.
/// </summary>
public class ParseFailedException : ErrorException
{
    public ParseFailedException(string message) : base(message) { }

    public ParseFailedException(string message, Exception innerException) : base(message, innerException) { }
}
