// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:5c3eac2ef7892df9942263b2ef22bbce08c4729cfb235dcd7f37f968755d1b10
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// The tree-sitter parser returned no tree for the given source input.
/// </summary>
public class ParseFailedException : ErrorException
{
    public ParseFailedException(string message) : base(message) { }

    public ParseFailedException(string message, Exception innerException) : base(message, innerException) { }
}
