// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:fdaedbc30d45f59f128e477ac54794046794ad0608ac245915e5e9bd7fbac89f
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// The language could not be applied to the parser (e.g., ABI version mismatch).
/// </summary>
public class ParserSetupException : ErrorException
{
    public ParserSetupException(string message) : base(message) { }

    public ParserSetupException(string message, Exception innerException) : base(message, innerException) { }
}
