// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:6125571a3e8d71b1bf26c8a105b8f42f97acba36088cabe6d2ac4064fef4370d
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// A tree-sitter query could not be compiled or executed.
/// </summary>
public class QueryErrorException : ErrorException
{
    public QueryErrorException(string message) : base(message) { }

    public QueryErrorException(string message, Exception innerException) : base(message, innerException) { }
}
