// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:cf84eb383aae226537d4dfbf11634379392a6f7ee6eaead589726b5e5d31f75e
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// A tree-sitter query could not be compiled or executed.
/// </summary>
public class QueryErrorException : ErrorException
{
    public QueryErrorException(string message) : base(message) { }

    public QueryErrorException(string message, Exception innerException) : base(message, innerException) { }
}
