// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8bb43fc12f987b2e754f9b1981768a07345d578eb7fe7f956b844c10cb2c2988
#nullable enable

using System;

namespace TreeSitterLanguagePack;

/// <summary>
/// A tree-sitter query could not be compiled or executed.
/// </summary>
public class QueryErrorException : ErrorException
{
    public QueryErrorException(string message) : base(message) { }

    public QueryErrorException(string message, Exception innerException) : base(message, innerException) { }
}
