// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:9f822147ae50dab04bc5e07d9311dd7b4c3d8d73b878655ef12f79b02bb1f5b0
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TreeSitterLanguagePack;
/// <summary>
/// The kind of structural item found in source code.
///
/// Categorizes top-level and nested declarations such as functions, classes,
/// structs, enums, traits, and more. Use [`Other`](StructureKind::Other) for
/// language-specific constructs that do not fit a standard category.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum StructureKind
{
    [JsonPropertyName("function")]
    Function, [JsonPropertyName("method")]
    Method, [JsonPropertyName("class")]
    Class, [JsonPropertyName("struct")]
    Struct, [JsonPropertyName("interface")]
    Interface, [JsonPropertyName("enum")]
    Enum, [JsonPropertyName("module")]
    Module, [JsonPropertyName("trait")]
    Trait, [JsonPropertyName("impl")]
    Impl, [JsonPropertyName("namespace")]
    Namespace, [JsonPropertyName("other")]
    Other,
}
