// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:d6a7c5c191b5fd284c25c09bd30f4766115c03dc59acacca936bd5004ecd51e2
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TreeSitterLanguagePack;
/// <summary>/// The kind of a symbol definition found in source code./// /// Categorizes symbol definitions such as variables, constants, functions,/// classes, types, interfaces, enums, and modules./// </summary>
public enum SymbolKind
{[JsonPropertyName("variable")]
    Variable,[JsonPropertyName("constant")]
    Constant,[JsonPropertyName("function")]
    Function,[JsonPropertyName("class")]
    Class,[JsonPropertyName("type")]
    Type,[JsonPropertyName("interface")]
    Interface,[JsonPropertyName("enum")]
    Enum,[JsonPropertyName("module")]
    Module,[JsonPropertyName("other")]
    Other,}
