// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ba3d64f1bdbc733556a596b2718817609290c351656742357e98689aba93f174
#nullable enable

using System;

namespace TreeSitterLanguagePack;

public class TreeSitterLanguagePackException : Exception
{
    public int Code { get; }

    public TreeSitterLanguagePackException(int code, string message) : base(message)
    {
        Code = code;
    }

    public TreeSitterLanguagePackException(string message) : base(message)
    {
        Code = 0;
    }

    public TreeSitterLanguagePackException(string message, Exception innerException) : base(message, innerException)
    {
        Code = 0;
    }
}
