// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:392c35e6b4fb340e5ae315cd9b6bc5e744b40531c34a234e6061329bba9002e1
#nullable enable

using System;

namespace TreeSitterLanguagePack;

public class TreeSitterLanguagePackException : Exception
{
    public int Code { get; }

    public TreeSitterLanguagePackException(int code, string message) : base(message)
    {
        Code = code;
    }

    public TreeSitterLanguagePackException(string message) : base(message)
    {
        Code = 0;
    }

    public TreeSitterLanguagePackException(string message, Exception innerException) : base(message, innerException)
    {
        Code = 0;
    }
}
