// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:d156b3f21d3da47b056bc94d5a2efc5ee0d8c6d26a733a0f453b579ce100d595
#nullable enable

using System;

namespace TreeSitterLanguagePack;

public class TreeSitterLanguagePackException : Exception
{
    public int Code { get; }

    public TreeSitterLanguagePackException(int code, string message) : base(message)
    {
        Code = code;
    }

    public TreeSitterLanguagePackException(string message) : base(message)
    {
        Code = 0;
    }

    public TreeSitterLanguagePackException(string message, Exception innerException) : base(message, innerException)
    {
        Code = 0;
    }
}
