// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8bb43fc12f987b2e754f9b1981768a07345d578eb7fe7f956b844c10cb2c2988
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
using System;
using System.IO;
using System.Runtime.CompilerServices;

namespace TreeSitterLanguagePack;

internal static class TestSetup
{
    [ModuleInitializer]
    internal static void Init()
    {
        // Walk up from the assembly directory until we find the repo root.
        // Prefer a sibling test_documents/ directory (chdir into it so that
        // fixture paths like "docx/fake.docx" resolve relative to it). If that
        // is absent (projects with no document fixtures), fall
        // back to a sibling alef.toml or fixtures/ marker as the repo root.
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        DirectoryInfo? repoRoot = null;
        while (dir != null)
        {
            var documentsCandidate = Path.Combine(dir.FullName, "test_documents");
            if (Directory.Exists(documentsCandidate))
            {
                repoRoot = dir;
                Directory.SetCurrentDirectory(documentsCandidate);
                break;
            }
            if (File.Exists(Path.Combine(dir.FullName, "alef.toml"))
                || Directory.Exists(Path.Combine(dir.FullName, "fixtures")))
            {
                repoRoot = dir;
                break;
            }
            dir = dir.Parent;
        }
    }
}
