# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8a18edcd9ab652e928e6e9bd871efb0698347b6457f51acb2178ff97ad98de7c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: query
defmodule E2e.QueryTest do
  use ExUnit.Case, async: false

  describe "highlights_nonexistent_language" do
    test "highlights_nonexistent_language" do
      result = TreeSitterLanguagePack.get_highlights_query("zzz_nonexistent_lang")
      assert is_nil(result) or String.trim(result) == ""
    end
  end

  describe "highlights_query_rust" do
    test "highlights_query_rust" do
      result = TreeSitterLanguagePack.get_highlights_query("rust")
      assert result != ""
    end
  end

  describe "highlights_query_unknown_language" do
    test "highlights_query_unknown_language" do
      result = TreeSitterLanguagePack.get_highlights_query("nonexistent_language_xyz")
      assert is_nil(result) or String.trim(result) == ""
    end
  end

  describe "injections_query_rust" do
    test "injections_query_rust" do
      result = TreeSitterLanguagePack.get_injections_query("rust")
      assert result != ""
    end
  end

  describe "injections_query_unknown_language" do
    test "injections_query_unknown_language" do
      result = TreeSitterLanguagePack.get_injections_query("nonexistent_xyz")
      assert is_nil(result) or String.trim(result) == ""
    end
  end

  describe "locals_query_cue" do
    test "locals_query_cue" do
      result = TreeSitterLanguagePack.get_locals_query("cue")
      assert result != ""
    end
  end

  describe "locals_query_unknown_language" do
    test "locals_query_unknown_language" do
      result = TreeSitterLanguagePack.get_locals_query("nonexistent_xyz")
      assert is_nil(result) or String.trim(result) == ""
    end
  end

  describe "tags_query_kotlin" do
    test "tags_query_kotlin" do
      result = TreeSitterLanguagePack.get_tags_query("kotlin")
      assert result != ""
    end
  end

  describe "tags_query_rust" do
    test "tags_query_rust" do
      result = TreeSitterLanguagePack.get_tags_query("rust")
      assert result != ""
    end
  end

  describe "tags_query_unknown_language" do
    test "tags_query_unknown_language" do
      result = TreeSitterLanguagePack.get_tags_query("nonexistent_xyz")
      assert is_nil(result) or String.trim(result) == ""
    end
  end
end
