// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0b39f1e738cf8fa2c6d652466c593c2e14c7d6ede6259556c95c1e46377f59d1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

import { describe, expect, it } from "vitest";
import {
  process,
  getHighlightsQuery,
  getInjectionsQuery,
  getLocalsQuery,
} from "tree_sitter_language_pack";
function _alefE2eText(value: unknown): string {
  return value == null ? "" : String(value);
}

function _alefE2eItemTexts(item: unknown): string[] {
  if (item == null || typeof item !== "object") {
    return [_alefE2eText(item)];
  }
  const record = item as Record<string, unknown>;
  const itemsText = Array.isArray(record.items) ? record.items.map(_alefE2eText).join(" ") : "";
  return [
    _alefE2eText(item),
    _alefE2eText(record.kind),
    _alefE2eText(record.name),
    _alefE2eText(record.source),
    _alefE2eText(record.alias),
    _alefE2eText(record.text),
    _alefE2eText(record.signature),
    itemsText,
  ];
}

describe("query", () => {
  it.skip("highlights_nonexistent_language: Get highlights query for nonexistent language returns null/empty", () => {
    // language not in WASM's static-compiled set: [python, javascript, typescript, tsx, rust, go, java, c, cpp, csharp, ruby, php, html, css, json, yaml, toml, markdown, bash, sql, lua, scala, kotlin, swift, dockerfile, vue, svelte, elixir, erlang, haskell, zig]
  });
  it("highlights_query_rust: get_highlights_query returns non-empty string for rust", () => {
    const result = getHighlightsQuery("rust");
    {
      const _v = result;
      if (typeof _v === "string" || Array.isArray(_v)) {
        expect(_v.length).toBeGreaterThan(0);
      } else {
        expect(_v).toBeDefined();
        expect(_v).not.toBeNull();
      }
    }
  });
  it.skip("highlights_query_unknown_language: get_highlights_query returns None for unknown language", () => {
    // language not in WASM's static-compiled set: [python, javascript, typescript, tsx, rust, go, java, c, cpp, csharp, ruby, php, html, css, json, yaml, toml, markdown, bash, sql, lua, scala, kotlin, swift, dockerfile, vue, svelte, elixir, erlang, haskell, zig]
  });
  it("injections_query_rust: get_injections_query returns non-empty for rust", () => {
    const result = getInjectionsQuery("rust");
    {
      const _v = result;
      if (typeof _v === "string" || Array.isArray(_v)) {
        expect(_v.length).toBeGreaterThan(0);
      } else {
        expect(_v).toBeDefined();
        expect(_v).not.toBeNull();
      }
    }
  });
  it.skip("injections_query_unknown_language: get_injections_query returns empty for unknown language", () => {
    // language not in WASM's static-compiled set: [python, javascript, typescript, tsx, rust, go, java, c, cpp, csharp, ruby, php, html, css, json, yaml, toml, markdown, bash, sql, lua, scala, kotlin, swift, dockerfile, vue, svelte, elixir, erlang, haskell, zig]
  });
  it.skip("locals_query_cue: get_locals_query returns non-empty for cue", () => {
    // language not in WASM's static-compiled set: [python, javascript, typescript, tsx, rust, go, java, c, cpp, csharp, ruby, php, html, css, json, yaml, toml, markdown, bash, sql, lua, scala, kotlin, swift, dockerfile, vue, svelte, elixir, erlang, haskell, zig]
  });
  it.skip("locals_query_unknown_language: get_locals_query returns empty for unknown language", () => {
    // language not in WASM's static-compiled set: [python, javascript, typescript, tsx, rust, go, java, c, cpp, csharp, ruby, php, html, css, json, yaml, toml, markdown, bash, sql, lua, scala, kotlin, swift, dockerfile, vue, svelte, elixir, erlang, haskell, zig]
  });
});
