# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2f5e3363deb733da9003518e6cb39574e99a8c0eefe1906ceacb88dd023d23d2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require 'tree_sitter_language_pack'
require 'json'

RSpec.describe 'smoke' do
  it 'smoke_abl: Smoke test: load abl and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'abl' }) }.not_to raise_error
  end

  it 'smoke_actionscript: Smoke test: load actionscript and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('var x:int = 1;', { 'language' => 'actionscript' }) }.not_to raise_error
  end

  it 'smoke_ada: Smoke test: load ada and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('procedure Main is begin null; end Main;', { 'language' => 'ada' }) }.not_to raise_error
  end

  it 'smoke_agda: Smoke test: load agda and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('module Main where', { 'language' => 'agda' }) }.not_to raise_error
  end

  it 'smoke_al: Smoke test: load al and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'al' }) }.not_to raise_error
  end

  it 'smoke_angular: Smoke test: load angular and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'angular' }) }.not_to raise_error
  end

  it 'smoke_apex: Smoke test: load apex and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('public class Main {}', { 'language' => 'apex' }) }.not_to raise_error
  end

  it 'smoke_arduino: Smoke test: load arduino and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('void setup() {}', { 'language' => 'arduino' }) }.not_to raise_error
  end

  it 'smoke_asciidoc: Smoke test: load asciidoc and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("= Title\n\nParagraph.", { 'language' => 'asciidoc' }) }.not_to raise_error
  end

  it 'smoke_asm: Smoke test: load asm and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('mov eax, 1', { 'language' => 'asm' }) }.not_to raise_error
  end

  it 'smoke_astro: Smoke test: load astro and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("---\n---\n<p>hello</p>", { 'language' => 'astro' }) }.not_to raise_error
  end

  it 'smoke_awk: Smoke test: load awk and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('BEGIN { print "hello" }', { 'language' => 'awk' }) }.not_to raise_error
  end

  it 'smoke_bash: Smoke test: load bash and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('echo hello', { 'language' => 'bash' }) }.not_to raise_error
  end

  it 'smoke_bass: Smoke test: load bass and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'bass' }) }.not_to raise_error
  end

  it 'smoke_batch: Smoke test: load batch and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("@echo off\necho hello", { 'language' => 'batch' }) }.not_to raise_error
  end

  it 'smoke_beancount: Smoke test: load beancount and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('2024-01-01 open Assets:Bank USD', { 'language' => 'beancount' }) }.not_to raise_error
  end

  it 'smoke_bibtex: Smoke test: load bibtex and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('@article{key, title={A}}', { 'language' => 'bibtex' }) }.not_to raise_error
  end

  it 'smoke_bicep: Smoke test: load bicep and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('param name string', { 'language' => 'bicep' }) }.not_to raise_error
  end

  it 'smoke_bitbake: Smoke test: load bitbake and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('DESCRIPTION = "hello"', { 'language' => 'bitbake' }) }.not_to raise_error
  end

  it 'smoke_blade: Smoke test: load blade and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'blade' }) }.not_to raise_error
  end

  it 'smoke_brightscript: Smoke test: load brightscript and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'brightscript' }) }.not_to raise_error
  end

  it 'smoke_bsl: Smoke test: load bsl and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('Procedure Main() EndProcedure', { 'language' => 'bsl' }) }.not_to raise_error
  end

  it 'smoke_c: Smoke test: load c and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('int main() { return 0; }', { 'language' => 'c' }) }.not_to raise_error
  end

  it 'smoke_c3: Smoke test: load c3 and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'c3' }) }.not_to raise_error
  end

  it 'smoke_caddy: Smoke test: load caddy and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process(":8080 {\n\trespond \"Hello\"\n}", { 'language' => 'caddy' }) }.not_to raise_error
  end

  it 'smoke_cairo: Smoke test: load cairo and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('fn main() {}', { 'language' => 'cairo' }) }.not_to raise_error
  end

  it 'smoke_capnp: Smoke test: load capnp and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('@0xabcdef1234567890;', { 'language' => 'capnp' }) }.not_to raise_error
  end

  it 'smoke_cedar: Smoke test: load cedar and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('permit(principal, action, resource);', { 'language' => 'cedar' }) }.not_to raise_error
  end

  it 'smoke_cedarschema: Smoke test: load cedarschema and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('entity User;', { 'language' => 'cedarschema' }) }.not_to raise_error
  end

  it 'smoke_cel: Smoke test: load cel and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'cel' }) }.not_to raise_error
  end

  it 'smoke_cfml: Smoke test: load cfml and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'cfml' }) }.not_to raise_error
  end

  it 'smoke_chatito: Smoke test: load chatito and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("%[greeting]\n    hello", { 'language' => 'chatito' }) }.not_to raise_error
  end

  it 'smoke_chuck: Smoke test: load chuck and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'chuck' }) }.not_to raise_error
  end

  it 'smoke_circom: Smoke test: load circom and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'circom' }) }.not_to raise_error
  end

  it 'smoke_clarity: Smoke test: load clarity and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('(define-public (hello) (ok true))', { 'language' => 'clarity' }) }.not_to raise_error
  end

  it 'smoke_clojure: Smoke test: load clojure and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('(def x 1)', { 'language' => 'clojure' }) }.not_to raise_error
  end

  it 'smoke_cmake: Smoke test: load cmake and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('cmake_minimum_required(VERSION 3.0)', { 'language' => 'cmake' }) }.not_to raise_error
  end

  it 'smoke_cobol: Smoke test: load cobol and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("       IDENTIFICATION DIVISION.\n       PROGRAM-ID. HELLO.", { 'language' => 'cobol' }) }.not_to raise_error
  end

  it 'smoke_comment: Smoke test: load comment and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('TODO: fix this', { 'language' => 'comment' }) }.not_to raise_error
  end

  it 'smoke_commonlisp: Smoke test: load commonlisp and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('(defun hello () (print "hello"))', { 'language' => 'commonlisp' }) }.not_to raise_error
  end

  it 'smoke_cooklang: Smoke test: load cooklang and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'cooklang' }) }.not_to raise_error
  end

  it 'smoke_corn: Smoke test: load corn and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('{ key = "value" }', { 'language' => 'corn' }) }.not_to raise_error
  end

  it 'smoke_cpon: Smoke test: load cpon and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('{"key": 1}', { 'language' => 'cpon' }) }.not_to raise_error
  end

  it 'smoke_cpp: Smoke test: load cpp and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('int main() { return 0; }', { 'language' => 'cpp' }) }.not_to raise_error
  end

  it 'smoke_crystal: Smoke test: load crystal and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'crystal' }) }.not_to raise_error
  end

  it 'smoke_csharp: Smoke test: load csharp and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('class Main {}', { 'language' => 'csharp' }) }.not_to raise_error
  end

  it 'smoke_css: Smoke test: load css and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('body { color: red; }', { 'language' => 'css' }) }.not_to raise_error
  end

  it 'smoke_cst: Smoke test: load cst and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'cst' }) }.not_to raise_error
  end

  it 'smoke_csv: Smoke test: load csv and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("a,b,c\n1,2,3", { 'language' => 'csv' }) }.not_to raise_error
  end

  it 'smoke_cuda: Smoke test: load cuda and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('__global__ void kernel() {}', { 'language' => 'cuda' }) }.not_to raise_error
  end

  it 'smoke_cue: Smoke test: load cue and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'cue' }) }.not_to raise_error
  end

  it 'smoke_cylc: Smoke test: load cylc and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'cylc' }) }.not_to raise_error
  end

  it 'smoke_d: Smoke test: load d and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('void main() {}', { 'language' => 'd' }) }.not_to raise_error
  end

  it 'smoke_dart: Smoke test: load dart and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('void main() {}', { 'language' => 'dart' }) }.not_to raise_error
  end

  it 'smoke_desktop: Smoke test: load desktop and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'desktop' }) }.not_to raise_error
  end

  it 'smoke_devicetree: Smoke test: load devicetree and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("/dts-v1/;\n/ { };", { 'language' => 'devicetree' }) }.not_to raise_error
  end

  it 'smoke_dhall: Smoke test: load dhall and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'dhall' }) }.not_to raise_error
  end

  it 'smoke_diff: Smoke test: load diff and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("--- a/file\n+++ b/file\n@@ -1 +1 @@\n-old\n+new", { 'language' => 'diff' }) }.not_to raise_error
  end

  it 'smoke_djot: Smoke test: load djot and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'djot' }) }.not_to raise_error
  end

  it 'smoke_dockerfile: Smoke test: load dockerfile and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('FROM alpine', { 'language' => 'dockerfile' }) }.not_to raise_error
  end

  it 'smoke_dot: Smoke test: load dot and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('digraph G { A -> B; }', { 'language' => 'dot' }) }.not_to raise_error
  end

  it 'smoke_doxygen: Smoke test: load doxygen and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('/** @brief A function */', { 'language' => 'doxygen' }) }.not_to raise_error
  end

  it 'smoke_dtd: Smoke test: load dtd and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('<!ELEMENT note (body)>', { 'language' => 'dtd' }) }.not_to raise_error
  end

  it 'smoke_earthfile: Smoke test: load earthfile and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'earthfile' }) }.not_to raise_error
  end

  it 'smoke_ebnf: Smoke test: load ebnf and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'ebnf' }) }.not_to raise_error
  end

  it 'smoke_editorconfig: Smoke test: load editorconfig and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'editorconfig' }) }.not_to raise_error
  end

  it 'smoke_eds: Smoke test: load eds and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'eds' }) }.not_to raise_error
  end

  it 'smoke_eex: Smoke test: load eex and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'eex' }) }.not_to raise_error
  end

  it 'smoke_elisp: Smoke test: load elisp and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('(defun hello () (message "hello"))', { 'language' => 'elisp' }) }.not_to raise_error
  end

  it 'smoke_elixir: Smoke test: load elixir and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('IO.puts("hello")', { 'language' => 'elixir' }) }.not_to raise_error
  end

  it 'smoke_elm: Smoke test: load elm and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('module Main exposing (..)', { 'language' => 'elm' }) }.not_to raise_error
  end

  it 'smoke_elsa: Smoke test: load elsa and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'elsa' }) }.not_to raise_error
  end

  it 'smoke_elvish: Smoke test: load elvish and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'elvish' }) }.not_to raise_error
  end

  it 'smoke_embeddedtemplate: Smoke test: load embeddedtemplate and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('<%= value %>', { 'language' => 'embeddedtemplate' }) }.not_to raise_error
  end

  it 'smoke_enforce: Smoke test: load enforce and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'enforce' }) }.not_to raise_error
  end

  it 'smoke_erlang: Smoke test: load erlang and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('main() -> ok.', { 'language' => 'erlang' }) }.not_to raise_error
  end

  it 'smoke_facility: Smoke test: load facility and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'facility' }) }.not_to raise_error
  end

  it 'smoke_faust: Smoke test: load faust and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'faust' }) }.not_to raise_error
  end

  it 'smoke_fennel: Smoke test: load fennel and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('(fn hello [] (print :hello))', { 'language' => 'fennel' }) }.not_to raise_error
  end

  it 'smoke_fidl: Smoke test: load fidl and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'fidl' }) }.not_to raise_error
  end

  it 'smoke_firrtl: Smoke test: load firrtl and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('circuit Main :', { 'language' => 'firrtl' }) }.not_to raise_error
  end

  it 'smoke_fish: Smoke test: load fish and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('echo hello', { 'language' => 'fish' }) }.not_to raise_error
  end

  it 'smoke_foam: Smoke test: load foam and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'foam' }) }.not_to raise_error
  end

  it 'smoke_forth: Smoke test: load forth and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'forth' }) }.not_to raise_error
  end

  it 'smoke_fortran: Smoke test: load fortran and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("program main\nend program main", { 'language' => 'fortran' }) }.not_to raise_error
  end

  it 'smoke_fsharp: Smoke test: load fsharp and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('let x = 1', { 'language' => 'fsharp' }) }.not_to raise_error
  end

  it 'smoke_fsharp_signature: Smoke test: load fsharp_signature and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('val x: int', { 'language' => 'fsharp_signature' }) }.not_to raise_error
  end

  it 'smoke_func: Smoke test: load func and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('() recv_internal() {}', { 'language' => 'func' }) }.not_to raise_error
  end

  it 'smoke_gap: Smoke test: load gap and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'gap' }) }.not_to raise_error
  end

  it 'smoke_gdscript: Smoke test: load gdscript and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("extends Node\nfunc _ready():\n\tpass", { 'language' => 'gdscript' }) }.not_to raise_error
  end

  it 'smoke_gdshader: Smoke test: load gdshader and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'gdshader' }) }.not_to raise_error
  end

  it 'smoke_git_config: Smoke test: load git_config and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'git_config' }) }.not_to raise_error
  end

  it 'smoke_git_rebase: Smoke test: load git_rebase and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'git_rebase' }) }.not_to raise_error
  end

  it 'smoke_gitattributes: Smoke test: load gitattributes and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('*.txt text', { 'language' => 'gitattributes' }) }.not_to raise_error
  end

  it 'smoke_gitcommit: Smoke test: load gitcommit and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("feat: add feature\n\nBody text", { 'language' => 'gitcommit' }) }.not_to raise_error
  end

  it 'smoke_gitignore: Smoke test: load gitignore and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("*.o\n*.log", { 'language' => 'gitignore' }) }.not_to raise_error
  end

  it 'smoke_gleam: Smoke test: load gleam and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('pub fn main() { }', { 'language' => 'gleam' }) }.not_to raise_error
  end

  it 'smoke_glimmer: Smoke test: load glimmer and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'glimmer' }) }.not_to raise_error
  end

  it 'smoke_glsl: Smoke test: load glsl and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('void main() { gl_Position = vec4(0.0); }', { 'language' => 'glsl' }) }.not_to raise_error
  end

  it 'smoke_gn: Smoke test: load gn and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('group("hello") {}', { 'language' => 'gn' }) }.not_to raise_error
  end

  it 'smoke_gnuplot: Smoke test: load gnuplot and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'gnuplot' }) }.not_to raise_error
  end

  it 'smoke_go: Smoke test: load go and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('package main', { 'language' => 'go' }) }.not_to raise_error
  end

  it 'smoke_godot_resource: Smoke test: load godot_resource and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'godot_resource' }) }.not_to raise_error
  end

  it 'smoke_gomod: Smoke test: load gomod and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("module example.com/hello\n\ngo 1.21", { 'language' => 'gomod' }) }.not_to raise_error
  end

  it 'smoke_gosum: Smoke test: load gosum and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('example.com/pkg v1.0.0 h1:abc=', { 'language' => 'gosum' }) }.not_to raise_error
  end

  it 'smoke_gotmpl: Smoke test: load gotmpl and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'gotmpl' }) }.not_to raise_error
  end

  it 'smoke_gowork: Smoke test: load gowork and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'gowork' }) }.not_to raise_error
  end

  it 'smoke_gpg: Smoke test: load gpg and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'gpg' }) }.not_to raise_error
  end

  it 'smoke_graphql: Smoke test: load graphql and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('type Query { hello: String }', { 'language' => 'graphql' }) }.not_to raise_error
  end

  it 'smoke_gren: Smoke test: load gren and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('module Main exposing (..)', { 'language' => 'gren' }) }.not_to raise_error
  end

  it 'smoke_groovy: Smoke test: load groovy and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('def x = 1', { 'language' => 'groovy' }) }.not_to raise_error
  end

  it 'smoke_gstlaunch: Smoke test: load gstlaunch and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('fakesrc ! fakesink', { 'language' => 'gstlaunch' }) }.not_to raise_error
  end

  it 'smoke_hack: Smoke test: load hack and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("<?hh\nfunction main(): void {}", { 'language' => 'hack' }) }.not_to raise_error
  end

  it 'smoke_hare: Smoke test: load hare and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('export fn main() void = void;', { 'language' => 'hare' }) }.not_to raise_error
  end

  it 'smoke_haskell: Smoke test: load haskell and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('main = putStrLn "hello"', { 'language' => 'haskell' }) }.not_to raise_error
  end

  it 'smoke_haxe: Smoke test: load haxe and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('class Main { static function main() {} }', { 'language' => 'haxe' }) }.not_to raise_error
  end

  it 'smoke_hcl: Smoke test: load hcl and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('variable "name" { type = string }', { 'language' => 'hcl' }) }.not_to raise_error
  end

  it 'smoke_heex: Smoke test: load heex and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('<%= @greeting %>', { 'language' => 'heex' }) }.not_to raise_error
  end

  it 'smoke_hjson: Smoke test: load hjson and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'hjson' }) }.not_to raise_error
  end

  it 'smoke_hlsl: Smoke test: load hlsl and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('float4 main() : SV_Target { return 0; }', { 'language' => 'hlsl' }) }.not_to raise_error
  end

  it 'smoke_hocon: Smoke test: load hocon and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'hocon' }) }.not_to raise_error
  end

  it 'smoke_hoon: Smoke test: load hoon and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'hoon' }) }.not_to raise_error
  end

  it 'smoke_html: Smoke test: load html and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('<p>hello</p>', { 'language' => 'html' }) }.not_to raise_error
  end

  it 'smoke_htmldjango: Smoke test: load htmldjango and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'htmldjango' }) }.not_to raise_error
  end

  it 'smoke_http: Smoke test: load http and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'http' }) }.not_to raise_error
  end

  it 'smoke_hurl: Smoke test: load hurl and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'hurl' }) }.not_to raise_error
  end

  it 'smoke_hyprlang: Smoke test: load hyprlang and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('general { border_size = 1 }', { 'language' => 'hyprlang' }) }.not_to raise_error
  end

  it 'smoke_idris: Smoke test: load idris and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('module Main', { 'language' => 'idris' }) }.not_to raise_error
  end

  it 'smoke_ini: Smoke test: load ini and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("[section]\nkey = value", { 'language' => 'ini' }) }.not_to raise_error
  end

  it 'smoke_ispc: Smoke test: load ispc and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('export void main() {}', { 'language' => 'ispc' }) }.not_to raise_error
  end

  it 'smoke_jai: Smoke test: load jai and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'jai' }) }.not_to raise_error
  end

  it 'smoke_janet: Smoke test: load janet and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('(print "hello")', { 'language' => 'janet' }) }.not_to raise_error
  end

  it 'smoke_java: Smoke test: load java and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('class Main {}', { 'language' => 'java' }) }.not_to raise_error
  end

  it 'smoke_javadoc: Smoke test: load javadoc and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'javadoc' }) }.not_to raise_error
  end

  it 'smoke_javascript: Smoke test: load javascript and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('console.log(\'hello\');', { 'language' => 'javascript' }) }.not_to raise_error
  end

  it 'smoke_jinja2: Smoke test: load jinja2 and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('{{ variable }}', { 'language' => 'jinja2' }) }.not_to raise_error
  end

  it 'smoke_jq: Smoke test: load jq and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('.[] | select(.key)', { 'language' => 'jq' }) }.not_to raise_error
  end

  it 'smoke_jsdoc: Smoke test: load jsdoc and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('/** @param {string} name */', { 'language' => 'jsdoc' }) }.not_to raise_error
  end

  it 'smoke_json: Smoke test: load json and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('{"key": "value"}', { 'language' => 'json' }) }.not_to raise_error
  end

  it 'smoke_json5: Smoke test: load json5 and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'json5' }) }.not_to raise_error
  end

  it 'smoke_jsonnet: Smoke test: load jsonnet and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('{ key: \'value\' }', { 'language' => 'jsonnet' }) }.not_to raise_error
  end

  it 'smoke_julia: Smoke test: load julia and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('function main() end', { 'language' => 'julia' }) }.not_to raise_error
  end

  it 'smoke_just: Smoke test: load just and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'just' }) }.not_to raise_error
  end

  it 'smoke_kcl: Smoke test: load kcl and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'kcl' }) }.not_to raise_error
  end

  it 'smoke_kconfig: Smoke test: load kconfig and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("config FOO\n\tbool \"Enable foo\"", { 'language' => 'kconfig' }) }.not_to raise_error
  end

  it 'smoke_kdl: Smoke test: load kdl and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('node "value"', { 'language' => 'kdl' }) }.not_to raise_error
  end

  it 'smoke_kotlin: Smoke test: load kotlin and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('fun main() {}', { 'language' => 'kotlin' }) }.not_to raise_error
  end

  it 'smoke_latex: Smoke test: load latex and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("\\documentclass{article}\n\\begin{document}\nHello\n\\end{document}", { 'language' => 'latex' }) }.not_to raise_error
  end

  it 'smoke_lean: Smoke test: load lean and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('def main : IO Unit := pure ()', { 'language' => 'lean' }) }.not_to raise_error
  end

  it 'smoke_ledger: Smoke test: load ledger and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'ledger' }) }.not_to raise_error
  end

  it 'smoke_less: Smoke test: load less and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'less' }) }.not_to raise_error
  end

  it 'smoke_linkerscript: Smoke test: load linkerscript and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('SECTIONS { .text : { *(.text) } }', { 'language' => 'linkerscript' }) }.not_to raise_error
  end

  it 'smoke_liquid: Smoke test: load liquid and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'liquid' }) }.not_to raise_error
  end

  it 'smoke_llvm: Smoke test: load llvm and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('define i32 @main() { ret i32 0 }', { 'language' => 'llvm' }) }.not_to raise_error
  end

  it 'smoke_lua: Smoke test: load lua and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('print(\'hello\')', { 'language' => 'lua' }) }.not_to raise_error
  end

  it 'smoke_luadoc: Smoke test: load luadoc and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('---@param name string', { 'language' => 'luadoc' }) }.not_to raise_error
  end

  it 'smoke_luap: Smoke test: load luap and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('[a-z]+', { 'language' => 'luap' }) }.not_to raise_error
  end

  it 'smoke_luau: Smoke test: load luau and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('local x: number = 1', { 'language' => 'luau' }) }.not_to raise_error
  end

  it 'smoke_magik: Smoke test: load magik and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("_method object.hello\n_endmethod", { 'language' => 'magik' }) }.not_to raise_error
  end

  it 'smoke_make: Smoke test: load make and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("all:\n\techo hello", { 'language' => 'make' }) }.not_to raise_error
  end

  it 'smoke_markdown: Smoke test: load markdown and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("\# Hello\n\nWorld", { 'language' => 'markdown' }) }.not_to raise_error
  end

  it 'smoke_markdown_inline: Smoke test: load markdown_inline and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('**bold** and *italic*', { 'language' => 'markdown_inline' }) }.not_to raise_error
  end

  it 'smoke_matlab: Smoke test: load matlab and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("function y = hello(x)\ny = x;\nend", { 'language' => 'matlab' }) }.not_to raise_error
  end

  it 'smoke_mermaid: Smoke test: load mermaid and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("graph TD\nA --> B", { 'language' => 'mermaid' }) }.not_to raise_error
  end

  it 'smoke_meson: Smoke test: load meson and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('project(\'hello\', \'c\')', { 'language' => 'meson' }) }.not_to raise_error
  end

  it 'smoke_mlir: Smoke test: load mlir and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'mlir' }) }.not_to raise_error
  end

  it 'smoke_mojo: Smoke test: load mojo and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'mojo' }) }.not_to raise_error
  end

  it 'smoke_move: Smoke test: load move and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'move' }) }.not_to raise_error
  end

  it 'smoke_nasm: Smoke test: load nasm and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'nasm' }) }.not_to raise_error
  end

  it 'smoke_netlinx: Smoke test: load netlinx and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('PROGRAM_NAME=\'hello\'', { 'language' => 'netlinx' }) }.not_to raise_error
  end

  it 'smoke_nginx: Smoke test: load nginx and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'nginx' }) }.not_to raise_error
  end

  it 'smoke_nickel: Smoke test: load nickel and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'nickel' }) }.not_to raise_error
  end

  it 'smoke_nim: Smoke test: load nim and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('echo "hello"', { 'language' => 'nim' }) }.not_to raise_error
  end

  it 'smoke_ninja: Smoke test: load ninja and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("rule cc\n  command = cc $in -o $out", { 'language' => 'ninja' }) }.not_to raise_error
  end

  it 'smoke_nix: Smoke test: load nix and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('{ pkgs ? import <nixpkgs> {} }: pkgs.hello', { 'language' => 'nix' }) }.not_to raise_error
  end

  it 'smoke_norg: Smoke test: load norg and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'norg' }) }.not_to raise_error
  end

  it 'smoke_norg_meta: Smoke test: load norg_meta and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'norg_meta' }) }.not_to raise_error
  end

  it 'smoke_nqc: Smoke test: load nqc and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('task main() {}', { 'language' => 'nqc' }) }.not_to raise_error
  end

  it 'smoke_nushell: Smoke test: load nushell and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'nushell' }) }.not_to raise_error
  end

  it 'smoke_objc: Smoke test: load objc and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('@interface Main @end', { 'language' => 'objc' }) }.not_to raise_error
  end

  it 'smoke_ocaml: Smoke test: load ocaml and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('let () = print_endline "hello"', { 'language' => 'ocaml' }) }.not_to raise_error
  end

  it 'smoke_ocaml_interface: Smoke test: load ocaml_interface and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('val x : int', { 'language' => 'ocaml_interface' }) }.not_to raise_error
  end

  it 'smoke_ocamllex: Smoke test: load ocamllex and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'ocamllex' }) }.not_to raise_error
  end

  it 'smoke_odin: Smoke test: load odin and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('package main', { 'language' => 'odin' }) }.not_to raise_error
  end

  it 'smoke_openscad: Smoke test: load openscad and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'openscad' }) }.not_to raise_error
  end

  it 'smoke_org: Smoke test: load org and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("* Hello\nWorld", { 'language' => 'org' }) }.not_to raise_error
  end

  it 'smoke_pascal: Smoke test: load pascal and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('program Hello; begin end.', { 'language' => 'pascal' }) }.not_to raise_error
  end

  it 'smoke_pem: Smoke test: load pem and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("-----BEGIN CERTIFICATE-----\ndata\n-----END CERTIFICATE-----", { 'language' => 'pem' }) }.not_to raise_error
  end

  it 'smoke_perl: Smoke test: load perl and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('print \'hello\';', { 'language' => 'perl' }) }.not_to raise_error
  end

  it 'smoke_pgn: Smoke test: load pgn and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('1. e4 e5 *', { 'language' => 'pgn' }) }.not_to raise_error
  end

  it 'smoke_php: Smoke test: load php and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('<?php echo \'hello\'; ?>', { 'language' => 'php' }) }.not_to raise_error
  end

  it 'smoke_phpdoc: Smoke test: load phpdoc and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'phpdoc' }) }.not_to raise_error
  end

  it 'smoke_pkl: Smoke test: load pkl and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('name = "hello"', { 'language' => 'pkl' }) }.not_to raise_error
  end

  it 'smoke_po: Smoke test: load po and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("msgid \"hello\"\nmsgstr \"world\"", { 'language' => 'po' }) }.not_to raise_error
  end

  it 'smoke_poe_filter: Smoke test: load poe_filter and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'poe_filter' }) }.not_to raise_error
  end

  it 'smoke_pony: Smoke test: load pony and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("actor Main\n  new create(env: Env) => None", { 'language' => 'pony' }) }.not_to raise_error
  end

  it 'smoke_postscript: Smoke test: load postscript and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('/hello { (Hello) show } def', { 'language' => 'postscript' }) }.not_to raise_error
  end

  it 'smoke_powershell: Smoke test: load powershell and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('Write-Host \'hello\'', { 'language' => 'powershell' }) }.not_to raise_error
  end

  it 'smoke_printf: Smoke test: load printf and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('%d %s', { 'language' => 'printf' }) }.not_to raise_error
  end

  it 'smoke_prisma: Smoke test: load prisma and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('model User { id Int @id }', { 'language' => 'prisma' }) }.not_to raise_error
  end

  it 'smoke_prolog: Smoke test: load prolog and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('hello :- write(\'hello\'), nl.', { 'language' => 'prolog' }) }.not_to raise_error
  end

  it 'smoke_promql: Smoke test: load promql and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'promql' }) }.not_to raise_error
  end

  it 'smoke_properties: Smoke test: load properties and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('key=value', { 'language' => 'properties' }) }.not_to raise_error
  end

  it 'smoke_proto: Smoke test: load proto and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('syntax = "proto3";', { 'language' => 'proto' }) }.not_to raise_error
  end

  it 'smoke_prql: Smoke test: load prql and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'prql' }) }.not_to raise_error
  end

  it 'smoke_psv: Smoke test: load psv and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("a|b|c\n1|2|3", { 'language' => 'psv' }) }.not_to raise_error
  end

  it 'smoke_pug: Smoke test: load pug and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'pug' }) }.not_to raise_error
  end

  it 'smoke_puppet: Smoke test: load puppet and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('notify { \'hello\': }', { 'language' => 'puppet' }) }.not_to raise_error
  end

  it 'smoke_purescript: Smoke test: load purescript and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('module Main where', { 'language' => 'purescript' }) }.not_to raise_error
  end

  it 'smoke_pymanifest: Smoke test: load pymanifest and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('include *.txt', { 'language' => 'pymanifest' }) }.not_to raise_error
  end

  it 'smoke_python: Smoke test: load python and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('print(\'hello\')', { 'language' => 'python' }) }.not_to raise_error
  end

  it 'smoke_ql: Smoke test: load ql and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'ql' }) }.not_to raise_error
  end

  it 'smoke_qmldir: Smoke test: load qmldir and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('module Example', { 'language' => 'qmldir' }) }.not_to raise_error
  end

  it 'smoke_qmljs: Smoke test: load qmljs and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("import QtQuick 2.0\nItem {}", { 'language' => 'qmljs' }) }.not_to raise_error
  end

  it 'smoke_query: Smoke test: load query and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('(identifier) @name', { 'language' => 'query' }) }.not_to raise_error
  end

  it 'smoke_r: Smoke test: load r and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('print(\'hello\')', { 'language' => 'r' }) }.not_to raise_error
  end

  it 'smoke_racket: Smoke test: load racket and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("\#lang racket\n(define x 1)", { 'language' => 'racket' }) }.not_to raise_error
  end

  it 'smoke_rasi: Smoke test: load rasi and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'rasi' }) }.not_to raise_error
  end

  it 'smoke_razor: Smoke test: load razor and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'razor' }) }.not_to raise_error
  end

  it 'smoke_rbs: Smoke test: load rbs and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'rbs' }) }.not_to raise_error
  end

  it 'smoke_re2c: Smoke test: load re2c and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("/*!re2c\n  [a-z]+ { return; }\n*/", { 'language' => 're2c' }) }.not_to raise_error
  end

  it 'smoke_readline: Smoke test: load readline and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('set editing-mode vi', { 'language' => 'readline' }) }.not_to raise_error
  end

  it 'smoke_regex: Smoke test: load regex and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'regex' }) }.not_to raise_error
  end

  it 'smoke_rego: Smoke test: load rego and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("package main\ndefault allow = false", { 'language' => 'rego' }) }.not_to raise_error
  end

  it 'smoke_requirements: Smoke test: load requirements and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('flask>=2.0', { 'language' => 'requirements' }) }.not_to raise_error
  end

  it 'smoke_rescript: Smoke test: load rescript and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('let x = 1', { 'language' => 'rescript' }) }.not_to raise_error
  end

  it 'smoke_robot: Smoke test: load robot and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'robot' }) }.not_to raise_error
  end

  it 'smoke_roc: Smoke test: load roc and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'roc' }) }.not_to raise_error
  end

  it 'smoke_ron: Smoke test: load ron and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('(key: "value")', { 'language' => 'ron' }) }.not_to raise_error
  end

  it 'smoke_rst: Smoke test: load rst and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("Hello\n=====\n\nWorld", { 'language' => 'rst' }) }.not_to raise_error
  end

  it 'smoke_rtf: Smoke test: load rtf and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('{\\rtf1 hello}', { 'language' => 'rtf' }) }.not_to raise_error
  end

  it 'smoke_ruby: Smoke test: load ruby and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('puts \'hello\'', { 'language' => 'ruby' }) }.not_to raise_error
  end

  it 'smoke_rust: Smoke test: load rust and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('fn main() {}', { 'language' => 'rust' }) }.not_to raise_error
  end

  it 'smoke_scala: Smoke test: load scala and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('object Main', { 'language' => 'scala' }) }.not_to raise_error
  end

  it 'smoke_scheme: Smoke test: load scheme and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('(define x 1)', { 'language' => 'scheme' }) }.not_to raise_error
  end

  it 'smoke_scss: Smoke test: load scss and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("$color: red;\nbody { color: $color; }", { 'language' => 'scss' }) }.not_to raise_error
  end

  it 'smoke_slang: Smoke test: load slang and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'slang' }) }.not_to raise_error
  end

  it 'smoke_smali: Smoke test: load smali and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process(".class public LMain;\n.super Ljava/lang/Object;", { 'language' => 'smali' }) }.not_to raise_error
  end

  it 'smoke_smalltalk: Smoke test: load smalltalk and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'smalltalk' }) }.not_to raise_error
  end

  it 'smoke_smithy: Smoke test: load smithy and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("namespace example\nstring MyString", { 'language' => 'smithy' }) }.not_to raise_error
  end

  it 'smoke_sml: Smoke test: load sml and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'sml' }) }.not_to raise_error
  end

  it 'smoke_snakemake: Smoke test: load snakemake and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'snakemake' }) }.not_to raise_error
  end

  it 'smoke_solidity: Smoke test: load solidity and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("pragma solidity ^0.8.0;\ncontract Main {}", { 'language' => 'solidity' }) }.not_to raise_error
  end

  it 'smoke_souffle: Smoke test: load souffle and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'souffle' }) }.not_to raise_error
  end

  it 'smoke_sourcepawn: Smoke test: load sourcepawn and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'sourcepawn' }) }.not_to raise_error
  end

  it 'smoke_sparql: Smoke test: load sparql and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('SELECT ?s WHERE { ?s ?p ?o }', { 'language' => 'sparql' }) }.not_to raise_error
  end

  it 'smoke_sql: Smoke test: load sql and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('SELECT 1;', { 'language' => 'sql' }) }.not_to raise_error
  end

  it 'smoke_sql_bigquery: Smoke test: load sql_bigquery and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'sql_bigquery' }) }.not_to raise_error
  end

  it 'smoke_squirrel: Smoke test: load squirrel and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('function main() {}', { 'language' => 'squirrel' }) }.not_to raise_error
  end

  it 'smoke_ssh_config: Smoke test: load ssh_config and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("Host example\n  HostName example.com", { 'language' => 'ssh_config' }) }.not_to raise_error
  end

  it 'smoke_stan: Smoke test: load stan and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'stan' }) }.not_to raise_error
  end

  it 'smoke_starlark: Smoke test: load starlark and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('def hello(): pass', { 'language' => 'starlark' }) }.not_to raise_error
  end

  it 'smoke_superhtml: Smoke test: load superhtml and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'superhtml' }) }.not_to raise_error
  end

  it 'smoke_svelte: Smoke test: load svelte and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('<script>let x = 1;</script>', { 'language' => 'svelte' }) }.not_to raise_error
  end

  it 'smoke_sway: Smoke test: load sway and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'sway' }) }.not_to raise_error
  end

  it 'smoke_swift: Smoke test: load swift and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('print("hello")', { 'language' => 'swift' }) }.not_to raise_error
  end

  it 'smoke_systemverilog: Smoke test: load systemverilog and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'systemverilog' }) }.not_to raise_error
  end

  it 'smoke_tablegen: Smoke test: load tablegen and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('def Hello : Base {}', { 'language' => 'tablegen' }) }.not_to raise_error
  end

  it 'smoke_tact: Smoke test: load tact and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'tact' }) }.not_to raise_error
  end

  it 'smoke_tcl: Smoke test: load tcl and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('puts hello', { 'language' => 'tcl' }) }.not_to raise_error
  end

  it 'smoke_teal: Smoke test: load teal and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'teal' }) }.not_to raise_error
  end

  it 'smoke_templ: Smoke test: load templ and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'templ' }) }.not_to raise_error
  end

  it 'smoke_tera: Smoke test: load tera and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'tera' }) }.not_to raise_error
  end

  it 'smoke_terraform: Smoke test: load terraform and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('resource "null_resource" "main" {}', { 'language' => 'terraform' }) }.not_to raise_error
  end

  it 'smoke_test: Smoke test: load test and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("===========\nTest\n===========\n---\n(node)", { 'language' => 'test' }) }.not_to raise_error
  end

  it 'smoke_textproto: Smoke test: load textproto and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('key: "value"', { 'language' => 'textproto' }) }.not_to raise_error
  end

  it 'smoke_thrift: Smoke test: load thrift and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('service HelloService {}', { 'language' => 'thrift' }) }.not_to raise_error
  end

  it 'smoke_tlaplus: Smoke test: load tlaplus and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("---- MODULE Main ----\n====", { 'language' => 'tlaplus' }) }.not_to raise_error
  end

  it 'smoke_tmux: Smoke test: load tmux and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'tmux' }) }.not_to raise_error
  end

  it 'smoke_todotxt: Smoke test: load todotxt and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'todotxt' }) }.not_to raise_error
  end

  it 'smoke_toml: Smoke test: load toml and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('key = "value"', { 'language' => 'toml' }) }.not_to raise_error
  end

  it 'smoke_tsv: Smoke test: load tsv and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("a\tb\tc\n1\t2\t3", { 'language' => 'tsv' }) }.not_to raise_error
  end

  it 'smoke_tsx: Smoke test: load tsx and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('const App = () => <div />;', { 'language' => 'tsx' }) }.not_to raise_error
  end

  it 'smoke_turtle: Smoke test: load turtle and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'turtle' }) }.not_to raise_error
  end

  it 'smoke_twig: Smoke test: load twig and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('{{ variable }}', { 'language' => 'twig' }) }.not_to raise_error
  end

  it 'smoke_typescript: Smoke test: load typescript and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('const x: number = 42;', { 'language' => 'typescript' }) }.not_to raise_error
  end

  it 'smoke_typespec: Smoke test: load typespec and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'typespec' }) }.not_to raise_error
  end

  it 'smoke_typoscript: Smoke test: load typoscript and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'typoscript' }) }.not_to raise_error
  end

  it 'smoke_typst: Smoke test: load typst and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('#let x = 1', { 'language' => 'typst' }) }.not_to raise_error
  end

  it 'smoke_udev: Smoke test: load udev and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('ACTION=="add", KERNEL=="sd*"', { 'language' => 'udev' }) }.not_to raise_error
  end

  it 'smoke_ungrammar: Smoke test: load ungrammar and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("Root = Item*\nItem = 'token'", { 'language' => 'ungrammar' }) }.not_to raise_error
  end

  it 'smoke_uxntal: Smoke test: load uxntal and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('|0100 LIT 01', { 'language' => 'uxntal' }) }.not_to raise_error
  end

  it 'smoke_v: Smoke test: load v and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('fn main() {}', { 'language' => 'v' }) }.not_to raise_error
  end

  it 'smoke_vb: Smoke test: load vb and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("Module Main\nEnd Module", { 'language' => 'vb' }) }.not_to raise_error
  end

  it 'smoke_verilog: Smoke test: load verilog and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('module main; endmodule', { 'language' => 'verilog' }) }.not_to raise_error
  end

  it 'smoke_vhdl: Smoke test: load vhdl and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('entity main is end main;', { 'language' => 'vhdl' }) }.not_to raise_error
  end

  it 'smoke_vhs: Smoke test: load vhs and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'vhs' }) }.not_to raise_error
  end

  it 'smoke_vim: Smoke test: load vim and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('echo \'hello\'', { 'language' => 'vim' }) }.not_to raise_error
  end

  it 'smoke_vimdoc: Smoke test: load vimdoc and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'vimdoc' }) }.not_to raise_error
  end

  it 'smoke_vrl: Smoke test: load vrl and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'vrl' }) }.not_to raise_error
  end

  it 'smoke_vue: Smoke test: load vue and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('<template><div>hello</div></template>', { 'language' => 'vue' }) }.not_to raise_error
  end

  it 'smoke_wast: Smoke test: load wast and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('(module)', { 'language' => 'wast' }) }.not_to raise_error
  end

  it 'smoke_wat: Smoke test: load wat and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('(module)', { 'language' => 'wat' }) }.not_to raise_error
  end

  it 'smoke_wgsl: Smoke test: load wgsl and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('@vertex fn main() -> @builtin(position) vec4f { return vec4f(); }', { 'language' => 'wgsl' }) }.not_to raise_error
  end

  it 'smoke_wgsl_bevy: Smoke test: load wgsl_bevy and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'wgsl_bevy' }) }.not_to raise_error
  end

  it 'smoke_wit: Smoke test: load wit and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('package example:pkg;', { 'language' => 'wit' }) }.not_to raise_error
  end

  it 'smoke_wolfram: Smoke test: load wolfram and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'wolfram' }) }.not_to raise_error
  end

  it 'smoke_x86asm: Smoke test: load x86asm and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'x86asm' }) }.not_to raise_error
  end

  it 'smoke_xcompose: Smoke test: load xcompose and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('<Multi_key> <a> : "a"', { 'language' => 'xcompose' }) }.not_to raise_error
  end

  it 'smoke_xml: Smoke test: load xml and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process("<?xml version=\"1.0\"?>\n<root>hello</root>", { 'language' => 'xml' }) }.not_to raise_error
  end

  it 'smoke_yaml: Smoke test: load yaml and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('key: value', { 'language' => 'yaml' }) }.not_to raise_error
  end

  it 'smoke_yuck: Smoke test: load yuck and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('(defwidget main [] (label :text "hi"))', { 'language' => 'yuck' }) }.not_to raise_error
  end

  it 'smoke_zig: Smoke test: load zig and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('pub fn main() void {}', { 'language' => 'zig' }) }.not_to raise_error
  end

  it 'smoke_ziggy: Smoke test: load ziggy and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'ziggy' }) }.not_to raise_error
  end

  it 'smoke_ziggy_schema: Smoke test: load ziggy_schema and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('x', { 'language' => 'ziggy_schema' }) }.not_to raise_error
  end

  it 'smoke_zsh: Smoke test: load zsh and parse a simple snippet' do
    expect { TreeSitterLanguagePack.process('echo hello', { 'language' => 'zsh' }) }.not_to raise_error
  end
end
