# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7a28870ed956f3bc905e5658d6a02739f99c913fd47058d0b86bf0780e634064
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
"""Pytest configuration for e2e tests."""
# Ensure the package is importable.
# The tree_sitter_language_pack package is expected to be installed in the current environment.
