# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4fd28d28be5d5c08a42b1adaeb8565a890c281118692f20fb4e08cfac6ad7fcf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
"""Pytest configuration for e2e tests."""
# Ensure the package is importable.
# The tree_sitter_language_pack package is expected to be installed in the current environment.
